//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#pragma mark Function Pointers

typedef void (*CDUnknownFunctionPointerType)(void); // return type and parameters are unknown

#pragma mark Named Structures

struct _CSRange {
    unsigned long long location;
    unsigned long long length;
};

struct _CSTypeRef {
    unsigned long long _opaque_1;
    unsigned long long _opaque_2;
};

#pragma mark -

//
// File: /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/Frameworks/RemoteInjection.framework/Versions/A/RemoteInjection
// UUID: EC29A5DA-9BFB-3A3F-BDD2-CC650D9307FA
//
//                           Arch: x86_64
//                Current version: 56120.0.0
//          Compatibility version: 1.0.0
//                 Source version: 56120.0.0.0.0
//       Minimum Mac OS X version: 10.9.0
//                    SDK version: 10.10.0
//
// Objective-C Garbage Collection: Unsupported
//

@interface RemoteBundleLoader : NSObject
{
    unsigned int _targetTask;
    int _targetPid;
    struct _CSTypeRef _remoteSymbolicator;
    struct _CSTypeRef _selfBundleSymbolicator;
    void *_remoteFunctionAddresses;
    const char *_bootstrappingText;
    const char *_secondLoaderText;
    struct _CSRange _bootstrappingCodeTextRange;
    struct _CSRange _secondLoaderRange;
}

+ (struct _CSTypeRef)symbolInSymbolicator:(struct _CSTypeRef)arg1 withName:(const char *)arg2 preferredOwner:(const char *)arg3;
- (BOOL)modifyTaskThreadsState:(CDUnknownFunctionPointerType)arg1;
- (BOOL)resumeAllThreads;
- (BOOL)suspendAllThreads;
- (BOOL)synchronouslyLoadMachO:(id)arg1 callingFunctionNamed:(id)arg2 argc:(int)arg3 argv:(const char **)arg4;
- (BOOL)scheduleLibraryLoad:(id)arg1 callingFunction:(id)arg2 argc:(int)arg3 argv:(const char **)arg4 error:(id *)arg5;
- (void)dealloc;
- (BOOL)libraryIsPresent:(id)arg1;
- (id)initWithTask:(unsigned int)arg1;

@end

