//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#pragma mark Blocks

typedef void (^CDUnknownBlockType)(void); // return type and parameters are unknown

#pragma mark -

//
// File: /Applications/Xcode-7GM.app/Contents/SharedFrameworks/DVTAnalyticsClient.framework/Versions/A/DVTAnalyticsClient
// UUID: F9505534-EB3E-30F1-8479-35A933E02FA4
//
//                           Arch: x86_64
//                Current version: 1.0.0
//          Compatibility version: 1.0.0
//                 Source version: 8223.0.0.0.0
//       Minimum Mac OS X version: 10.9.0
//                    SDK version: 10.11.0
//
// Objective-C Garbage Collection: Unsupported
//
//                       Run path: @loader_path/../../../../Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib
//                               = /Applications/Xcode-7GM.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib
//                       Run path: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib
//                               = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib
//                       Run path: @loader_path/../../../../Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks/
//                               = /Applications/Xcode-7GM.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks
//

@protocol DVTAnalyticsServiceURLComponentProviding <NSObject>
@property(readonly) NSDictionary *parameters;
@property(readonly) NSArray *pathComponents;
@end

@protocol DVTServicesJSONSerialization <NSObject>
- (id)JSONRepresentation;

@optional
+ (id)objectFromJSONRepresentation:(id)arg1 error:(id *)arg2;
@end

@protocol NSObject
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;
@property(readonly) unsigned long long hash;
- (struct _NSZone *)zone;
- (unsigned long long)retainCount;
- (id)autorelease;
- (oneway void)release;
- (id)retain;
- (BOOL)respondsToSelector:(SEL)arg1;
- (BOOL)conformsToProtocol:(Protocol *)arg1;
- (BOOL)isMemberOfClass:(Class)arg1;
- (BOOL)isKindOfClass:(Class)arg1;
- (BOOL)isProxy;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2 withObject:(id)arg3;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2;
- (id)performSelector:(SEL)arg1;
- (id)self;
- (Class)class;
- (BOOL)isEqual:(id)arg1;

@optional
@property(readonly, copy) NSString *debugDescription;
@end

@protocol NSURLSessionDelegate <NSObject>

@optional
- (void)URLSessionDidFinishEventsForBackgroundURLSession:(NSURLSession *)arg1;
- (void)URLSession:(NSURLSession *)arg1 didReceiveChallenge:(NSURLAuthenticationChallenge *)arg2 completionHandler:(void (^)(long long, NSURLCredential *))arg3;
- (void)URLSession:(NSURLSession *)arg1 didBecomeInvalidWithError:(NSError *)arg2;
@end

@protocol __ARCLiteIndexedSubscripting__
- (void)setObject:(id)arg1 atIndexedSubscript:(unsigned long long)arg2;
- (id)objectAtIndexedSubscript:(unsigned long long)arg1;
@end

@protocol __ARCLiteKeyedSubscripting__
- (void)setObject:(id)arg1 forKeyedSubscript:(id)arg2;
- (id)objectForKeyedSubscript:(id)arg1;
@end

@interface DVTAnalyticsAppIdentifier : NSObject <DVTAnalyticsServiceURLComponentProviding, DVTServicesJSONSerialization>
{
    BOOL _isBeta;
    NSString *_adamId;
    NSString *_bundleIdentifier;
    NSString *_version;
    NSString *_buildNumber;
}

+ (id)objectFromJSONRepresentation:(id)arg1 error:(id *)arg2;
+ (id)appIdentifierWithAdamId:(id)arg1 bundleIdentifier:(id)arg2 version:(id)arg3 buildNumber:(id)arg4 isBeta:(BOOL)arg5;
@property(readonly) BOOL isBeta; // @synthesize isBeta=_isBeta;
@property(readonly) NSString *buildNumber; // @synthesize buildNumber=_buildNumber;
@property(readonly) NSString *version; // @synthesize version=_version;
@property(readonly) NSString *bundleIdentifier; // @synthesize bundleIdentifier=_bundleIdentifier;
@property(readonly) NSString *adamId; // @synthesize adamId=_adamId;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
- (id)JSONRepresentation;
@property(readonly) NSDictionary *parameters;
@property(readonly) NSArray *pathComponents;
@property(readonly) unsigned long long hash;
- (BOOL)isEqual:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

@interface DVTAnalyticsClientTool : NSObject
{
    DVTAnalyticsAppIdentifier *_appIdentifier;
    DVTAnalyticsCrashPointIdentifier *_crashPointIdentifier;
    DVTDeveloperAccount *_developerAccount;
    NSString *_name;
    NSArray *_arguments;
    NSFileHandle *_standardInput;
    NSFileHandle *_standardOutput;
    NSFileHandle *_standardError;
    NSString *_developerAccountUser;
    NSString *_appAdamId;
    NSString *_appBundleId;
    NSString *_appVersion;
    NSString *_appBuild;
    NSString *_isBeta;
    NSString *_crashPointId;
    NSArray *_deviceFamilies;
    NSArray *_osVersions;
    NSString *_lastCrashReporterKey;
    NSString *_lastCrashReportTime;
    long long _command;
    DVTServicesSession *_session;
}

+ (id)analyticsClientTool;
@property(retain) DVTServicesSession *session; // @synthesize session=_session;
@property long long command; // @synthesize command=_command;
@property(retain) NSString *lastCrashReportTime; // @synthesize lastCrashReportTime=_lastCrashReportTime;
@property(retain) NSString *lastCrashReporterKey; // @synthesize lastCrashReporterKey=_lastCrashReporterKey;
@property(retain) NSArray *osVersions; // @synthesize osVersions=_osVersions;
@property(retain) NSArray *deviceFamilies; // @synthesize deviceFamilies=_deviceFamilies;
@property(retain) NSString *crashPointId; // @synthesize crashPointId=_crashPointId;
@property(retain) NSString *isBeta; // @synthesize isBeta=_isBeta;
@property(retain) NSString *appBuild; // @synthesize appBuild=_appBuild;
@property(retain) NSString *appVersion; // @synthesize appVersion=_appVersion;
@property(retain) NSString *appBundleId; // @synthesize appBundleId=_appBundleId;
@property(retain) NSString *appAdamId; // @synthesize appAdamId=_appAdamId;
@property(retain) NSString *developerAccountUser; // @synthesize developerAccountUser=_developerAccountUser;
@property(retain) NSFileHandle *standardError; // @synthesize standardError=_standardError;
@property(retain) NSFileHandle *standardOutput; // @synthesize standardOutput=_standardOutput;
@property(retain) NSFileHandle *standardInput; // @synthesize standardInput=_standardInput;
@property(retain) NSArray *arguments; // @synthesize arguments=_arguments;
@property(retain) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (id)_sessionWithError:(id *)arg1;
@property(readonly) DVTDeveloperAccount *developerAccount; // @synthesize developerAccount=_developerAccount;
@property(readonly) DVTAnalyticsCrashPointIdentifier *crashPointIdentifier; // @synthesize crashPointIdentifier=_crashPointIdentifier;
@property(readonly) DVTAnalyticsAppIdentifier *appIdentifier; // @synthesize appIdentifier=_appIdentifier;
- (BOOL)_ensureRequiredArgumentsWithError:(id *)arg1;
- (BOOL)_parseArgumentsWithError:(id *)arg1;
- (BOOL)_downloadMoreLogsWithError:(id *)arg1;
- (BOOL)_downloadLogsWithError:(id *)arg1;
- (BOOL)_listLogsWithError:(id *)arg1;
- (BOOL)_executeWithError:(id *)arg1 executionBlock:(CDUnknownBlockType)arg2;
- (id)_stringFromCommand:(long long)arg1;
- (long long)_commandFromString:(id)arg1 error:(id *)arg2;
- (BOOL)runWithError:(id *)arg1;

@end

@interface DVTAnalyticsCrashPointData : NSObject <DVTServicesJSONSerialization>
{
    DVTAnalyticsCrashPointIdentifier *_crashPointIdentifier;
    NSString *_adamId;
    NSString *_appVersion;
    NSString *_appBuild;
    NSString *_bundleId;
    NSString *_isBeta;
    NSString *_crashPointId;
}

@property(retain) NSString *crashPointId; // @synthesize crashPointId=_crashPointId;
@property(retain, nonatomic) NSString *isBeta; // @synthesize isBeta=_isBeta;
@property(retain) NSString *bundleId; // @synthesize bundleId=_bundleId;
@property(retain) NSString *appBuild; // @synthesize appBuild=_appBuild;
@property(retain) NSString *appVersion; // @synthesize appVersion=_appVersion;
@property(retain) NSString *adamId; // @synthesize adamId=_adamId;
- (void).cxx_destruct;
- (id)JSONRepresentation;
@property(readonly) DVTAnalyticsCrashPointIdentifier *crashPointIdentifier; // @synthesize crashPointIdentifier=_crashPointIdentifier;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

@interface DVTAnalyticsServiceOption : NSObject
{
    NSString *_name;
    NSString *_value;
}

+ (id)dictionaryFromOptions:(id)arg1;
+ (id)optionWithName:(id)arg1 value:(id)arg2;
@property(readonly) NSString *value; // @synthesize value=_value;
@property(readonly) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (id)description;

@end

@interface DVTAnalyticsCrashPointDateDistributionOption : DVTAnalyticsServiceOption
{
}

+ (id)distributionWithStandardEndDate;
+ (id)distributionWithStandardStartDate;
+ (id)distributionWithDate:(id)arg1 type:(long long)arg2;
+ (id)_dateFormatter;
+ (id)_nameForType:(long long)arg1;
+ (void)initialize;

@end

@interface DVTAnalyticsCrashPointDeviceFamilyData : NSObject <DVTServicesJSONSerialization>
{
    NSString *_deviceFamily;
    NSNumber *_value;
}

+ (id)objectFromJSONRepresentation:(id)arg1 error:(id *)arg2;
@property(readonly) NSNumber *value; // @synthesize value=_value;
@property(readonly) NSString *deviceFamily; // @synthesize deviceFamily=_deviceFamily;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
- (BOOL)isEqual:(id)arg1;
- (id)JSONRepresentation;
- (id)initWithDeviceFamily:(id)arg1 value:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

@interface DVTAnalyticsCrashPointDeviceFamilyDistribution : NSObject <DVTServicesJSONSerialization>
{
    NSArray *_deviceFamilyData;
}

@property(readonly) NSArray *deviceFamilyData; // @synthesize deviceFamilyData=_deviceFamilyData;
- (void).cxx_destruct;
- (id)JSONRepresentation;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

@interface DVTAnalyticsCrashPointDeviceFamilyDistributionOption : DVTAnalyticsServiceOption
{
}

+ (id)distributionWithDeviceFamilies:(id)arg1;

@end

@interface DVTAnalyticsCrashPointDeviceFilter : DVTAnalyticsServiceOption
{
}

+ (id)filterWithDeviceModel:(id)arg1;

@end

@interface DVTAnalyticsCrashPointDistributionOptions : NSObject
{
    NSArray *_options;
}

+ (id)distributionWithDefaultDateRangeAndDeviceFamilies:(id)arg1;
+ (id)distributionWithDefaultDateRangeAndOSVersions:(id)arg1;
+ (id)distributionWithDefaultDateRange;
+ (id)distributionStartDate:(id)arg1 endDate:(id)arg2 osVersions:(id)arg3 deviceFamilies:(id)arg4;
+ (id)_distributionWithStartDateDistro:(id)arg1 endDateDistro:(id)arg2 osVersions:(id)arg3 deviceFamilies:(id)arg4;
@property(readonly) NSArray *options; // @synthesize options=_options;
- (void).cxx_destruct;

@end

@interface DVTAnalyticsCrashPointDownloadData : DVTAnalyticsCrashPointData
{
    DVTAnalyticsCrashPointOSVersionDistribution *_osVersionDistribution;
    DVTAnalyticsCrashPointDeviceFamilyDistribution *_deviceFamilyDistribution;
    DVTAnalyticsCrashPointTimeDistribution *_crashPointTimeSeries;
    DVTAnalyticsCrashPointLogList *_logList;
}

+ (id)crashPointForSession:(id)arg1 crashPointIdentifier:(id)arg2 distributionOptions:(id)arg3 error:(id *)arg4;
@property(retain) DVTAnalyticsCrashPointLogList *logList; // @synthesize logList=_logList;
@property(retain) DVTAnalyticsCrashPointTimeDistribution *crashPointTimeSeries; // @synthesize crashPointTimeSeries=_crashPointTimeSeries;
@property(retain) DVTAnalyticsCrashPointDeviceFamilyDistribution *deviceFamilyDistribution; // @synthesize deviceFamilyDistribution=_deviceFamilyDistribution;
@property(retain) DVTAnalyticsCrashPointOSVersionDistribution *osVersionDistribution; // @synthesize osVersionDistribution=_osVersionDistribution;
- (void).cxx_destruct;
- (id)JSONRepresentation;

@end

@interface DVTAnalyticsCrashPointIdentifier : NSObject <DVTAnalyticsServiceURLComponentProviding, DVTServicesJSONSerialization>
{
    DVTAnalyticsAppIdentifier *_appIdentifier;
    NSString *_crashPointId;
}

+ (id)objectFromJSONRepresentation:(id)arg1 error:(id *)arg2;
+ (id)crashPointIdentifierWithAppIdentifier:(id)arg1 crashPointId:(id)arg2;
@property(readonly) NSString *crashPointId; // @synthesize crashPointId=_crashPointId;
@property(readonly) DVTAnalyticsAppIdentifier *appIdentifier; // @synthesize appIdentifier=_appIdentifier;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
- (id)JSONRepresentation;
@property(readonly) NSDictionary *parameters;
@property(readonly) NSArray *pathComponents;
@property(readonly) unsigned long long hash;
- (BOOL)isEqual:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

@interface DVTAnalyticsCrashPointList : NSObject <DVTServicesJSONSerialization>
{
    DVTAnalyticsAppIdentifier *_appIdentifier;
    NSArray *_topCrashes;
    NSString *_crashesSortedBy;
    NSString *_adamId;
    NSString *_appVersion;
    NSString *_appBuild;
    NSString *_bundleId;
    NSString *_isBeta;
    NSNumber *_numCrashes;
}

+ (id)crashPointListForSession:(id)arg1 appIdentifier:(id)arg2 options:(id)arg3 error:(id *)arg4;
@property(retain) NSNumber *numCrashes; // @synthesize numCrashes=_numCrashes;
@property(retain, nonatomic) NSString *isBeta; // @synthesize isBeta=_isBeta;
@property(retain) NSString *bundleId; // @synthesize bundleId=_bundleId;
@property(retain) NSString *appBuild; // @synthesize appBuild=_appBuild;
@property(retain) NSString *appVersion; // @synthesize appVersion=_appVersion;
@property(retain) NSString *adamId; // @synthesize adamId=_adamId;
@property(readonly) NSString *crashesSortedBy; // @synthesize crashesSortedBy=_crashesSortedBy;
@property(readonly) NSArray *topCrashes; // @synthesize topCrashes=_topCrashes;
- (void).cxx_destruct;
- (id)JSONRepresentation;
@property(readonly) DVTAnalyticsAppIdentifier *appIdentifier; // @synthesize appIdentifier=_appIdentifier;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

@interface DVTAnalyticsCrashPointLogData : NSObject <DVTServicesJSONSerialization>
{
    NSString *_data;
}

@property(readonly) NSString *data; // @synthesize data=_data;
- (void).cxx_destruct;
- (id)JSONRepresentation;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

@interface DVTAnalyticsCrashPointLogList : NSObject <DVTServicesJSONSerialization>
{
    BOOL _hasMoreLogs;
    NSString *_lastCrashPointTime;
    NSString *_lastCrashReporterKey;
    NSArray *_logData;
    NSString *_moreLogs;
}

+ (id)logListWithHasMoreLogs:(BOOL)arg1 lastCrashPointTime:(id)arg2 lastCrashReporterKey:(id)arg3 logData:(id)arg4;
@property(readonly) NSString *moreLogs; // @synthesize moreLogs=_moreLogs;
@property(readonly) NSArray *logData; // @synthesize logData=_logData;
@property(readonly) NSString *lastCrashReporterKey; // @synthesize lastCrashReporterKey=_lastCrashReporterKey;
@property(readonly) NSString *lastCrashPointTime; // @synthesize lastCrashPointTime=_lastCrashPointTime;
- (void).cxx_destruct;
- (id)JSONRepresentation;
@property(readonly) BOOL hasMoreLogs; // @synthesize hasMoreLogs=_hasMoreLogs;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

@interface DVTAnalyticsCrashPointMoreLogsData : DVTAnalyticsCrashPointData
{
    DVTAnalyticsCrashPointLogList *_logList;
    NSString *_moreLogs;
    NSString *_lastCrashPointTime;
    NSString *_lastCrashReporterKey;
    NSArray *_logData;
}

+ (id)crashPointUpdateForSession:(id)arg1 crashPointIdentifier:(id)arg2 moreLogsOptions:(id)arg3 error:(id *)arg4;
@property(retain) NSArray *logData; // @synthesize logData=_logData;
@property(retain) NSString *lastCrashReporterKey; // @synthesize lastCrashReporterKey=_lastCrashReporterKey;
@property(retain) NSString *lastCrashPointTime; // @synthesize lastCrashPointTime=_lastCrashPointTime;
@property(retain) NSString *moreLogs; // @synthesize moreLogs=_moreLogs;
- (void).cxx_destruct;
- (id)JSONRepresentation;
@property(readonly) DVTAnalyticsCrashPointLogList *logList; // @synthesize logList=_logList;

@end

@interface DVTAnalyticsCrashPointOSDistributionOption : DVTAnalyticsServiceOption
{
}

+ (id)distributionWithOSVersions:(id)arg1;

@end

@interface DVTAnalyticsCrashPointOSFilter : DVTAnalyticsServiceOption
{
}

+ (id)filterWithOSVersion:(id)arg1;

@end

@interface DVTAnalyticsCrashPointOSVersionData : NSObject <DVTServicesJSONSerialization>
{
    NSString *_osVersion;
    NSNumber *_value;
}

+ (id)objectFromJSONRepresentation:(id)arg1 error:(id *)arg2;
@property(readonly) NSNumber *value; // @synthesize value=_value;
@property(readonly) NSString *osVersion; // @synthesize osVersion=_osVersion;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
- (BOOL)isEqual:(id)arg1;
- (id)JSONRepresentation;
- (id)initWithOSVersion:(id)arg1 value:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

@interface DVTAnalyticsCrashPointOSVersionDistribution : NSObject <DVTServicesJSONSerialization>
{
    NSArray *_osVersionData;
}

@property(readonly) NSArray *osVersionData; // @synthesize osVersionData=_osVersionData;
- (void).cxx_destruct;
- (id)JSONRepresentation;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

@interface DVTAnalyticsCrashPointSortingOption : DVTAnalyticsServiceOption
{
}

+ (id)uniqueDevicesCountSortingOption;
+ (id)crashlogsCountSortingOption;
+ (id)_sortingOptionWithValue:(id)arg1;

@end

@interface DVTAnalyticsCrashPointSummary : NSObject <DVTServicesJSONSerialization>
{
    NSString *_crashPointId;
    NSString *_crashPointString;
    NSString *_sourceFileName;
    NSNumber *_sourceFileLineNumber;
    NSNumber *_rollingOccurenceCount;
    NSNumber *_rollingUniqueDeviceCount;
}

@property(readonly) NSNumber *rollingUniqueDeviceCount; // @synthesize rollingUniqueDeviceCount=_rollingUniqueDeviceCount;
@property(readonly) NSNumber *rollingOccurenceCount; // @synthesize rollingOccurenceCount=_rollingOccurenceCount;
@property(readonly) NSNumber *sourceFileLineNumber; // @synthesize sourceFileLineNumber=_sourceFileLineNumber;
@property(readonly) NSString *sourceFileName; // @synthesize sourceFileName=_sourceFileName;
@property(readonly) NSString *crashPointString; // @synthesize crashPointString=_crashPointString;
@property(readonly) NSString *crashPointId; // @synthesize crashPointId=_crashPointId;
- (void).cxx_destruct;
- (id)JSONRepresentation;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

@interface DVTAnalyticsCrashPointTimeData : NSObject <DVTServicesJSONSerialization>
{
    NSString *_periodStart;
    NSNumber *_value;
}

+ (id)objectFromJSONRepresentation:(id)arg1 error:(id *)arg2;
@property(readonly) NSNumber *value; // @synthesize value=_value;
@property(readonly) NSString *periodStart; // @synthesize periodStart=_periodStart;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
- (BOOL)isEqual:(id)arg1;
- (id)JSONRepresentation;
- (id)initWithPeriodStart:(id)arg1 value:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

@interface DVTAnalyticsCrashPointTimeDistribution : NSObject <DVTServicesJSONSerialization>
{
    NSArray *_timeSeriesData;
}

@property(readonly) NSArray *timeSeriesData; // @synthesize timeSeriesData=_timeSeriesData;
- (void).cxx_destruct;
- (id)JSONRepresentation;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

@interface DVTAnalyticsService : NSObject
{
    NSArray *_pathComponents;
    NSDictionary *_parameters;
    DVTServicesType *_responseType;
    NSArray *_orderedParameters;
}

+ (id)_combinedParametersFromOptions:(id)arg1 andURLComponentProvider:(id)arg2;
+ (id)serviceWithIdentifier:(id)arg1 pathComponents:(id)arg2 parameters:(id)arg3;
+ (void)initialize;
@property(readonly) NSArray *orderedParameters; // @synthesize orderedParameters=_orderedParameters;
@property(copy) DVTServicesType *responseType; // @synthesize responseType=_responseType;
@property(copy) NSDictionary *parameters; // @synthesize parameters=_parameters;
@property(copy) NSArray *pathComponents; // @synthesize pathComponents=_pathComponents;
- (void).cxx_destruct;
- (id)_requestQueryString;
- (id)_requestEndpoint;
- (id)_responseFromServiceWithSession:(id)arg1 error:(id *)arg2;
- (id)resultWithSession:(id)arg1 error:(id *)arg2;
- (id)initWithExtension:(id)arg1 pathComponents:(id)arg2 parameters:(id)arg3;

@end

@interface DVTAnalyticsDownloadCrashPointService : DVTAnalyticsService
{
}

+ (id)servicePathComponents;
+ (id)downloadCrashPointServiceWithCrashPointIdentifier:(id)arg1 distributionOptions:(id)arg2;

@end

@interface DVTAnalyticsDownloadMoreLogsOptions : NSObject
{
    NSArray *_options;
}

+ (id)downloadMoreLogsOptionsWithLastCrashReportKey:(id)arg1 lastCrashPointTime:(id)arg2;
@property(readonly) NSArray *options; // @synthesize options=_options;
- (void).cxx_destruct;

@end

@interface DVTAnalyticsDownloadMoreLogsService : DVTAnalyticsService
{
}

+ (id)servicePathComponents;
+ (id)downloadMoreLogsServiceWithCrashPointIdentifier:(id)arg1 options:(id)arg2;

@end

@interface DVTAnalyticsLastCrashPointTimeOption : DVTAnalyticsServiceOption
{
}

+ (id)optionWithLastCrashPointTime:(id)arg1;

@end

@interface DVTAnalyticsLastCrashReportKeyOption : DVTAnalyticsServiceOption
{
}

+ (id)optionWithLastCrashReportKey:(id)arg1;

@end

@interface DVTAnalyticsListTopCrashPointsService : DVTAnalyticsService
{
}

+ (id)servicePathComponents;
+ (id)listTopCrashPointsServiceWithAppIdentifier:(id)arg1 options:(id)arg2;

@end

@interface DVTAnalyticsRequest : DVTServicesRequest <NSURLSessionDelegate>
{
    NSString *_endpoint;
    NSString *_query;
}

+ (id)requestWithSession:(id)arg1 endpoint:(id)arg2 query:(id)arg3;
+ (void)initialize;
@property(readonly) NSString *query; // @synthesize query=_query;
@property(readonly) NSString *endpoint; // @synthesize endpoint=_endpoint;
- (void).cxx_destruct;
- (void)URLSession:(id)arg1 didReceiveChallenge:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (id)responseBySendingRequestWithError:(id *)arg1;
- (id)_urlSessionConfiguration;
- (id)_additionalHTTPHeaders;
- (id)_credentials;
- (id)requestURL;
- (id)_analyticsAPIVersion;
- (id)_analyticsServiceHostname;
- (id)initWithSession:(id)arg1 endpoint:(id)arg2 query:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

@interface DVTAnalyticsResponse : NSObject
{
    NSDictionary *_payload;
}

+ (id)responseFromData:(id)arg1 httpResponse:(id)arg2 error:(id *)arg3;
@property(readonly) NSDictionary *payload; // @synthesize payload=_payload;
- (void).cxx_destruct;
- (id)initWithPayload:(id)arg1;

@end

