//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#pragma mark Blocks

typedef void (^CDUnknownBlockType)(void); // return type and parameters are unknown

#pragma mark Named Structures

struct Argument {
    void *_field1;
    unsigned int _field2;
    unsigned int _field3;
    unsigned int _field4;
    unsigned short _field5;
    unsigned short _field6;
};

struct CoreFunction {
    unsigned int _field1;
    unsigned int _field2;
    unsigned short _field3;
    unsigned short _field4;
    union {
        unsigned long long _field1;
        unsigned long long _field2;
    } _field5;
    struct Argument _field6;
    struct Argument _field7[16];
    unsigned int _field8;
    unsigned int _field9;
    void *_field10;
    void *_field11;
};

struct Function {
    struct CoreFunction _field1;
    unsigned long long _field2;
    unsigned long long _field3;
    unsigned long long *_field4;
    unsigned short _field5;
    unsigned short _field6;
    int _field7;
    void *_field8;
    unsigned int _field9;
    unsigned int _field10;
    unsigned long long _field11;
    unsigned long long _field12;
    struct Function *_field13;
    void *_field14;
};

struct _CSTypeRef {
    unsigned long long _opaque_1;
    unsigned long long _opaque_2;
};

struct _NSRange {
    unsigned long long location;
    unsigned long long length;
};

struct __hash_node<std::__1::__hash_value_type<unsigned long long, DYDevice *>, void *>;

struct dy_timebase {
    struct mach_timebase_info mach_timebase;
    unsigned long long nanoseconds_since_epoch_timestamp;
    unsigned long long mach_timestamp;
};

struct mach_timebase_info {
    unsigned int numer;
    unsigned int denom;
};

struct unique_ptr<std::__1::__hash_node<std::__1::__hash_value_type<unsigned long long, DYDevice *>, void *>*[], std::__1::__bucket_list_deallocator<std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<unsigned long long, DYDevice *>, void *>*>>> {
    struct __compressed_pair<std::__1::__hash_node<std::__1::__hash_value_type<unsigned long long, DYDevice *>, void *>**, std::__1::__bucket_list_deallocator<std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<unsigned long long, DYDevice *>, void *>*>>> {
        struct __hash_node<std::__1::__hash_value_type<unsigned long long, DYDevice *>, void *> **__first_;
        struct __bucket_list_deallocator<std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<unsigned long long, DYDevice *>, void *>*>> {
            struct __compressed_pair<unsigned long, std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<unsigned long long, DYDevice *>, void *>*>> {
                unsigned long long __first_;
            } __data_;
        } __second_;
    } __ptr_;
};

struct unordered_map<unsigned long long, DYDevice *, std::__1::hash<unsigned long long>, std::__1::equal_to<unsigned long long>, std::__1::allocator<std::__1::pair<const unsigned long long, DYDevice *>>> {
    struct __hash_table<std::__1::__hash_value_type<unsigned long long, DYDevice *>, std::__1::__unordered_map_hasher<unsigned long long, std::__1::__hash_value_type<unsigned long long, DYDevice *>, std::__1::hash<unsigned long long>, true>, std::__1::__unordered_map_equal<unsigned long long, std::__1::__hash_value_type<unsigned long long, DYDevice *>, std::__1::equal_to<unsigned long long>, true>, std::__1::allocator<std::__1::__hash_value_type<unsigned long long, DYDevice *>>> {
        struct unique_ptr<std::__1::__hash_node<std::__1::__hash_value_type<unsigned long long, DYDevice *>, void *>*[], std::__1::__bucket_list_deallocator<std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<unsigned long long, DYDevice *>, void *>*>>> __bucket_list_;
        struct __compressed_pair<std::__1::__hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<unsigned long long, DYDevice *>, void *>*>, std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<unsigned long long, DYDevice *>, void *>>> {
            struct __hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<unsigned long long, DYDevice *>, void *>*> {
                struct __hash_node<std::__1::__hash_value_type<unsigned long long, DYDevice *>, void *> *__next_;
            } __first_;
        } __p1_;
        struct __compressed_pair<unsigned long, std::__1::__unordered_map_hasher<unsigned long long, std::__1::__hash_value_type<unsigned long long, DYDevice *>, std::__1::hash<unsigned long long>, true>> {
            unsigned long long __first_;
        } __p2_;
        struct __compressed_pair<float, std::__1::__unordered_map_equal<unsigned long long, std::__1::__hash_value_type<unsigned long long, DYDevice *>, std::__1::equal_to<unsigned long long>, true>> {
            float __first_;
        } __p3_;
    } __table_;
};

struct vector<GPUTools::FD::Function, std::__1::allocator<GPUTools::FD::Function>> {
    struct Function *__begin_;
    struct Function *__end_;
    struct __compressed_pair<GPUTools::FD::Function *, std::__1::allocator<GPUTools::FD::Function>> {
        struct Function *__first_;
    } __end_cap_;
};

#pragma mark Typedef'd Structures

typedef struct {
    unsigned char _field1;
    unsigned char _field2;
    unsigned char _field3;
    unsigned char _field4;
    unsigned char _field5;
    unsigned char _field6;
    unsigned char _field7;
    unsigned char _field8;
    unsigned char _field9;
    unsigned char _field10;
    unsigned char _field11;
    unsigned char _field12;
    unsigned char _field13;
    unsigned char _field14;
    unsigned char _field15;
    unsigned char _field16;
} CDStruct_bd2f613f;

typedef struct {
    unsigned int bytes;
    unsigned int messages;
    unsigned int buffers;
    unsigned int aliases;
    unsigned long long standbyTimestamp;
    unsigned long long capturingTimestamp;
    unsigned long long processingTimestamp;
    unsigned long long invalidTimestamp;
    unsigned long long duration;
} CDStruct_faeedbfb;

typedef struct {
    double _field1;
    unsigned int _field2;
    unsigned int _field3;
    unsigned int _field4;
    unsigned int _field5;
} CDStruct_fc1d2ed0;

#pragma mark -

//
// File: /Applications/Xcode-7GM.app/Contents/SharedFrameworks/GPUToolsServices.framework/Versions/A/GPUToolsServices
// UUID: 5E659305-045D-3FB5-8184-E45973880A16
//
//                           Arch: x86_64
//                Current version: 18058.0.0
//          Compatibility version: 1.0.0
//                 Source version: 18058.0.0.0.0
//       Minimum Mac OS X version: 10.10.0
//                    SDK version: 10.11.0
//
// Objective-C Garbage Collection: Unsupported
//

@protocol DYCacheableResource <NSObject>
@property(readonly, nonatomic) unsigned long long cachingCost;
@end

@protocol NSCoding
- (id)initWithCoder:(NSCoder *)arg1;
- (void)encodeWithCoder:(NSCoder *)arg1;
@end

@protocol NSCopying
- (id)copyWithZone:(struct _NSZone *)arg1;
@end

@protocol NSObject
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;
@property(readonly) unsigned long long hash;
- (struct _NSZone *)zone;
- (unsigned long long)retainCount;
- (id)autorelease;
- (oneway void)release;
- (id)retain;
- (BOOL)respondsToSelector:(SEL)arg1;
- (BOOL)conformsToProtocol:(Protocol *)arg1;
- (BOOL)isMemberOfClass:(Class)arg1;
- (BOOL)isKindOfClass:(Class)arg1;
- (BOOL)isProxy;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2 withObject:(id)arg3;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2;
- (id)performSelector:(SEL)arg1;
- (id)self;
- (Class)class;
- (BOOL)isEqual:(id)arg1;

@optional
@property(readonly, copy) NSString *debugDescription;
@end

@interface DYEncoder : NSObject
{
    id m_delegate;
    unsigned int m_format;
}

@property(readonly, nonatomic) unsigned int format; // @synthesize format=m_format;
- (void).cxx_destruct;
- (id)decode:(id)arg1 format:(unsigned int)arg2 level:(unsigned int)arg3 width:(unsigned int)arg4 height:(unsigned int)arg5 options:(id)arg6;
- (id)encode:(id)arg1 level:(unsigned int)arg2 width:(unsigned int)arg3 height:(unsigned int)arg4 options:(id)arg5 errorCode:(int *)arg6;
- (id)describeOptions:(id)arg1;
- (void)setDelegate:(id)arg1;
- (id)options;
- (id)name;

@end

@interface DYASTCEncoder : DYEncoder
{
}

+ (void)initialize;
- (id)decode:(id)arg1 format:(unsigned int)arg2 level:(unsigned int)arg3 width:(unsigned int)arg4 height:(unsigned int)arg5 options:(id)arg6;
- (id)encode:(id)arg1 level:(unsigned int)arg2 width:(unsigned int)arg3 height:(unsigned int)arg4 options:(id)arg5 errorCode:(int *)arg6;
- (id)describeOptions:(id)arg1;
- (id)options;
- (id)name;

@end

@interface DYAnalyzerArchiveVisitor : DYInOrderInstructionFilesVisitor
{
    DYCaptureArchive *_archive;
    DYAnalyzerEngine *_engine;
    BOOL _bStartedFrameVisiting;
    int _captureBlockMode;
}

@property(readonly, retain, nonatomic) DYAnalyzerEngine *engine; // @synthesize engine=_engine;
- (void).cxx_destruct;
@property(nonatomic) BOOL unsorted; // @dynamic unsorted;
- (void)abort;
- (void)visitFunctionStreamFile:(id)arg1;
- (void)performPreCaptureVisitActions;
- (void)visitCaptureArchive:(id)arg1;
- (void)processFunctionStream:(id)arg1;
- (id)_loadEngineForAPI:(unsigned int)arg1 deviceInfo:(id)arg2;
- (void)_runAnalyzerWithBlock:(CDUnknownBlockType)arg1;
- (void)runAnalyzerProducingNoFindingsWithSingleFrameMode:(BOOL)arg1;
- (id)generateFindingsAndAddTo:(id)arg1 singleFrameMode:(BOOL)arg2;
- (id)initForArchive:(id)arg1;

@end

@interface DYAnalyzerEngine : NSObject
{
    int _captureBlockMode;
    int _frameNum;
    int _drawCallNum;
    DYAnalyzerFindingPool *_findingPool;
    int _funcCounter;
    unsigned long long _lastTimestamp;
    NSMutableDictionary *_heuristicPoolDict;
    CDUnknownBlockType _graphicsEngineInfoProvider;
    NSMutableDictionary *_resourceGroupObjectCoveragePool;
    NSMutableSet *_enabledHeuristicNameSet;
    DYDeviceInfo *_deviceInfo;
    CDUnknownBlockType _loadURLBlock;
    BOOL _singleFrameMode;
    BOOL _abort;
    BOOL _usePreSortHeuristics;
}

+ (id)getLocalizedString:(id)arg1 table:(id)arg2 forGraphicsAPI:(unsigned int)arg3;
+ (id)getLocalizedString:(id)arg1 forGraphicsAPI:(unsigned int)arg2;
@property(nonatomic) BOOL usePreSortHeuristics; // @synthesize usePreSortHeuristics=_usePreSortHeuristics;
@property(readonly, nonatomic) BOOL singleFrameMode; // @synthesize singleFrameMode=_singleFrameMode;
@property(nonatomic) int drawCallNum; // @synthesize drawCallNum=_drawCallNum;
@property(nonatomic) int frameNum; // @synthesize frameNum=_frameNum;
@property(retain, nonatomic) NSMutableDictionary *heuristicPoolDict; // @synthesize heuristicPoolDict=_heuristicPoolDict;
@property(nonatomic) int captureBlockMode; // @synthesize captureBlockMode=_captureBlockMode;
@property(retain, nonatomic) DYAnalyzerFindingPool *findingPool; // @synthesize findingPool=_findingPool;
@property(nonatomic) unsigned long long lastTimestamp; // @synthesize lastTimestamp=_lastTimestamp;
@property(nonatomic) int funcCounter; // @synthesize funcCounter=_funcCounter;
@property(copy, nonatomic) CDUnknownBlockType loadURLBlock; // @synthesize loadURLBlock=_loadURLBlock;
@property(copy, nonatomic) CDUnknownBlockType graphicsEngineInfoProvider; // @synthesize graphicsEngineInfoProvider=_graphicsEngineInfoProvider;
@property(retain, nonatomic) DYDeviceInfo *deviceInfo; // @synthesize deviceInfo=_deviceInfo;
- (void).cxx_destruct;
- (id)_newHeuristicPoolWithGraphicsEngineID:(unsigned long long)arg1;
- (id)newFrameStatisticsFinding;
- (unsigned int)_stateMirrorProcessFunctionAndAnnotate:(const struct Function *)arg1 functionIndex:(int)arg2;
- (unsigned int)_stateMirrorProcessFunction:(const struct Function *)arg1 functionIndex:(int)arg2;
- (void)_stateMirrorInitialize;
- (id)nameForVariable:(const char *)arg1 graphicsEngineID:(unsigned long long)arg2;
- (id)getObjectLabel:(unsigned long long)arg1 objectType:(int)arg2 objectID:(int)arg3;
- (BOOL)isUniformFullyPreUpdatedInCapture:(unsigned long long)arg1 programID:(unsigned int)arg2 uniformLoc:(int)arg3;
- (BOOL)isObjectDataUpdatedInCapture:(unsigned long long)arg1 objectType:(int)arg2 objectID:(unsigned int)arg3;
- (BOOL)doesProgramHaveLinkedShader:(unsigned long long)arg1 programID:(unsigned int)arg2 shaderType:(int)arg3;
- (BOOL)isObjectCreatedInCapture:(unsigned long long)arg1 objectType:(int)arg2 objectID:(unsigned int)arg3;
- (BOOL)isObjectUsedInCapture:(unsigned long long)arg1 objectType:(int)arg2 objectID:(unsigned int)arg3;
- (BOOL)isObjectFullyPreUpdatedInCapture:(unsigned long long)arg1 objectType:(int)arg2 objectID:(unsigned int)arg3;
- (id)drawCallsUsingProgram:(unsigned int)arg1 graphicsEngineID:(unsigned long long)arg2;
- (id)getProgramArrayUsingShader:(unsigned long long)arg1 shaderID:(unsigned int)arg2;
- (id)getStaticObjectIDArray:(unsigned long long)arg1 objectType:(unsigned int)arg2;
- (void)enableStateDeltaGeneratorHeuristics;
- (void)abort;
- (void)disableSingleFrameMode;
- (void)enableSingleFrameMode;
- (void)disableAllHeuristics;
- (void)enableAllHeuristics;
- (void)disableHeuristic:(id)arg1;
- (void)enableHeuristic:(id)arg1;
- (id)enabledHeuristicNames;
- (void)notifyCompletion;
- (void)endAllBlocks;
- (void)processFunctionStream:(id)arg1 blockMode:(int)arg2 findingsHandler:(CDUnknownBlockType)arg3;
- (void)processFunction:(const struct Function *)arg1 blockMode:(int)arg2 findingsHandler:(CDUnknownBlockType)arg3;
- (void)processFunction:(const struct Function *)arg1 blockMode:(int)arg2 analyzeInserted:(BOOL)arg3 findingsHandler:(CDUnknownBlockType)arg4;
- (void)processFunction:(const struct Function *)arg1 blockMode:(int)arg2 streamMode:(BOOL)arg3 analyzeInserted:(BOOL)arg4 findingsHandler:(CDUnknownBlockType)arg5;
- (int)functionIndexForBlockMode:(int)arg1;
- (id)init;
- (id)getHeuristicPool:(unsigned long long)arg1;
- (void)_populateHeuristicPool:(id)arg1;
- (id)getLocalizedString:(id)arg1 table:(id)arg2;
- (id)getLocalizedString:(id)arg1;
- (void)configureForArchive:(id)arg1;
- (unsigned int)_supportedGraphicsAPI;

@end

@interface DYAnalyzerEngineFactory : NSObject
{
    DYDeviceInfo *_deviceInfo;
}

+ (id)newAnalyzerEngineFactoryForGraphicsAPI:(unsigned int)arg1 deviceInfo:(id)arg2;
- (void).cxx_destruct;
- (unsigned int)_supportedGraphicsAPI;
- (id)newAnalyzerEngine;
- (id)initWithDeviceInfo:(id)arg1;

@end

@interface DYAnalyzerFinding : NSObject <NSCopying, NSCoding, NSObject>
{
    NSString *_kind;
    NSString *_generator;
    NSMutableString *_details;
    NSMutableString *_shortDetails;
    NSMutableString *_simplifiedDetails;
    NSString *_links;
    NSMutableIndexSet *_functionIndices;
    NSMutableDictionary *_statistics;
    id <NSCoding><NSCopying><NSObject> _additionalData;
    unsigned int _frameNum;
    unsigned int _drawCallNum;
    unsigned int _classification;
    int _warningLevel;
    int _granularity;
    unsigned long long _graphicsEngineID;
    unsigned long long _resourceGroupID;
    NSArray *_subfindings;
}

+ (id)_findingLevelString:(int)arg1;
@property(retain, nonatomic) NSArray *subfindings; // @synthesize subfindings=_subfindings;
@property(retain, nonatomic) id <NSCoding><NSCopying><NSObject> additionalData; // @synthesize additionalData=_additionalData;
@property(readonly, copy, nonatomic) NSMutableDictionary *statistics; // @synthesize statistics=_statistics;
@property(nonatomic) unsigned int drawCallNum; // @synthesize drawCallNum=_drawCallNum;
@property(nonatomic) unsigned int frameNum; // @synthesize frameNum=_frameNum;
@property(readonly, copy, nonatomic) NSIndexSet *functionIndices; // @synthesize functionIndices=_functionIndices;
@property(nonatomic) int warningLevel; // @synthesize warningLevel=_warningLevel;
@property(copy, nonatomic) NSString *links; // @synthesize links=_links;
@property(copy, nonatomic) NSMutableString *details; // @synthesize details=_details;
@property(retain, nonatomic) NSString *generator; // @synthesize generator=_generator;
@property(nonatomic) int granularity; // @synthesize granularity=_granularity;
@property(nonatomic) unsigned long long resourceGroupID; // @synthesize resourceGroupID=_resourceGroupID;
@property(nonatomic) unsigned long long graphicsEngineID; // @synthesize graphicsEngineID=_graphicsEngineID;
@property(nonatomic) unsigned int classification; // @synthesize classification=_classification;
@property(retain, nonatomic) NSString *kind; // @synthesize kind=_kind;
- (void).cxx_destruct;
- (BOOL)isTextureImageCompletelyUpdated;
- (BOOL)isBufferDataCompletelyUpdated;
- (BOOL)isInefficientStateUpdate;
- (BOOL)isRedundantCallOrQuery;
- (BOOL)isRedundantCall;
- (BOOL)isFrameStatistics;
- (BOOL)isDataRestoreUnnecessaryForFunc:(const struct Function *)arg1 targetArgIndex:(int)arg2 objectType:(unsigned int)arg3 analyzerEngine:(id)arg4;
- (id)debugPrintString;
- (void)addFunctionIndices:(id)arg1;
- (void)addFunctionIndex:(unsigned long long)arg1;
- (void)appendStatistic:(id)arg1 object:(id)arg2;
- (void)appendStatistics:(id)arg1;
- (void)setStatistics:(id)arg1;
- (id)_simplifiedDetailsStringSubstituted:(id)arg1 plural:(BOOL)arg2;
- (id)simplifiedDetailsSubstituted:(BOOL)arg1;
@property(readonly, copy, nonatomic) NSString *simplifiedDetails;
- (void)setSimplifiedDetails:(id)arg1;
@property(copy, nonatomic) NSString *shortDetails;
- (void)loadSimplifiedDetailString:(id)arg1 fromEngine:(id)arg2;
- (void)appendDetailStrings:(id)arg1 fromEngine:(id)arg2;
- (void)appendShortDetails:(id)arg1;
- (void)appendDetails:(id)arg1;
@property(readonly, retain, nonatomic) NSString *localizedKind; // @dynamic localizedKind;
@property(readonly, retain, nonatomic) NSString *synopsis; // @dynamic synopsis;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

@interface DYAnalyzerErrorFinding : DYAnalyzerFinding
{
    unsigned int _functionEnum;
}

@property(nonatomic) unsigned int functionEnum; // @synthesize functionEnum=_functionEnum;
- (BOOL)isTextureImageCompletelyUpdated;
- (BOOL)isBufferDataCompletelyUpdated;
- (BOOL)isInefficientStateUpdate;
- (BOOL)isRedundantCallOrQuery;
- (BOOL)isRedundantCall;
- (BOOL)isFrameStatistics;
- (BOOL)isDataRestoreUnnecessaryForFunc:(const struct Function *)arg1 targetArgIndex:(int)arg2 objectType:(unsigned int)arg3 analyzerEngine:(id)arg4;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFunctionEnum:(unsigned int)arg1;

@end

__attribute__((visibility("hidden")))
@interface DYAnalyzerFindingPool : NSObject
{
    NSMutableArray *_findingsHandlers;
    CDUnknownBlockType handler;
    int _minWarningLevel;
}

@property(nonatomic) int minWarningLevel; // @synthesize minWarningLevel=_minWarningLevel;
@property(copy, nonatomic) CDUnknownBlockType handler; // @synthesize handler;
- (void).cxx_destruct;
- (void)notifyCompletion;
- (void)addFinding:(id)arg1;
- (void)removeFindingsHandler:(id)arg1;
- (id)handleFindingsOnQueue:(struct dispatch_queue_s *)arg1 handler:(CDUnknownBlockType)arg2;
- (id)init;

@end

@interface DYAnalyzerFindingPunchThrough : DYAnalyzerFinding
{
    unsigned int _punchThroughReasons;
    unsigned int _numReasons;
}

@property(readonly, nonatomic) unsigned int numReasons; // @synthesize numReasons=_numReasons;
@property(readonly, nonatomic) unsigned int punchThroughReasons; // @synthesize punchThroughReasons=_punchThroughReasons;
- (BOOL)isTextureImageCompletelyUpdated;
- (BOOL)isBufferDataCompletelyUpdated;
- (BOOL)isInefficientStateUpdate;
- (BOOL)isRedundantCallOrQuery;
- (BOOL)isRedundantCall;
- (BOOL)isFrameStatistics;
- (BOOL)isDataRestoreUnnecessaryForFunc:(const struct Function *)arg1 targetArgIndex:(int)arg2 objectType:(unsigned int)arg3 analyzerEngine:(id)arg4;
- (id)_determineSeparatorByNumReasonsAdded:(unsigned int)arg1;
- (id)_apiSpecificReasonString:(int)arg1;
- (id)reasonsString;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithPunchThroughReasons:(unsigned int)arg1;
- (void)_initCommon;
- (id)description;

@end

@interface DYAnalyzerHeuristic : NSObject
{
    int _functionIndex;
    int _captureBlockMode;
    unsigned int _stateMirrorRetCode;
    BOOL _isPostMirrorHeuristic;
    BOOL _isPreSortHeuristic;
    DYAnalyzerFindingPool *_weakFindingPool;
    DYAnalyzerHeuristicPool *_weakHeuristicPool;
    DYAnalyzerEngine *_weakEngine;
}

+ (id)heuristicBundlesForAPI:(unsigned int)arg1;
+ (Class)heuristicForIdentifier:(id)arg1 forAPI:(unsigned int)arg2;
+ (id)availableHeuristicNamesForAPI:(unsigned int)arg1;
+ (void)_registerHeuristicsForAPI:(unsigned int)arg1;
+ (BOOL)_registerHeuristic:(Class)arg1 forAPI:(unsigned int)arg2;
+ (BOOL)supportsAPI:(unsigned int)arg1;
+ (id)identifier;
@property(nonatomic) __weak DYAnalyzerEngine *weakEngine; // @synthesize weakEngine=_weakEngine;
@property(nonatomic) __weak DYAnalyzerHeuristicPool *weakHeuristicPool; // @synthesize weakHeuristicPool=_weakHeuristicPool;
@property(nonatomic) __weak DYAnalyzerFindingPool *weakFindingPool; // @synthesize weakFindingPool=_weakFindingPool;
@property(readonly, nonatomic) BOOL isPreSortHeuristic; // @synthesize isPreSortHeuristic=_isPreSortHeuristic;
@property(readonly, nonatomic) BOOL isPostMirrorHeuristic; // @synthesize isPostMirrorHeuristic=_isPostMirrorHeuristic;
- (void).cxx_destruct;
@property(readonly, nonatomic) DYAnalyzerHeuristicPool *heuristicPool;
@property(readonly, nonatomic) DYAnalyzerEngine *engine;
@property(readonly, nonatomic) DYAnalyzerFindingPool *findingPool;
- (id)loadURLData:(const char *)arg1;
- (void)notifyCompletion;
- (void)setFunctionIndex:(int)arg1;
- (void)addLinks:(id)arg1 fromKey:(id)arg2;
- (void)addFunctionDerivedDetails:(id)arg1;
- (id)findingWithKind:(id)arg1 warningLevel:(int)arg2 classification:(unsigned int)arg3 detailsKey:(id)arg4 linksKey:(id)arg5 triggerIndex:(int)arg6;
- (id)errorFindingFromFunction:(const struct Function *)arg1;
- (id)finding;
- (void)_setGenerationEnvironmentForFinding:(id)arg1;
- (void)endBlock:(int)arg1;
- (void)startBlock:(int)arg1;
- (void)processFunction:(const struct Function *)arg1 stateMirrorRetCode:(unsigned int)arg2;
- (BOOL)shouldBeRunOnPlatform:(int)arg1;
- (id)description;
- (id)initWithIsPostMirrorHeuristic:(BOOL)arg1 isPreSortHeuristic:(BOOL)arg2;
- (id)initWithIsPostMirrorHeuristic:(BOOL)arg1;
- (id)init;

@end

@interface DYAnalyzerHeuristicPool : NSObject
{
    int _captureBlockMode;
    BOOL _bInsideCaptureBlock;
    int _functionIndex;
    unsigned int _stateMirrorRetCode;
    DYAnalyzerEngine *_engine;
    NSMutableArray *_heuristicPool;
    DYAnalyzerFinding *_perFrameFindingStats;
    unsigned long long _graphicsEngineID;
}

@property(readonly, nonatomic) unsigned long long graphicsEngineID; // @synthesize graphicsEngineID=_graphicsEngineID;
@property(nonatomic) unsigned int stateMirrorRetCode; // @synthesize stateMirrorRetCode=_stateMirrorRetCode;
@property(readonly, nonatomic) int functionIndex; // @synthesize functionIndex=_functionIndex;
@property(readonly, retain, nonatomic) DYAnalyzerFinding *perFrameFindingStats; // @synthesize perFrameFindingStats=_perFrameFindingStats;
@property(readonly, retain, nonatomic) NSMutableArray *heuristicPool; // @synthesize heuristicPool=_heuristicPool;
@property(readonly, nonatomic) __weak DYAnalyzerEngine *engine; // @synthesize engine=_engine;
- (void).cxx_destruct;
- (void)notifyCompletion;
- (void)endBlock;
- (void)startBlock:(int)arg1;
- (void)processPostMirrorHeuristics:(const struct Function *)arg1 captureBlockMode:(int)arg2 functionIndex:(int)arg3;
- (void)processPreMirrorHeuristics:(const struct Function *)arg1 captureBlockMode:(int)arg2 functionIndex:(int)arg3;
- (void)addHeuristic:(id)arg1;
- (id)initWithEngine:(id)arg1 graphicsEngineID:(unsigned long long)arg2;

@end

@interface DYAnalyzerSubfinding : NSObject
{
    int _funcIndex;
    NSString *_text;
}

@property(readonly, nonatomic) int funcIndex; // @synthesize funcIndex=_funcIndex;
@property(readonly, nonatomic) NSString *text; // @synthesize text=_text;
- (void).cxx_destruct;
- (id)initWithText:(id)arg1 andFunctionIndex:(int)arg2;

@end

@interface DYAnalyzerTestUtil : NSObject
{
}

+ (BOOL)_diffAndTestFindingsFile:(id)arg1 withTraceFile:(id)arg2 refName:(id)arg3;
+ (void)_printFindings:(id)arg1 toFile:(id)arg2;
+ (id)_openFile:(id)arg1 create:(BOOL)arg2;
+ (BOOL)_compareReferenceFindings:(id)arg1 refName:(id)arg2;
+ (BOOL)_generateReferenceFindings:(id)arg1 refName:(id)arg2;
+ (BOOL)testFindings:(id)arg1 refName:(id)arg2;
+ (id)findingsOfKind:(id)arg1 kind:(id)arg2;
+ (void)debugPrintFormattedFindingsOfKind:(id)arg1 kind:(id)arg2;
+ (void)debugPrintFormattedFindings:(id)arg1;
+ (BOOL)findingKindIsAbsent:(id)arg1 inFindings:(id)arg2;
+ (BOOL)findingKindIsPresent:(id)arg1 inFindings:(id)arg2;
+ (id)analyzeArchive:(id)arg1;

@end

@interface DYArchiveTester : NSObject
{
}

+ (void)debugOutputArchiveTrace:(id)arg1 toPath:(id)arg2 withFunctionTracer:(id)arg3;
+ (BOOL)_diffAndTestTraceFile:(id)arg1 withTraceFile:(id)arg2 refArchiveName:(id)arg3;
+ (BOOL)_compareReferenceArchive:(id)arg1 refArchiveName:(id)arg2 withFunctionTracer:(id)arg3;
+ (BOOL)_generateReferenceArchive:(id)arg1 refArchiveName:(id)arg2 withFunctionTracer:(id)arg3;
+ (BOOL)testArchive:(id)arg1 refArchiveName:(id)arg2 withFunctionTracer:(id)arg3;
+ (id)openArchive:(id)arg1 suffix:(id)arg2 bundle:(id)arg3;
+ (id)openArchive:(id)arg1 bundle:(id)arg2;

@end

@interface DYBCEncoder : DYEncoder
{
}

+ (void)initialize;
- (id)decode:(id)arg1 format:(unsigned int)arg2 level:(unsigned int)arg3 width:(unsigned int)arg4 height:(unsigned int)arg5 options:(id)arg6;
- (id)encode:(id)arg1 level:(unsigned int)arg2 width:(unsigned int)arg3 height:(unsigned int)arg4 options:(id)arg5 errorCode:(int *)arg6;
- (id)describeOptions:(id)arg1;
- (id)options;
- (id)name;

@end

@interface DYGuestAppLaunchStrategy : NSObject
{
    DYGuestAppSession *_session;
    int _pid;
}

+ (double)launchTimeout;
@property(readonly, nonatomic) int pid; // @synthesize pid=_pid;
- (void).cxx_destruct;
- (void)registerInferiorPid:(int)arg1;
- (id)performLaunch:(id)arg1 connectFuture:(id)arg2;
- (id)initWithSession:(id)arg1;
- (id)init;

@end

@interface DYBaseLocalLaunchStrategy : DYGuestAppLaunchStrategy
{
}

+ (id)interposingDylibPath;
- (id)performLaunch:(id)arg1 connectFuture:(id)arg2;
- (void)registerInferiorPid:(int)arg1;
- (id)initWithSession:(id)arg1;

@end

@interface DYCaptureArchiveModifier : DYInOrderInstructionFilesVisitor
{
    DYCaptureArchive *_archive;
    DYCaptureArchive *_archiveOriginal;
    NSString *_fileSuffix;
    NSMutableArray *_functionStreamModifiers;
    NSMutableSet *_processedFilesSet;
    int _functionIndex;
    BOOL _copyDataFiles;
    struct vector<GPUTools::FD::Function, std::__1::allocator<GPUTools::FD::Function>> _functions;
    struct vector<GPUTools::FD::Function, std::__1::allocator<GPUTools::FD::Function>> _afterFunctions;
    struct vector<GPUTools::FD::Function, std::__1::allocator<GPUTools::FD::Function>> _endFunctions;
    BOOL _analyzeMode;
    BOOL _analyzePass;
    BOOL _replaceFuncStreamFiles;
    DYFunctionStreamModifier *_currentModifier;
    struct Function *_currentFunction;
    DYCaptureFile *_currentFile;
    NSError *_error;
}

+ (BOOL)applyModifiersToArchive:(id)arg1 modifiers:(id)arg2;
+ (id)createTemporaryModifiedArchive:(id)arg1 modifiers:(id)arg2 copyDataFiles:(BOOL)arg3;
@property(readonly, nonatomic) NSError *error; // @synthesize error=_error;
@property(readonly, nonatomic) DYCaptureFile *currentFile; // @synthesize currentFile=_currentFile;
@property(readonly, nonatomic) struct Function *currentFunction; // @synthesize currentFunction=_currentFunction;
@property(readonly, nonatomic) NSMutableArray *functionStreamModifiers; // @synthesize functionStreamModifiers=_functionStreamModifiers;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)_processFunction:(const struct Function *)arg1 functionIndex:(int)arg2;
- (void)_restoreAPIState;
- (void)_saveAPIState;
- (void)_duplicateDataFiles:(id)arg1;
- (id)copyDataForFilename:(id)arg1 error:(id *)arg2;
- (id)addDataFileWithPrefix:(id)arg1 bytes:(const void *)arg2 size:(unsigned long long)arg3;
- (void)_incrementFunctionIndex:(struct Function *)arg1;
- (id)_writeFunctionsToStreamWithFilename:(id)arg1;
- (void)visitInternalFile:(id)arg1;
- (void)visitDataFile:(id)arg1;
- (void)_duplicateCaptureFile:(id)arg1;
- (id)_modifyFunctionStream:(id)arg1 modifier:(id)arg2 filename:(id)arg3;
- (void)visitFunctionStreamFile:(id)arg1;
- (void)_processPass:(id)arg1;
- (void)visitCaptureArchive:(id)arg1;
- (void)insertFunction:(struct Function)arg1 position:(int)arg2;
- (id)initWithArchive:(id)arg1 fileSuffix:(id)arg2 copyDataFiles:(BOOL)arg3;
- (id)init;

@end

@interface DYCaptureArchiveTracer : DYInOrderInstructionFilesVisitor
{
    DYCaptureArchive *_captureArchive;
    DYFunctionTracer *_functionTracer;
    NSError *_error;
}

@property(readonly, retain, nonatomic) NSError *error; // @synthesize error=_error;
- (void).cxx_destruct;
- (void)newTraceString:(id)arg1;
- (void)visitFunctionStreamFile:(id)arg1;
- (id)performTrace;
- (id)initWithCaptureArchive:(id)arg1 withFunctionTracer:(id)arg2;

@end

@interface DYCaptureArchiveTraceToFile : DYCaptureArchiveTracer
{
    NSFileHandle *_fileHandle;
}

- (void).cxx_destruct;
- (void)newTraceString:(id)arg1;
- (void)closeFile;
- (id)initWithCaptureArchive:(id)arg1 withFilePath:(id)arg2 withFunctionTracer:(id)arg3;

@end

@interface DYCaptureSession : NSObject
{
    DYGuestAppSession *_session;
    DYCaptureArchive *_archive;
    struct dispatch_queue_s *_queue;
    NSMutableDictionary *_finalConfigurationDictionary;
    DYTransportSource *_source;
    DYContinuation *_invalidationCompletion;
    DYFuture *_iconFuture;
    NSMutableDictionary *_buffers;
    NSError *_error;
    NSMapTable *_observersMap;
    struct _NSRange _frameRange;
    CDStruct_faeedbfb _stats;
    int _state;
    unsigned int _serial;
    BOOL _automaticallyDeleteArchiveOnFailure;
    int _storeSymbolicatorSignature;
    BOOL _triggerOnNextGraphicsCommand;
    BOOL _lockGraphicsAfterCompletion;
    BOOL _harvestStateAtEnd;
    BOOL _suspendAfterCompletion;
    BOOL _complete;
    BOOL _clientDidSendAllData;
    BOOL _deviceSupportsSessionSerial;
}

+ (void)initialize;
+ (BOOL)accessInstanceVariablesDirectly;
+ (BOOL)automaticallyNotifiesObserversForKey:(id)arg1;
@property(nonatomic) BOOL complete; // @synthesize complete=_complete;
@property(nonatomic) int storeSymbolicatorSignature; // @synthesize storeSymbolicatorSignature=_storeSymbolicatorSignature;
@property(nonatomic) BOOL suspendAfterCompletion; // @synthesize suspendAfterCompletion=_suspendAfterCompletion;
@property(nonatomic) BOOL harvestStateAtEnd; // @synthesize harvestStateAtEnd=_harvestStateAtEnd;
@property(nonatomic) BOOL lockGraphicsAfterCompletion; // @synthesize lockGraphicsAfterCompletion=_lockGraphicsAfterCompletion;
@property(nonatomic) BOOL triggerOnNextGraphicsCommand; // @synthesize triggerOnNextGraphicsCommand=_triggerOnNextGraphicsCommand;
@property(nonatomic) struct _NSRange frameRange; // @synthesize frameRange=_frameRange;
@property(readonly, retain, nonatomic) NSError *error; // @synthesize error=_error;
@property(nonatomic) BOOL automaticallyDeleteArchiveOnFailure; // @synthesize automaticallyDeleteArchiveOnFailure=_automaticallyDeleteArchiveOnFailure;
@property(readonly, retain, nonatomic) DYCaptureArchive *archive; // @synthesize archive=_archive;
- (void).cxx_destruct;
- (void)_replaceArchive:(id)arg1;
- (void)_postProcessArchive;
- (void)_saveAPISpecificData:(id)arg1;
- (void)_setupFinalConfigurationDictionary:(id)arg1;
- (void)_receivedAllClientData:(id)arg1;
- (void)_flushBuffers;
- (BOOL)stopCapturing;
- (BOOL)startCapturing;
- (BOOL)_activateWithSession:(id)arg1 serial:(unsigned int)arg2 invalidationCompletion:(id)arg3;
- (id)_allowedSessionInfoBaseClasses;
- (BOOL)_sendActivationMessage;
- (void)invalidate;
- (void)_invalidate:(id)arg1;
- (void)removeObserver:(id)arg1;
- (id)notifyOnQueue:(struct dispatch_queue_s *)arg1 handler:(CDUnknownBlockType)arg2;
- (void)_postStateChange:(int)arg1;
- (void)copyStatistics:(CDStruct_faeedbfb *)arg1;
@property(nonatomic) BOOL invalid; // @dynamic invalid;
@property(readonly, nonatomic) BOOL active; // @dynamic active;
- (void)_setState:(int)arg1;
@property(nonatomic) int state; // @dynamic state;
@property(nonatomic) unsigned long long frameLimit; // @dynamic frameLimit;
@property(nonatomic) unsigned long long triggerFrame; // @dynamic triggerFrame;
- (void)setTargetQueue:(struct dispatch_queue_s *)arg1;
- (void)dealloc;
- (id)initWithCaptureArchive:(id)arg1;
- (id)init;

@end

__attribute__((visibility("hidden")))
@interface DYDeferredLocalLaunchStrategy : DYBaseLocalLaunchStrategy
{
}

- (id)performLaunch:(id)arg1 connectFuture:(id)arg2;

@end

@interface DYDepthEncoder : DYEncoder
{
}

+ (void)initialize;
- (id)decode:(id)arg1 format:(unsigned int)arg2 level:(unsigned int)arg3 width:(unsigned int)arg4 height:(unsigned int)arg5 options:(id)arg6;
- (id)encode:(id)arg1 level:(unsigned int)arg2 width:(unsigned int)arg3 height:(unsigned int)arg4 options:(id)arg5 errorCode:(int *)arg6;
- (id)describeOptions:(id)arg1;
- (id)options;
- (id)name;

@end

@interface DYDevice : NSObject
{
    DYDeviceInfo *_deviceInfo;
}

+ (id)replayerAppIdentifier;
+ (Class)controlStrategyClass;
+ (Class)deferredLaunchStrategyClass;
+ (Class)launchStrategyClass;
@property(readonly, retain, nonatomic) DYDeviceInfo *deviceInfo; // @synthesize deviceInfo=_deviceInfo;
- (void).cxx_destruct;
- (BOOL)supportsPlaybackOfCaptureWithInfo:(id)arg1 limitBackwardsCompatibility:(BOOL)arg2 isInternal:(BOOL)arg3;
- (BOOL)versionIsOlderThan:(id)arg1;
- (id)iconDataForApplicationIdentifiers:(id)arg1;
- (id)createTransport;
@property(readonly, retain, nonatomic) NSString *standardTitle; // @dynamic standardTitle;
@property(readonly, retain, nonatomic) NSArray *supportedGraphicsAPIInfos; // @dynamic supportedGraphicsAPIInfos;
@property(readonly, nonatomic) CDStruct_fc1d2ed0 mainScreenDescriptor; // @dynamic mainScreenDescriptor;
@property(readonly, retain, nonatomic) DYGPUToolsVersionInfo *gputoolsVersionInfo; // @dynamic gputoolsVersionInfo;
@property(readonly, nonatomic) NSError *gputoolsServiceAvailabilityError; // @dynamic gputoolsServiceAvailabilityError;
@property(readonly, nonatomic) BOOL gputoolsServiceAvailable; // @dynamic gputoolsServiceAvailable;
@property(readonly, nonatomic) unsigned int nativePointerSize;
@property(readonly, retain, nonatomic) NSString *productType; // @dynamic productType;
@property(readonly, retain, nonatomic) NSString *build; // @dynamic build;
@property(readonly, retain, nonatomic) NSString *version; // @dynamic version;
@property(readonly, retain, nonatomic) NSString *name; // @dynamic name;
@property(readonly, nonatomic) BOOL sharedPermanentIdentifier; // @dynamic sharedPermanentIdentifier;
@property(readonly, retain, nonatomic) NSString *permanentIdentifier; // @dynamic permanentIdentifier;
@property(readonly, nonatomic) unsigned long long runtimeIdentifier; // @dynamic runtimeIdentifier;
@property(readonly, nonatomic) int platform; // @dynamic platform;
- (id)init;

@end

@interface DYDeviceRepository : NSObject
{
    struct unordered_map<unsigned long long, DYDevice *, std::__1::hash<unsigned long long>, std::__1::equal_to<unsigned long long>, std::__1::allocator<std::__1::pair<const unsigned long long, DYDevice *>>> _deviceMap;
    int _lock;
}

+ (id)sharedDeviceRepository;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)registerDevice:(id)arg1;
- (id)deviceMatchingDeviceInfo:(id)arg1;
- (id)allDevices;
- (id)_allDevicesInner;
- (id)init;

@end

@interface DYETCEncoder : DYEncoder
{
}

- (id)decode:(id)arg1 format:(unsigned int)arg2 level:(unsigned int)arg3 width:(unsigned int)arg4 height:(unsigned int)arg5 options:(id)arg6;
- (id)encode:(id)arg1 level:(unsigned int)arg2 width:(unsigned int)arg3 height:(unsigned int)arg4 options:(id)arg5 errorCode:(int *)arg6;
- (id)describeOptions:(id)arg1;
- (id)options;
- (id)name;

@end

@interface DYFunctionStreamModifier : NSObject
{
    CDUnknownBlockType _block;
}

- (void).cxx_destruct;
- (void)analyzeFunctionInArchiveModifier:(id)arg1;
- (BOOL)shouldAnalyze;
- (void)onBeginFileInArchiveModifier:(id)arg1;
- (BOOL)processFunctionInArchiveModifier:(id)arg1;
- (id)initWithBlock:(CDUnknownBlockType)arg1;

@end

@interface DYGuestApp : NSObject <NSCoding, NSCopying>
{
    unsigned long long _kind;
    NSMutableArray *_argumentEntries;
    NSMutableArray *_environmentEntries;
    NSMutableArray *_mutableEnvironmentEntries;
    NSString *_title;
    _Bool _useDeferredLaunch;
    BOOL _applyShellTokenizationToArguments;
    NSURL *_url;
    NSURL *_trueBinary;
    NSURL *_hostURL;
    NSDictionary *_infoPlist;
    NSString *_bundleIdentifier;
    NSString *_currentWorkingDirectory;
    unsigned long long _launchArchitecture;
}

+ (id)keyPathsForValuesAffectingUrl;
+ (id)keyPathsForValuesAffectingPath;
+ (void)initialize;
@property(nonatomic) BOOL applyShellTokenizationToArguments; // @synthesize applyShellTokenizationToArguments=_applyShellTokenizationToArguments;
@property(readonly, nonatomic) NSMutableArray *mutableEnvironmentEntries; // @synthesize mutableEnvironmentEntries=_mutableEnvironmentEntries;
@property(nonatomic) _Bool useDeferredLaunch; // @synthesize useDeferredLaunch=_useDeferredLaunch;
@property(nonatomic) unsigned long long launchArchitecture; // @synthesize launchArchitecture=_launchArchitecture;
@property(copy, nonatomic) NSString *currentWorkingDirectory; // @synthesize currentWorkingDirectory=_currentWorkingDirectory;
@property(copy, nonatomic) NSString *bundleIdentifier; // @synthesize bundleIdentifier=_bundleIdentifier;
@property(copy, nonatomic) NSDictionary *infoPlist; // @synthesize infoPlist=_infoPlist;
@property(retain, nonatomic) NSURL *hostURL; // @synthesize hostURL=_hostURL;
@property(retain, nonatomic) NSURL *trueBinary; // @synthesize trueBinary=_trueBinary;
@property(retain, nonatomic) NSURL *url; // @synthesize url=_url;
@property(readonly, nonatomic) unsigned long long kind; // @synthesize kind=_kind;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSDictionary *environment; // @dynamic environment;
@property(readonly, nonatomic) NSArray *arguments; // @dynamic arguments;
- (id)_applyShellProcessingOnArgumentValue:(id)arg1;
- (BOOL)isArchitectureAvailable:(unsigned long long)arg1;
@property(copy, nonatomic) NSString *title; // @dynamic title;
@property(copy, nonatomic) NSString *path; // @dynamic path;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)_initNoAlloc;
- (id)init;

// Remaining properties
@property(copy, nonatomic) NSArray *argumentEntries; // @dynamic argumentEntries;
@property(copy, nonatomic) NSArray *environmentEntries; // @dynamic environmentEntries;
@property(readonly, nonatomic) NSMutableArray *mutableArgumentEntries; // @dynamic mutableArgumentEntries;

@end

@interface DYGuestAppArgument : NSObject <NSCoding, NSCopying>
{
    BOOL _enabled;
    NSString *_stringValue;
}

+ (id)argumentWithValue:(id)arg1 enabled:(BOOL)arg2;
@property(nonatomic) BOOL enabled; // @synthesize enabled=_enabled;
@property(copy, nonatomic) NSString *stringValue; // @synthesize stringValue=_stringValue;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

@interface DYGuestAppControlStrategy : NSObject
{
    DYGuestAppSession *_session;
}

+ (Class)symbolicatorClass;
- (void).cxx_destruct;
- (void)bringToForeground;
- (void)sendToBackground;
- (void)terminate;
- (void)resume;
- (void)createSymbolicator:(id)arg1;
- (id)initWithSession:(id)arg1;
- (id)init;

@end

@interface DYGuestAppEnvironment : NSObject <NSCoding, NSCopying>
{
    BOOL _enabled;
    NSString *_key;
    NSString *_stringValue;
}

+ (id)environmentWithKey:(id)arg1 value:(id)arg2 enabled:(BOOL)arg3;
@property(nonatomic) BOOL enabled; // @synthesize enabled=_enabled;
@property(copy, nonatomic) NSString *stringValue; // @synthesize stringValue=_stringValue;
@property(copy, nonatomic) NSString *key; // @synthesize key=_key;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

@interface DYGuestAppSession : NSObject
{
    struct dispatch_queue_s *_queue;
    unsigned int _transactionBits;
    BOOL _attemptedLaunch;
    unsigned int _graphicsAPI;
    struct dispatch_queue_s *_masterQueue;
    struct dispatch_semaphore_s *_transactionSema;
    NSMutableArray *_launchEnvironmentMutators;
    NSMutableArray *_finalLaunchDictionaryMutators;
    DYTransportSource *_source;
    DYSymbolicator *_symbolicator;
    DYFuture *_symbolicatorFuture;
    NSMapTable *_observersMap;
    NSMapTable *_traceHandlersMap;
    NSMutableDictionary *_fbufStreamHeaders;
    struct dispatch_queue_s *_traceHandlingQueue;
    NSMutableDictionary *_overridesConfiguration;
    DYCaptureSession *_activeCaptureSession;
    unsigned int _captureSessionSerial;
    NSMutableArray *_displayLinkInfo;
    struct dy_timebase _appTimebase;
    BOOL _didTerminate;
    BOOL _interposeSemaphoreSignalSent;
    BOOL _disableAllInterposing;
    BOOL _disableLaunchTimeout;
    BOOL _remainSuspendedAfterLaunch;
    BOOL _running;
    BOOL _invalid;
    BOOL _includeBacktracesInTrace;
    BOOL _includeDriverEventsInTrace;
    int _traceMode;
    DYGuestApp *_guestApp;
    DYDevice *_device;
    DYTransport *_transport;
    NSDictionary *_finalLaunchDictionary;
    NSError *_error;
    DYBreakpoint *_currentBreakpoint;
    DYResourceStreamer *_resourceStreamer;
    unsigned long long _profilingSendPeriod;
    unsigned long long _profilingFlags;
    NSDictionary *_hardwareCountersConfiguration;
    DYGuestAppLaunchStrategy *_launchStrategy;
    DYGuestAppControlStrategy *_controlStrategy;
}

+ (void)initialize;
@property(readonly, nonatomic) DYGuestAppControlStrategy *controlStrategy; // @synthesize controlStrategy=_controlStrategy;
@property(readonly, nonatomic) DYGuestAppLaunchStrategy *launchStrategy; // @synthesize launchStrategy=_launchStrategy;
@property(retain, nonatomic) NSDictionary *hardwareCountersConfiguration; // @synthesize hardwareCountersConfiguration=_hardwareCountersConfiguration;
@property(nonatomic) unsigned long long profilingFlags; // @synthesize profilingFlags=_profilingFlags;
@property(nonatomic) unsigned long long profilingSendPeriod; // @synthesize profilingSendPeriod=_profilingSendPeriod;
@property(nonatomic) BOOL includeDriverEventsInTrace; // @synthesize includeDriverEventsInTrace=_includeDriverEventsInTrace;
@property(nonatomic) BOOL includeBacktracesInTrace; // @synthesize includeBacktracesInTrace=_includeBacktracesInTrace;
@property(nonatomic) int traceMode; // @synthesize traceMode=_traceMode;
@property(readonly, retain, nonatomic) DYResourceStreamer *resourceStreamer; // @synthesize resourceStreamer=_resourceStreamer;
@property(retain, nonatomic) DYBreakpoint *currentBreakpoint; // @synthesize currentBreakpoint=_currentBreakpoint;
@property(readonly, nonatomic) unsigned int graphicsAPI; // @synthesize graphicsAPI=_graphicsAPI;
@property(readonly, retain, nonatomic) NSError *error; // @synthesize error=_error;
@property(readonly, nonatomic) BOOL invalid; // @synthesize invalid=_invalid;
@property(readonly, nonatomic) BOOL running; // @synthesize running=_running;
@property(readonly, retain, nonatomic) NSDictionary *finalLaunchDictionary; // @synthesize finalLaunchDictionary=_finalLaunchDictionary;
@property(nonatomic) BOOL remainSuspendedAfterLaunch; // @synthesize remainSuspendedAfterLaunch=_remainSuspendedAfterLaunch;
@property(nonatomic) BOOL disableLaunchTimeout; // @synthesize disableLaunchTimeout=_disableLaunchTimeout;
@property(nonatomic) BOOL disableAllInterposing; // @synthesize disableAllInterposing=_disableAllInterposing;
@property(readonly, retain, nonatomic) DYTransport *transport; // @synthesize transport=_transport;
@property(readonly, retain, nonatomic) DYDevice *device; // @synthesize device=_device;
@property(readonly, retain, nonatomic) DYGuestApp *guestApp; // @synthesize guestApp=_guestApp;
- (void).cxx_destruct;
- (id)newCaptureSessionWithArchive:(id)arg1;
- (void)setValue:(id)arg1 forOverride:(id)arg2;
@property(readonly, nonatomic) struct dy_timebase appTimebase; // @dynamic appTimebase;
@property(readonly, nonatomic) int currentBreakpointType; // @dynamic currentBreakpointType;
- (void)_sendAllConfigurations;
- (void)_sendOverridesConfiguration;
- (void)_sendTraceConfiguration;
- (void)_sendAdditionalConfigurations;
- (void)_modifyTraceConfigurationDictionary:(id)arg1;
- (void)_handleFstreamData:(id)arg1;
- (void)_handleGuestAppTermination:(id)arg1;
- (void)_handleTransportMessage:(id)arg1;
- (id)updateResources:(id)arg1;
- (id)queryForGraphicsAPIUsage;
- (id)getDisplayLinkInfo;
- (id)activateCaptureSession:(id)arg1;
- (id)prepareSymbolicator;
- (void)removeObserver:(id)arg1;
- (id)notifyOnQueue:(struct dispatch_queue_s *)arg1 handler:(CDUnknownBlockType)arg2;
- (void)_postEvent:(int)arg1 info:(id)arg2;
- (void)removeTraceHandler:(id)arg1;
- (id)handleTraceOnQueue:(struct dispatch_queue_s *)arg1 handler:(CDUnknownBlockType)arg2;
- (void)dispatchInTransaction:(CDUnknownBlockType)arg1;
- (BOOL)_isDirectTransactionAllowed;
- (void)drainQueue;
- (void)invalidate;
- (void)_invalidate:(id)arg1;
- (void)bringToForeground;
- (void)sendToBackground;
- (void)unlockGraphics;
- (void)lockGraphics;
- (void)terminate;
- (void)resume;
@property(readonly, retain, nonatomic) NSDictionary *finalLaunchEnvironment; // @dynamic finalLaunchEnvironment;
- (void)dispatchOnceRunning:(struct dispatch_queue_s *)arg1 block:(CDUnknownBlockType)arg2;
- (id)launch;
- (id)launchDebugServerWithEnvironment:(id)arg1 andLaunchPath:(id)arg2 andPort:(id)arg3;
- (void)_applyBuiltinEnvironmentMutation:(id)arg1;
- (id)_makeLaunchDictionary;
- (void)registerFinalLaunchDictionaryMutator:(CDUnknownBlockType)arg1;
- (void)registerLaunchEnvironmentMutator:(CDUnknownBlockType)arg1;
- (struct dispatch_queue_s *)createQueueTargettingPrimaryQueue;
- (struct dispatch_queue_s *)createQueueTargettingMasterQueue;
- (void)setTargetQueue:(struct dispatch_queue_s *)arg1;
- (void)dealloc;
- (id)_initWithGuestApp:(id)arg1 transport:(id)arg2 device:(id)arg3 launchStrategyClass:(Class)arg4 controlStrategyClass:(Class)arg5;
- (id)initWithGuestApp:(id)arg1 device:(id)arg2 deferLaunch:(BOOL)arg3;
- (id)init;

@end

__attribute__((visibility("hidden")))
@interface DYImageFormatInfo : NSObject
{
    unsigned int _internalFormat;
    unsigned int _format;
    unsigned int _type;
}

@property(nonatomic) unsigned int type; // @synthesize type=_type;
@property(nonatomic) unsigned int format; // @synthesize format=_format;
@property(nonatomic) unsigned int internalFormat; // @synthesize internalFormat=_internalFormat;
- (id)initWithInternalFormat:(unsigned int)arg1 format:(unsigned int)arg2 andType:(unsigned int)arg3;

@end

__attribute__((visibility("hidden")))
@interface DYImageInfo : NSObject
{
    int _width;
    int _height;
    int _depth;
    int _compressed;
    int _numSamples;
    DYImageFormatInfo *_clientFormatInfo;
    DYImageFormatInfo *_engineFormatInfo;
}

@property(nonatomic) int numSamples; // @synthesize numSamples=_numSamples;
@property(nonatomic) int compressed; // @synthesize compressed=_compressed;
@property(nonatomic) int depth; // @synthesize depth=_depth;
@property(nonatomic) int height; // @synthesize height=_height;
@property(nonatomic) int width; // @synthesize width=_width;
@property(retain, nonatomic) DYImageFormatInfo *engineFormatInfo; // @synthesize engineFormatInfo=_engineFormatInfo;
@property(retain, nonatomic) DYImageFormatInfo *clientFormatInfo; // @synthesize clientFormatInfo=_clientFormatInfo;
- (void).cxx_destruct;
- (id)initWithClientFormatInfo:(id)arg1 engineFormatInfo:(id)arg2 width:(int)arg3 height:(int)arg4 depth:(int)arg5 compressed:(int)arg6 numSamples:(int)arg7;

@end

@interface DYInvestigatorCase : NSObject <NSCoding, NSCopying>
{
    struct dispatch_queue_s *_observersMapQueue;
    NSMapTable *_observersMap;
    BOOL _invalid;
    int _invalidReason;
    int _dataAvailable;
    unsigned int _investigationProgress;
    int _investigatorResult;
    DYInvestigatorCaseConfigData *_configData;
    DYDeviceInfo *_playbackDeviceInfo;
    NSMutableArray *_redFlagAnalyzerFindings;
    NSMutableArray *_investigatorFindings;
    NSMutableArray *_additionalFindings;
    NSString *_timestamp;
}

@property(retain, nonatomic) NSString *timestamp; // @synthesize timestamp=_timestamp;
@property(readonly, nonatomic) NSMutableArray *additionalFindings; // @synthesize additionalFindings=_additionalFindings;
@property(readonly, nonatomic) NSMutableArray *investigatorFindings; // @synthesize investigatorFindings=_investigatorFindings;
@property(readonly, nonatomic) NSMutableArray *redFlagAnalyzerFindings; // @synthesize redFlagAnalyzerFindings=_redFlagAnalyzerFindings;
@property(nonatomic) int investigatorResult; // @synthesize investigatorResult=_investigatorResult;
@property(nonatomic) unsigned int investigationProgress; // @synthesize investigationProgress=_investigationProgress;
@property(readonly, nonatomic) int dataAvailable; // @synthesize dataAvailable=_dataAvailable;
@property(nonatomic) int invalidReason; // @synthesize invalidReason=_invalidReason;
@property(nonatomic) BOOL invalid; // @synthesize invalid=_invalid;
@property(readonly, nonatomic) DYDeviceInfo *playbackDeviceInfo; // @synthesize playbackDeviceInfo=_playbackDeviceInfo;
@property(retain, nonatomic) DYInvestigatorCaseConfigData *configData; // @synthesize configData=_configData;
- (void).cxx_destruct;
- (void)invalidateWithReason:(int)arg1;
- (id)investigatorResultBody;
- (id)investigatorResultString;
- (void)notifyDataAvailable:(int)arg1;
- (void)postEvent:(int)arg1;
- (void)removeObserver:(id)arg1;
- (id)observeEventsOnQueue:(struct dispatch_queue_s *)arg1 handler:(CDUnknownBlockType)arg2;
- (id)description;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithConfigData:(id)arg1 withPlaybackDeviceInfo:(id)arg2;
- (void)_initCommon;

@end

@interface DYInvestigatorCaseConfigData : NSObject <NSCopying, NSCoding>
{
    NSMutableArray *_overviewSamples;
    NSMutableDictionary *_reportData;
    DYOverviewMeasurementsPerSample *_overviewSamplePrev;
    NSMutableArray *_frameRateOverTimeArray;
    NSMutableDictionary *_reportDataNew;
    int _reportLock;
    unsigned long long _overviewSampleCount;
    unsigned long long _overviewSamplePeriod;
    unsigned long long _overviewDuration;
    BOOL _overviewSamplesAreReady;
    NSString *_appName;
    NSArray *_appArguments;
    DYDeviceInfo *_captureDeviceInfo;
    NSMutableArray *_displayLinks;
    NSArray *_analyzerFindings;
    NSNumber *_originalCaptureFrameTime;
    DYInvestigatorStatistics *_overviewFrameTime;
    DYInvestigatorStatistics *_overviewCAWaitTime;
}

@property(readonly, nonatomic) NSDictionary *reportData; // @synthesize reportData=_reportData;
@property(retain, nonatomic) DYInvestigatorStatistics *overviewCAWaitTime; // @synthesize overviewCAWaitTime=_overviewCAWaitTime;
@property(retain, nonatomic) DYInvestigatorStatistics *overviewFrameTime; // @synthesize overviewFrameTime=_overviewFrameTime;
@property(retain, nonatomic) NSNumber *originalCaptureFrameTime; // @synthesize originalCaptureFrameTime=_originalCaptureFrameTime;
@property(nonatomic) BOOL overviewSamplesAreReady; // @synthesize overviewSamplesAreReady=_overviewSamplesAreReady;
@property(retain, nonatomic) NSArray *analyzerFindings; // @synthesize analyzerFindings=_analyzerFindings;
@property(retain, nonatomic) NSMutableArray *displayLinks; // @synthesize displayLinks=_displayLinks;
@property(readonly, nonatomic) NSArray *overviewSamples; // @synthesize overviewSamples=_overviewSamples;
@property(retain, nonatomic) DYDeviceInfo *captureDeviceInfo; // @synthesize captureDeviceInfo=_captureDeviceInfo;
@property(retain, nonatomic) NSArray *appArguments; // @synthesize appArguments=_appArguments;
@property(retain, nonatomic) NSString *appName; // @synthesize appName=_appName;
- (void).cxx_destruct;
- (void)reportDataClearProjections;
- (void)reportDataClear;
- (void)reportDataCommit;
- (void)reportDataRemoveObjectForKey:(id)arg1;
- (void)reportDataSetObject:(id)arg1 forKey:(id)arg2;
- (void)debugPrintFormatted;
- (id)totalFrameRateArray;
- (void)addDisplayLinks:(id)arg1;
- (void)addOverviewSamples:(id)arg1;
- (void)_addOverviewSample:(id)arg1;
- (void)addTraceProfileData:(id)arg1;
- (id)_createSample:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithCaptureDeviceInfo:(id)arg1 appName:(id)arg2 appArguments:(id)arg3 analyzerFindings:(id)arg4;
- (id)init;

@end

@interface DYInvestigatorConfig : NSObject <NSCopying, NSCoding>
{
    DYDeviceInfo *_deviceInfo;
    unsigned long long _overviewSamplePeriod;
    unsigned long long _overviewSampleCount;
    unsigned long long _overviewDuration;
}

@property(readonly, nonatomic) unsigned long long overviewDuration; // @synthesize overviewDuration=_overviewDuration;
@property(readonly, nonatomic) unsigned long long overviewSampleCount; // @synthesize overviewSampleCount=_overviewSampleCount;
@property(readonly, nonatomic) unsigned long long overviewSamplePeriod; // @synthesize overviewSamplePeriod=_overviewSamplePeriod;
@property(readonly, nonatomic) DYDeviceInfo *deviceInfo; // @synthesize deviceInfo=_deviceInfo;
- (void).cxx_destruct;
@property(readonly, nonatomic) unsigned long long profilingFlags; // @dynamic profilingFlags;
@property(readonly, nonatomic) int traceMode; // @dynamic traceMode;
@property(readonly, nonatomic) BOOL isLegacyDevice; // @dynamic isLegacyDevice;
- (void)_setOverviewDuration:(unsigned long long)arg1 SamplePeriod:(unsigned long long)arg2;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithDeviceInfo:(id)arg1;
- (id)init;

@end

@interface DYInvestigatorDisplayLink : NSObject <NSCopying>
{
    BOOL _running;
    unsigned int _identifier;
    unsigned int _interval;
    unsigned long long _timeStamp;
}

@property(readonly, nonatomic) unsigned long long timeStamp; // @synthesize timeStamp=_timeStamp;
@property(nonatomic) unsigned int interval; // @synthesize interval=_interval;
@property(nonatomic) BOOL running; // @synthesize running=_running;
@property(nonatomic) unsigned int identifier; // @synthesize identifier=_identifier;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithIdentifier:(unsigned int)arg1 withRunning:(BOOL)arg2 withInterval:(unsigned int)arg3;
- (id)init;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;

@end

@interface DYInvestigatorFinding : NSObject
{
}

@end

@interface DYInvestigatorFindingWarning : DYInvestigatorFinding
{
}

@end

@interface DYInvestigatorRecommendation : NSObject <NSCopying, NSCoding>
{
    NSMutableDictionary *_sectionsDict;
    DYInvestigatorRecommendationSection *_currentSection;
    DYInvestigatorRecommendationInfo *_summary;
}

@property(retain, nonatomic) DYInvestigatorRecommendationInfo *summary; // @synthesize summary=_summary;
- (void).cxx_destruct;
- (void)printFormatted;
- (void)addAdditionalSectionItem:(id)arg1;
- (void)addSpecificSectionItem:(id)arg1;
- (void)addGeneralSectionItem:(id)arg1;
@property(readonly, nonatomic) DYInvestigatorRecommendationSection *additionalSection; // @dynamic additionalSection;
@property(readonly, nonatomic) DYInvestigatorRecommendationSection *specificSection; // @dynamic specificSection;
@property(readonly, nonatomic) DYInvestigatorRecommendationSection *generalSection; // @dynamic generalSection;
- (void)setOrdered:(BOOL)arg1;
- (void)setPreamble:(id)arg1;
- (void)selectSection:(id)arg1;
- (void)setSummaryWithString:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;
- (id)description;

@end

@interface DYInvestigatorRecommendationInfo : NSObject <NSCopying, NSCoding>
{
    NSAttributedString *_text;
}

@property(readonly, nonatomic) NSAttributedString *text; // @synthesize text=_text;
- (void).cxx_destruct;
- (void)debugPrintFormatted;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithString:(id)arg1;
- (id)initWithAttributedString:(id)arg1;
- (id)init;
- (id)description;

@end

@interface DYInvestigatorRecommendationItem : NSObject <NSCoding, NSCopying>
{
}

- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;

@end

@interface DYInvestigatorRecommendationItemList : DYInvestigatorRecommendationItem
{
    NSMutableArray *value;
}

@property(retain, nonatomic) NSArray *value; // @synthesize value;
- (void).cxx_destruct;
- (void)addString:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (id)initWithArray:(id)arg1;
- (id)init;

@end

@interface DYInvestigatorRecommendationItemBulletedList : DYInvestigatorRecommendationItemList
{
}

- (id)description;

@end

@interface DYInvestigatorRecommendationItemNumberedList : DYInvestigatorRecommendationItemList
{
}

- (id)description;

@end

@interface DYInvestigatorRecommendationItemText : DYInvestigatorRecommendationItem
{
    NSAttributedString *value;
}

@property(retain, nonatomic) NSAttributedString *value; // @synthesize value;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (id)initWithString:(id)arg1;
- (id)initWithAttributedString:(id)arg1;

@end

@interface DYInvestigatorRecommendationSection : NSObject <NSCopying, NSCoding>
{
    BOOL _ordered;
    NSAttributedString *_preamble;
    NSMutableArray *_items;
}

@property(retain, nonatomic) NSMutableArray *items; // @synthesize items=_items;
@property(nonatomic) BOOL ordered; // @synthesize ordered=_ordered;
@property(retain, nonatomic) NSAttributedString *preamble; // @synthesize preamble=_preamble;
- (void).cxx_destruct;
- (void)printFormatted;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;
- (id)description;

@end

@interface DYInvestigatorSharedConfigManager : NSObject
{
    struct dispatch_queue_s *_queue;
    NSMapTable *_deviceInfoToInvestigatorConfig;
}

+ (id)sharedManager;
- (void).cxx_destruct;
- (void)investigatorConfigRemove:(id)arg1;
- (id)investigatorConfigForDeviceInfo:(id)arg1;
- (void)dealloc;
- (id)init;

@end

@interface DYInvestigatorStatistics : NSObject <NSCoding, NSCopying>
{
    unsigned long long _minimum;
    unsigned long long _firstQuartile;
    unsigned long long _median;
    unsigned long long _thirdQuartile;
    unsigned long long _maximum;
    unsigned long long _mean;
    unsigned long long _sumValueQ1toQ3;
    unsigned long long _sumWeightQ1toQ3;
    unsigned long long _meanQ1toQ3;
}

+ (id)statisticsFromArray:(id)arg1 getter:(CDUnknownBlockType)arg2;
@property(nonatomic) unsigned long long meanQ1toQ3; // @synthesize meanQ1toQ3=_meanQ1toQ3;
@property(nonatomic) unsigned long long sumWeightQ1toQ3; // @synthesize sumWeightQ1toQ3=_sumWeightQ1toQ3;
@property(nonatomic) unsigned long long sumValueQ1toQ3; // @synthesize sumValueQ1toQ3=_sumValueQ1toQ3;
@property(nonatomic) unsigned long long mean; // @synthesize mean=_mean;
@property(nonatomic) unsigned long long maximum; // @synthesize maximum=_maximum;
@property(nonatomic) unsigned long long thirdQuartile; // @synthesize thirdQuartile=_thirdQuartile;
@property(nonatomic) unsigned long long median; // @synthesize median=_median;
@property(nonatomic) unsigned long long firstQuartile; // @synthesize firstQuartile=_firstQuartile;
@property(nonatomic) unsigned long long minimum; // @synthesize minimum=_minimum;
- (void)offsetDataWithOffset:(unsigned long long)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;

@end

@interface DYLocalApp : DYGuestApp
{
    NSArray *_archs;
    NSData *_bookmarkData;
    BOOL _exists;
}

+ (id)keyPathsForValuesAffectingExists;
@property(readonly, nonatomic) BOOL exists; // @synthesize exists=_exists;
- (void).cxx_destruct;
- (BOOL)isArchitectureAvailable:(unsigned long long)arg1;
- (void)setPath:(id)arg1;
- (void)setUrl:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithURL:(id)arg1;
- (id)init;

@end

@interface DYLocalControlStrategy : DYGuestAppControlStrategy
{
}

- (void)terminate;
- (void)resume;

@end

@interface DYLocalHostDevice : DYDevice
{
}

+ (Class)controlStrategyClass;
+ (Class)deferredLaunchStrategyClass;
+ (Class)launchStrategyClass;
+ (id)sharedLocalHostDevice;
- (id)createTransport;
- (id)iconDataForApplicationIdentifiers:(id)arg1;
- (id)guestAppWithURL:(id)arg1;
- (id)gputoolsServiceAvailabilityError;
- (BOOL)gputoolsServiceAvailable;
- (id)_init;
- (id)init;

@end

__attribute__((visibility("hidden")))
@interface DYLocalLaunchStrategy : DYBaseLocalLaunchStrategy
{
}

- (id)urlForBundleIdentifier:(id)arg1;
- (int)launchURL:(id)arg1 launchDictionary:(id)arg2 error:(id *)arg3;
- (id)performLaunch:(id)arg1 connectFuture:(id)arg2;

@end

__attribute__((visibility("hidden")))
@interface DYNSTaskLaunchStrategy : DYLocalLaunchStrategy
{
    NSTask *_task;
}

- (void).cxx_destruct;
- (int)launchURL:(id)arg1 launchDictionary:(id)arg2 error:(id *)arg3;

@end

__attribute__((visibility("hidden")))
@interface DYNSWorkspaceLaunchStrategy : DYLocalLaunchStrategy
{
}

- (id)urlForBundleIdentifier:(id)arg1;
- (int)launchURL:(id)arg1 launchDictionary:(id)arg2 error:(id *)arg3;

@end

@interface DYOverviewMeasurementsPerSample : NSObject <NSCoding, NSCopying>
{
    unsigned long long _timestamp;
    unsigned long long _framesDuration;
    unsigned long long _cpuTime;
    unsigned long long _cpuIdleTime;
    unsigned int _frameIndex;
    unsigned int _numFrames;
    unsigned long long _inGLTime;
    unsigned long long _totalPlatformTime;
    unsigned long long _inVertexProcessTime;
    unsigned long long _inStateChangeTime;
    unsigned long long _inTextureUploadTime;
    unsigned long long _caWaitTime;
    unsigned int _tilerUtilizationPercent;
    unsigned int _rendererUtilizationPercent;
    unsigned int _deviceUtilizationPercent;
    unsigned int _performanceBits;
    unsigned int _sampleIndex;
    unsigned long long _graphicsCommandNum;
    NSDictionary *_drawCommandStatistics;
}

+ (id)frameDurationStatistics:(id)arg1;
+ (double)averageFPS:(id)arg1;
@property(readonly, nonatomic) NSDictionary *drawCommandStatistics; // @synthesize drawCommandStatistics=_drawCommandStatistics;
@property(nonatomic) unsigned long long graphicsCommandNum; // @synthesize graphicsCommandNum=_graphicsCommandNum;
@property(nonatomic) unsigned long long caWaitTime; // @synthesize caWaitTime=_caWaitTime;
@property(nonatomic) unsigned int performanceBits; // @synthesize performanceBits=_performanceBits;
@property(nonatomic) unsigned int deviceUtilizationPercent; // @synthesize deviceUtilizationPercent=_deviceUtilizationPercent;
@property(nonatomic) unsigned int rendererUtilizationPercent; // @synthesize rendererUtilizationPercent=_rendererUtilizationPercent;
@property(nonatomic) unsigned int tilerUtilizationPercent; // @synthesize tilerUtilizationPercent=_tilerUtilizationPercent;
@property(nonatomic) unsigned long long inTextureUploadTime; // @synthesize inTextureUploadTime=_inTextureUploadTime;
@property(nonatomic) unsigned long long inStateChangeTime; // @synthesize inStateChangeTime=_inStateChangeTime;
@property(nonatomic) unsigned long long inVertexProcessTime; // @synthesize inVertexProcessTime=_inVertexProcessTime;
@property(nonatomic) unsigned long long totalPlatformTime; // @synthesize totalPlatformTime=_totalPlatformTime;
@property(nonatomic) unsigned long long inGLTime; // @synthesize inGLTime=_inGLTime;
@property(nonatomic) unsigned int numFrames; // @synthesize numFrames=_numFrames;
@property(nonatomic) unsigned int frameIndex; // @synthesize frameIndex=_frameIndex;
@property(nonatomic) unsigned long long cpuIdleTime; // @synthesize cpuIdleTime=_cpuIdleTime;
@property(nonatomic) unsigned long long cpuTime; // @synthesize cpuTime=_cpuTime;
@property(nonatomic) unsigned long long framesDuration; // @synthesize framesDuration=_framesDuration;
@property(nonatomic) unsigned long long timestamp; // @synthesize timestamp=_timestamp;
@property(nonatomic) unsigned int sampleIndex; // @synthesize sampleIndex=_sampleIndex;
- (void).cxx_destruct;
@property(readonly, nonatomic) BOOL waitOnGPU;
- (void)log;
- (id)initWithDictionary:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;

@end

@interface DYPVRTCEncoder : DYEncoder
{
    int m_alpha_option;
    int m_punchthrough_option;
    int m_channel_weighting;
}

- (id)decode:(id)arg1 format:(unsigned int)arg2 level:(unsigned int)arg3 width:(unsigned int)arg4 height:(unsigned int)arg5 options:(id)arg6;
- (id)encode:(id)arg1 level:(unsigned int)arg2 width:(unsigned int)arg3 height:(unsigned int)arg4 options:(id)arg5 errorCode:(int *)arg6;
- (void)parseOptions:(id)arg1;
- (id)describeOptions:(id)arg1;
- (void)setDelegate:(id)arg1;
- (id)options;
- (id)name;

@end

@interface DYPalettedEncoder : DYEncoder
{
}

- (id)_convertTexels4Bit:(id)arg1 width:(unsigned int)arg2 height:(unsigned int)arg3 palette:(id)arg4;
- (id)_convertTexels8Bit:(id)arg1 width:(unsigned int)arg2 height:(unsigned int)arg3 palette:(id)arg4;
- (id)_convertPaletteRGBA8:(id)arg1 numEntries:(unsigned int)arg2;
- (id)_convertPaletteRGB8:(id)arg1 numEntries:(unsigned int)arg2;
- (id)_convertPaletteRGB5A1:(id)arg1 numEntries:(unsigned int)arg2;
- (id)_convertPaletteRGBA4:(id)arg1 numEntries:(unsigned int)arg2;
- (id)_convertPaletteRGB565:(id)arg1 numEntries:(unsigned int)arg2;
- (id)decode:(id)arg1 format:(unsigned int)arg2 level:(unsigned int)arg3 width:(unsigned int)arg4 height:(unsigned int)arg5 options:(id)arg6;
- (id)encode:(id)arg1 level:(unsigned int)arg2 width:(unsigned int)arg3 height:(unsigned int)arg4 options:(id)arg5 errorCode:(int *)arg6;

@end

@interface DYPixelFormatConverter : NSObject
{
}

+ (unsigned int)getGenericFormatForGLFormat:(unsigned int)arg1 type:(unsigned int)arg2 format:(unsigned int)arg3;
+ (void)getGLFormatForGenericFormat:(unsigned int)arg1 glInternalFormatOut:(unsigned int *)arg2 glFormatOut:(unsigned int *)arg3 glTypeOut:(unsigned int *)arg4;
+ (void)_initDictionaries;
+ (void)initialize;

@end

@interface DYResourceManagerHelper : NSObject
{
    id <DYCaptureStore> _captureStore;
    DYResourceStreamer *_resourceStreamer;
    NSCache *_captureStoreCache;
    NSCache *_deviceCache;
    NSCache *_textureBackingStoresCache;
    NSMutableSet *_updatedResourcesSet;
    struct dispatch_queue_s *_resourceQueue;
    struct dispatch_queue_s *_deviceQueue;
    int _captureStoreSpinLock;
}

+ (id)_keyForResource:(id)arg1 sharegroup:(unsigned long long)arg2 funcIndex:(unsigned int)arg3;
- (void).cxx_destruct;
- (BOOL)hasResourceStreamer;
- (id)updateResource:(id)arg1 sharegroup:(unsigned long long)arg2;
- (BOOL)hasResourceBeenUpdated:(unsigned long long)arg1 resourceType:(unsigned int)arg2 container:(unsigned long long)arg3;
- (void)invalidateDeviceResource:(id)arg1 sharegroup:(unsigned long long)arg2 functionIndex:(unsigned int)arg3;
- (void)invalidateDeviceCache;
- (id)loadDeviceResource:(id)arg1 sharegroup:(unsigned long long)arg2 functionIndex:(unsigned int)arg3;
- (id)loadTextureImageBackingStore:(id)arg1 creationClass:(Class)arg2;
- (id)loadCaptureStoreData:(id)arg1;
- (void)dealloc;
- (id)initWithCaptureStore:(id)arg1 resourceStreamer:(id)arg2;

@end

@interface DYResourceStreamer : NSObject
{
    DYTransport *_transport;
    struct dispatch_queue_s *_outputQueue;
    struct dispatch_queue_s *_replyQueue;
}

+ (id)processRealizeResourceMessages:(id)arg1 resourceObject:(id)arg2 tempDict:(id)arg3;
+ (id)_createResource:(id)arg1 funcStreamData:(id)arg2 objectCache:(id)arg3;
+ (id)findDataForURL:(const char *)arg1 inCache:(id)arg2;
- (void).cxx_destruct;
- (id)updateResource:(id)arg1;
- (id)realizeResource:(id)arg1 functionIndex:(unsigned int)arg2;
- (void)dealloc;
- (id)initWithTransport:(id)arg1;
- (id)init;

@end

@interface DYStackFrame : NSObject <NSCopying>
{
    BOOL _faulted;
    DYSymbolicator *_symbolicator;
    unsigned long long _address;
    unsigned long long _index;
    struct _CSTypeRef _owner;
    struct _CSTypeRef _symbol;
    struct _CSTypeRef _sourceInfo;
}

@property(nonatomic) struct _CSTypeRef sourceInfo; // @synthesize sourceInfo=_sourceInfo;
@property(nonatomic) struct _CSTypeRef symbol; // @synthesize symbol=_symbol;
@property(nonatomic) struct _CSTypeRef owner; // @synthesize owner=_owner;
@property(nonatomic) unsigned long long index; // @synthesize index=_index;
@property(nonatomic) unsigned long long address; // @synthesize address=_address;
@property(retain, nonatomic) DYSymbolicator *symbolicator; // @synthesize symbolicator=_symbolicator;
- (void).cxx_destruct;
- (id)shortFormat;
- (id)fullFormat;
@property(readonly, nonatomic) NSString *ownerName; // @dynamic ownerName;
- (void)_fault;
- (void)_reset;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

@interface DYSymbolicator : NSObject
{
    NSArray *_rootPaths;
    BOOL _removeTopGPUTools;
    CDUnknownBlockType _ownerFilter;
    CDUnknownBlockType _stackFrameAllocator;
    struct _CSTypeRef _coreSymbolicator;
}

+ (id)dysmURLForUUIDBytes:(const CDStruct_bd2f613f *)arg1 roots:(id)arg2;
@property(copy, nonatomic) CDUnknownBlockType stackFrameAllocator; // @synthesize stackFrameAllocator=_stackFrameAllocator;
@property(copy, nonatomic) CDUnknownBlockType ownerFilter; // @synthesize ownerFilter=_ownerFilter;
@property(nonatomic) BOOL removeTopGPUTools; // @synthesize removeTopGPUTools=_removeTopGPUTools;
@property(readonly, nonatomic) struct _CSTypeRef coreSymbolicator; // @synthesize coreSymbolicator=_coreSymbolicator;
- (void).cxx_destruct;
- (void)enumerateStackFrames:(id)arg1 usingBlock:(CDUnknownBlockType)arg2;
- (void)enumerateStackFrames:(unsigned long long *)arg1 count:(unsigned long long)arg2 usingBlock:(CDUnknownBlockType)arg3;
- (id)_createStackFrame;
- (void)dealloc;
- (id)initWithSignature:(id)arg1 rootPaths:(id)arg2 device:(id)arg3 error:(id *)arg4;
- (id)initWithCoreSymbolicator:(struct _CSTypeRef)arg1 rootPaths:(id)arg2 device:(id)arg3;
- (id)init;
- (void)_fixSymbolOwnerPaths;

@end

__attribute__((visibility("hidden")))
@interface _EntryGLToGeneric : NSObject
{
    unsigned int _type;
    unsigned int _genericEnum;
}

+ (id)addToArray:(id)arg1 glType:(unsigned int)arg2 genericEnum:(unsigned int)arg3;
@property(readonly, nonatomic) unsigned int genericEnum; // @synthesize genericEnum=_genericEnum;
@property(readonly, nonatomic) unsigned int type; // @synthesize type=_type;
- (id)initWithType:(unsigned int)arg1 andGenericEnum:(unsigned int)arg2;

@end

__attribute__((visibility("hidden")))
@interface _EntryGenericToGL : NSObject
{
    unsigned int _internalFormat;
    unsigned int _format;
    unsigned int _type;
}

@property(readonly, nonatomic) unsigned int type; // @synthesize type=_type;
@property(readonly, nonatomic) unsigned int format; // @synthesize format=_format;
@property(readonly, nonatomic) unsigned int internalFormat; // @synthesize internalFormat=_internalFormat;
- (id)initWithInternalFormat:(unsigned int)arg1 andFormat:(unsigned int)arg2 andType:(unsigned int)arg3;

@end

