//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#pragma mark -

//
// File: /Applications/Xcode-7GM.app/Contents/SharedFrameworks/kperfdataDT.framework/Versions/A/kperfdataDT
// UUID: 6007D8DE-C6A5-3F06-99F8-4F5AFEB98740
//
//                           Arch: x86_64
//                Current version: 1.0.0
//          Compatibility version: 1.0.0
//                 Source version: 63.0.0.0.0
//       Minimum Mac OS X version: 10.10.0
//                    SDK version: 10.11.0
//

//
// This file does not contain any Objective-C runtime information.
//
