//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#pragma mark Blocks

typedef void (^CDUnknownBlockType)(void); // return type and parameters are unknown

#pragma mark -

//
// File: /Applications/Xcode-7GM.app/Contents/PlugIns/IDEiOSSupportCore.ideplugin/Contents/MacOS/IDEiOSSupportCore
// UUID: 490888B8-72C6-3042-863D-2902F583DA74
//
//                           Arch: x86_64
//                Current version: 0.0.0
//          Compatibility version: 0.0.0
//                 Source version: 8167.0.0.0.0
//       Minimum Mac OS X version: 10.10.0
//                    SDK version: 10.11.0
//
// Objective-C Garbage Collection: Unsupported
//
//                       Run path: @loader_path/../../../
//                               = /Applications/Xcode-7GM.app/Contents/PlugIns
//                       Run path: @loader_path/../../../../Frameworks
//                               = /Applications/Xcode-7GM.app/Contents/Frameworks
//                       Run path: @loader_path/../../../../SharedFrameworks
//                               = /Applications/Xcode-7GM.app/Contents/SharedFrameworks
//                       Run path: @loader_path/../../../../Developer/Library/PrivateFrameworks
//                               = /Applications/Xcode-7GM.app/Contents/Developer/Library/PrivateFrameworks
//                       Run path: @loader_path/../../../../Developer/Platforms/iPhoneSimulator.platform/Developer/Library/PrivateFrameworks
//                               = /Applications/Xcode-7GM.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/PrivateFrameworks
//                       Run path: @loader_path/../../../../Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks
//                               = /Applications/Xcode-7GM.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks
//                       Run path: @loader_path/../../../../Applications/Instruments.app/Contents/Frameworks
//                               = /Applications/Xcode-7GM.app/Contents/Applications/Instruments.app/Contents/Frameworks
//

@protocol DTMISProcessControlServiceAuthorizedAPI <DTXAllowedRPC>
- (void)pidDiedCallback:(NSNumber *)arg1;
@end

@protocol DTXAllowedRPC <NSObject>
@end

@protocol DVTBasicDevice <DVTCodesignableDevice>
@property(readonly) _Bool deviceIsBusy;
@property(readonly) NSError *unavailabilityError;
@property(readonly, getter=isAvailable) BOOL available;
@property(readonly) BOOL isProxiedDevice;
@property(readonly, copy) NSString *nativeArchitecture;
@property(readonly) DVTPlatform *platform;
@property(readonly, copy, nonatomic) NSString *operatingSystemVersionWithBuildNumber;
@property(readonly, copy) NSString *operatingSystemBuild;
@property(readonly, copy) NSString *operatingSystemVersion;
@property(readonly, copy) NSString *processorDescription;
@property(readonly, copy, nonatomic) NSString *modelUTI;
@property(readonly, copy, nonatomic) NSString *modelCode;
@property(readonly, copy, nonatomic) NSString *modelName;

@optional
- (DTXConnection *)primaryInstrumentsServer;
@end

@protocol DVTBasiciOSDevice <DVTBasicDevice>
- (NSArray *)supportedDeviceFamilies;
- (BOOL)deviceSupportsBuildable:(id <IDEBuildable>)arg1 buildParameters:(IDEBuildParameters *)arg2 error:(id *)arg3;
@end

@protocol DVTCodesignableDevice <NSObject>
@property(readonly, copy) NSSet *proxiedDevices;
@property(readonly) BOOL supportsProvisioning;
@property(readonly, copy) NSString *platformIdentifier;
@property(readonly, copy) NSString *identifier;
@property(readonly, copy) NSString *nameForDeveloperPortal;
@property(readonly, copy) NSString *name;
@end

@protocol DVTDeviceApplicationInstaller <DVTDeviceApplicationProvider>
- (BOOL)uploadApplicationDataWithPath:(NSString *)arg1 forInstalledApplicationWithBundleIdentifier:(NSString *)arg2 error:(id *)arg3;
- (BOOL)downloadApplicationDataToPath:(NSString *)arg1 forInstalledApplicationWithBundleIdentifier:(NSString *)arg2 error:(id *)arg3;
- (NSError *)uninstallApplicationWithBundleIdentifierSync:(NSString *)arg1;
@end

@protocol DVTDeviceApplicationProvider <NSObject>
@property(readonly) NSSet *applications;

@optional
@property(readonly) NSSet *systemApplications;
@end

@protocol DVTInvalidation <NSObject>
- (void)primitiveInvalidate;

@optional
+ (BOOL)supportsInvalidationPrevention;
+ (unsigned long long)assertionBehaviorForKeyValueObservationsAtEndOfEvent;
+ (unsigned long long)assertionBehaviorAfterEndOfEventForSelector:(SEL)arg1;
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly, nonatomic, getter=isValid) BOOL valid;
- (void)invalidate;
@end

@protocol DVTSDKPropertiesProvider <NSObject>
+ (DVTMacroDefinitionTable *)additionalDefaultPropertiesForSDK:(DVTSDK *)arg1;
@end

@protocol IDEArchivePackagerIdentityToken <NSObject>
- (DVTCodesignParameterSnapshot *)codesignParameterSnapshotIncludingProfile:(BOOL)arg1;
- (id <IDEArchivePackagerIdentityToken>)relatedTokenForKey:(NSString *)arg1;
- (int)status;
- (NSString *)displayName;
@end

@protocol IDEBuildable <DVTInvalidation, NSObject>
@property(readonly, copy) NSString *legacyIdentifier;
@property(readonly) NSString *productModuleName;
@property(readonly) NSSet *namesOfLinkedBinaries;
@property(readonly) NSString *toolTip;
@property(readonly) NSString *displayName;
@property(readonly) id <IDEBlueprint> blueprint;
@property(readonly, copy) IDEEntityIdentifier *entityIdentifier;
@property(readonly, copy) NSString *buildableIdentifier;
@property(readonly, copy) NSString *productTypeIdentifier;
- (IDEBuilder *)createBuilderForBuildCommand:(int)arg1 withBuildTaskQueueSet:(IDEBuildOperationQueueSet *)arg2 parameters:(IDEBuildParameters *)arg3 buildOnlyTheseFiles:(NSArray *)arg4 restorePersistedBuildResults:(BOOL)arg5 withManager:(id <IDEBuildableOperationManager>)arg6;
- (NSArray *)implicitDependenciesForBuildParameters:(IDEBuildParameters *)arg1 executionEnvironment:(IDEExecutionEnvironment *)arg2 returningMessages:(id *)arg3;
- (NSArray *)directDependencies;
- (NSArray *)orderedRecursiveDependenciesIncludingSelf:(BOOL)arg1;
- (DVTSearchPath *)toolSearchPathWithBuildParameters:(IDEBuildParameters *)arg1;
- (NSString *)absolutePathByEvaluatingBuildSettingExpressionString:(NSString *)arg1 withBuildParameters:(IDEBuildParameters *)arg2;
- (NSString *)stringByEvaluatingBuildSettingExpressionString:(NSString *)arg1 withBuildParameters:(IDEBuildParameters *)arg2;
- (NSArray *)evaluatedStringListValueForBuildSetting:(NSString *)arg1 withBuildParameters:(IDEBuildParameters *)arg2;
- (NSString *)evaluatedStringValueForBuildSetting:(NSString *)arg1 withBuildParameters:(IDEBuildParameters *)arg2;
- (NSArray *)allBuildSettingNamesWithBuildParameters:(IDEBuildParameters *)arg1;
- (IDEProductType *)productTypeWithBuildParameters:(IDEBuildParameters *)arg1;

@optional
- (Class)buildOperationManagerClass;
@end

@protocol IDEBuildableProduct <IDEBuildable>
@property(readonly) BOOL productIsExecutable;
@property(readonly) NSDictionary *productSettings;
@property(readonly) NSString *iconPath;
@property(readonly, copy) DVTFileDataType *fileDataType;
@property(readonly) DVTFilePath *filePath;
- (DVTFilePath *)filePathForBuildParameters:(IDEBuildParameters *)arg1;
- (NSString *)productTypeIdentifier;
@end

@protocol IDEPortalEntitlementsCoordinatorPlatform <NSObject>
- (NSDictionary *)willRequestProfileWithFeatures:(NSDictionary *)arg1 usingWildcardAppID:(BOOL)arg2;
- (NSDictionary *)didReadProfileFeatures:(NSDictionary *)arg1;
- (id)initWithCapabilitiesContext:(id <IDECapabilitiesContextProviding>)arg1;
@end

@protocol IDERunDestinationFallbackSelectorDeviceInfo <NSObject>
@property(readonly, nonatomic) NSString *ide_fallbackSelectorDeviceGroupingFamily;
@end

@protocol IDERunOperationWorkerChaining
@end

@protocol NSFileManagerDelegate <NSObject>

@optional
- (BOOL)fileManager:(NSFileManager *)arg1 shouldProceedAfterError:(NSError *)arg2 removingItemAtURL:(NSURL *)arg3;
- (BOOL)fileManager:(NSFileManager *)arg1 shouldProceedAfterError:(NSError *)arg2 removingItemAtPath:(NSString *)arg3;
- (BOOL)fileManager:(NSFileManager *)arg1 shouldRemoveItemAtURL:(NSURL *)arg2;
- (BOOL)fileManager:(NSFileManager *)arg1 shouldRemoveItemAtPath:(NSString *)arg2;
- (BOOL)fileManager:(NSFileManager *)arg1 shouldProceedAfterError:(NSError *)arg2 linkingItemAtURL:(NSURL *)arg3 toURL:(NSURL *)arg4;
- (BOOL)fileManager:(NSFileManager *)arg1 shouldProceedAfterError:(NSError *)arg2 linkingItemAtPath:(NSString *)arg3 toPath:(NSString *)arg4;
- (BOOL)fileManager:(NSFileManager *)arg1 shouldLinkItemAtURL:(NSURL *)arg2 toURL:(NSURL *)arg3;
- (BOOL)fileManager:(NSFileManager *)arg1 shouldLinkItemAtPath:(NSString *)arg2 toPath:(NSString *)arg3;
- (BOOL)fileManager:(NSFileManager *)arg1 shouldProceedAfterError:(NSError *)arg2 movingItemAtURL:(NSURL *)arg3 toURL:(NSURL *)arg4;
- (BOOL)fileManager:(NSFileManager *)arg1 shouldProceedAfterError:(NSError *)arg2 movingItemAtPath:(NSString *)arg3 toPath:(NSString *)arg4;
- (BOOL)fileManager:(NSFileManager *)arg1 shouldMoveItemAtURL:(NSURL *)arg2 toURL:(NSURL *)arg3;
- (BOOL)fileManager:(NSFileManager *)arg1 shouldMoveItemAtPath:(NSString *)arg2 toPath:(NSString *)arg3;
- (BOOL)fileManager:(NSFileManager *)arg1 shouldProceedAfterError:(NSError *)arg2 copyingItemAtURL:(NSURL *)arg3 toURL:(NSURL *)arg4;
- (BOOL)fileManager:(NSFileManager *)arg1 shouldProceedAfterError:(NSError *)arg2 copyingItemAtPath:(NSString *)arg3 toPath:(NSString *)arg4;
- (BOOL)fileManager:(NSFileManager *)arg1 shouldCopyItemAtURL:(NSURL *)arg2 toURL:(NSURL *)arg3;
- (BOOL)fileManager:(NSFileManager *)arg1 shouldCopyItemAtPath:(NSString *)arg2 toPath:(NSString *)arg3;
@end

@protocol NSObject
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;
@property(readonly) unsigned long long hash;
- (struct _NSZone *)zone;
- (unsigned long long)retainCount;
- (id)autorelease;
- (oneway void)release;
- (id)retain;
- (BOOL)respondsToSelector:(SEL)arg1;
- (BOOL)conformsToProtocol:(Protocol *)arg1;
- (BOOL)isMemberOfClass:(Class)arg1;
- (BOOL)isKindOfClass:(Class)arg1;
- (BOOL)isProxy;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2 withObject:(id)arg3;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2;
- (id)performSelector:(SEL)arg1;
- (id)self;
- (Class)class;
- (BOOL)isEqual:(id)arg1;

@optional
@property(readonly, copy) NSString *debugDescription;
@end

@protocol XCDTMobileIS_XPCDebuggingProcotol <DTXAllowedRPC>
- (void)outputReceived:(NSString *)arg1 fromProcess:(int)arg2 atTime:(unsigned long long)arg3;
- (void)xpcServiceObserved:(NSString *)arg1 withProcessIdentifier:(int)arg2 requestedByProcess:(int)arg3 options:(NSDictionary *)arg4;
@end

@protocol __ARCLiteIndexedSubscripting__
- (void)setObject:(id)arg1 atIndexedSubscript:(unsigned long long)arg2;
- (id)objectAtIndexedSubscript:(unsigned long long)arg1;
@end

@protocol __ARCLiteKeyedSubscripting__
- (void)setObject:(id)arg1 forKeyedSubscript:(id)arg2;
- (id)objectForKeyedSubscript:(id)arg1;
@end

@interface DTDKApplication (IDEiPhoneOrganizerApplications)
- (id)DVT_nameAndVersion;
@end

@interface DVTAbstractiOSDevice : DVTDevice <DVTBasiciOSDevice>
{
    NSMapTable *_workspaceInstallsInProgress;
}

+ (id)nameForDeviceFamilyObject:(id)arg1;
- (void).cxx_destruct;
- (void)showTodayViewForExtensions:(id)arg1 pid:(int)arg2;
- (id)serviceHubProcessControlChannel;
- (id)iconImage;
- (id)deviceClassForDisplay;
- (BOOL)supportsBuildingThinnedResources;
- (void)uninstallProvisioningProfile:(id)arg1;
- (void)installProvisioningProfiles:(id)arg1;
- (BOOL)canInstallProfile:(id)arg1;
- (id)provisioningProfiles;
@property(readonly) _Bool deviceIsBusy;
- (id)taskForDeviceCommand:(id)arg1 withArguments:(id)arg2 error:(id *)arg3;
- (void)installActivityDidEndInWorkspace:(id)arg1 withError:(id)arg2;
- (void)installActivityInWorkspace:(id)arg1 operationInProgress:(id)arg2 details:(id)arg3;
- (void)installActivityWillBeginInWorkspace:(id)arg1 withProductName:(id)arg2;
- (void)setInstallProgress:(long long)arg1 path:(id)arg2;
- (void)setInstallProgress:(long long)arg1 text:(id)arg2;
- (long long)updateInstalledApplicationsWithResult:(id *)arg1;
- (long long)copyLocalPath:(id)arg1 toLocalPath:(id)arg2 sync:(BOOL)arg3 errorStringPtr:(id *)arg4;
- (long long)copyDevicePath:(id)arg1 toLocalPath:(id)arg2 sync:(BOOL)arg3 errorStringPtr:(id *)arg4;
- (long long)copyLocalPath:(id)arg1 toDevicePath:(id)arg2 sync:(BOOL)arg3 errorStringPtr:(id *)arg4;
- (long long)copyDevicePath:(id)arg1 toDevicePath:(id)arg2 sync:(BOOL)arg3 errorStringPtr:(id *)arg4;
- (id)copyDevicePath:(id)arg1 toLocalPath:(id)arg2 sync:(_Bool)arg3;
- (id)copyLocalPath:(id)arg1 toDevicePath:(id)arg2 sync:(_Bool)arg3;
- (id)copyLocalPath:(id)arg1 toLocalPath:(id)arg2 sync:(_Bool)arg3;
- (id)copyDevicePath:(id)arg1 toDevicePath:(id)arg2 sync:(_Bool)arg3;
- (id)_copyPath:(id)arg1 toPath:(id)arg2 sync:(_Bool)arg3 onDevice:(_Bool)arg4;
- (id)_transformPathForDevice:(id)arg1;
- (id)_additionalRsyncParameters;
- (id)_rsyncEnvironment;
- (id)copyLocalPath:(id)arg1 toLocalPath:(id)arg2 sync:(BOOL)arg3 withHardLinkDirs:(id)arg4;
- (id)systemBasePath;
- (id)softwareVersion;
- (void)createInstallWithName:(id)arg1 path:(id)arg2 buildables:(id)arg3 buildParameters:(id)arg4 killProcesses:(id)arg5 workspace:(id)arg6;
- (id)installSubstitutionPathsForDebugger;
- (_Bool)addUUIDToActiveInstalls:(id)arg1 errorString:(id *)arg2;
- (_Bool)copyBackActiveInstallsWithErrorString:(id *)arg1;
- (id)activeInstallsPath;
- (BOOL)canInstallBuildablesError:(id *)arg1;
- (id)preferredSDKForDeviceOptions:(id)arg1 error:(id *)arg2;
- (id)preferredArchitectureForDeviceOptions:(id)arg1 error:(id *)arg2;
- (id)supportedArchitecturesForBuildable:(id)arg1 buildParameters:(id)arg2 error:(id *)arg3;
- (BOOL)deviceSupportsBuildable:(id)arg1 buildParameters:(id)arg2 error:(id *)arg3;
- (long long)hostAuthenticatedOneLineCommand:(id)arg1 withArg:(id)arg2 result:(id *)arg3;
- (id)taskForHostCommand:(id)arg1 withArguments:(id)arg2 error:(id *)arg3;
- (long long)multiLineCommand:(id)arg1 onDevice:(_Bool)arg2 result:(id *)arg3;
- (long long)oneLineCommand:(id)arg1 onDevice:(_Bool)arg2 withArguments:(id)arg3 environment:(id)arg4 result:(id *)arg5;
- (id)multiLineCommand:(id)arg1 onDevice:(_Bool)arg2;
- (id)oneLineCommand:(id)arg1 onDevice:(_Bool)arg2 withArguments:(id)arg3 andEnvironment:(id)arg4;
- (id)_runTask:(id)arg1;
- (id)_runTask:(id)arg1 withOutputHandler:(CDUnknownBlockType)arg2;
- (id)supportedDeviceFamilies;
- (void)renameDevice:(id)arg1;
- (void)setName:(id)arg1;
- (_Bool)canRenameDevice;
- (BOOL)shouldPresentDeviceForBuildable:(id)arg1 buildParameters:(id)arg2 error:(id *)arg3;
- (_Bool)isWireless;
@property(readonly) _Bool isPasscodeLocked;
- (BOOL)isConcreteDevice;
- (BOOL)isGenericDevice;
- (id)initWithDeviceLocation:(id)arg1 extension:(id)arg2;

// Remaining properties
@property(readonly, getter=isAvailable) BOOL available;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, copy) NSString *identifier;
@property(readonly) BOOL isProxiedDevice;
@property(readonly, copy, nonatomic) NSString *modelCode;
@property(readonly, copy, nonatomic) NSString *modelName;
@property(readonly, copy, nonatomic) NSString *modelUTI;
@property(readonly, copy) NSString *name;
@property(readonly, copy) NSString *nameForDeveloperPortal;
@property(readonly, copy) NSString *nativeArchitecture;
@property(readonly, copy) NSString *operatingSystemBuild;
@property(readonly, copy) NSString *operatingSystemVersion;
@property(readonly, copy, nonatomic) NSString *operatingSystemVersionWithBuildNumber;
@property(readonly) DVTPlatform *platform;
@property(readonly, copy) NSString *platformIdentifier;
@property(readonly, copy) NSString *processorDescription;
@property(readonly, copy) NSSet *proxiedDevices;
@property(readonly) Class superclass;
@property(readonly) BOOL supportsProvisioning;
@property(readonly) NSError *unavailabilityError;

@end

@interface DVTBasicProxiediOSDevice : NSObject <DVTBasiciOSDevice>
{
}

+ (id)keyPathsForValuesAffectingNameForDeveloperPortal;
- (BOOL)deviceSupportsBuildable:(id)arg1 buildParameters:(id)arg2 error:(id *)arg3;
@property(readonly) _Bool deviceIsBusy;
@property(readonly) NSError *unavailabilityError;
@property(readonly, getter=isAvailable) BOOL available;
@property(readonly) NSString *adjustedOperatingSystemVersion;
- (id)supportedDeviceFamilies;
@property(readonly, copy) NSString *name;
@property(readonly, copy, nonatomic) NSString *modelCode;
@property(readonly, copy) NSString *identifier;
@property(readonly) DVTPlatform *platform;
@property(readonly, copy) NSString *platformIdentifier;
@property(readonly, copy) NSString *processorDescription;
@property(readonly) BOOL supportsProvisioning;
@property(readonly, copy) NSString *nameForDeveloperPortal;
@property(readonly, copy) NSSet *proxiedDevices;
@property(readonly, copy, nonatomic) NSString *operatingSystemVersionWithBuildNumber;
@property(readonly, copy) NSString *operatingSystemVersion;
@property(readonly, copy) NSString *operatingSystemBuild;
@property(readonly, copy) NSString *nativeArchitecture;
@property(readonly, copy, nonatomic) NSString *modelName;
@property(readonly, copy, nonatomic) NSString *modelUTI;
@property(readonly) BOOL isProxiedDevice;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

@interface DVTDownloadableIndexSourceiOS : DVTIndexBackedDownloadableProvider
{
}

- (id)baseURL;
- (id)userDefaultsKey;
- (id)identifier;

@end

@interface DVTProxiedDeviceSymbolsCoordinator : NSObject
{
    DVTFilePath *_symbolsPath;
    NSError *_downloadError;
    DVTDownloadableOperationDownload *_downloadOperation;
    DVTProxiediOSDevice *_device;
    NSString *_modelCode;
    DVTObservingToken *_modelCodeObserver;
    NSString *_operatingSystemVersion;
    DVTObservingToken *_operatingSystemVersionObserver;
    NSString *_operatingSystemBuild;
    DVTObservingToken *_operatingSystemBuildObserver;
    DVTPlatform *_platform;
    DVTObservingToken *_platformObserver;
}

@property(retain) DVTObservingToken *platformObserver; // @synthesize platformObserver=_platformObserver;
@property(retain) DVTPlatform *platform; // @synthesize platform=_platform;
@property(retain) DVTObservingToken *operatingSystemBuildObserver; // @synthesize operatingSystemBuildObserver=_operatingSystemBuildObserver;
@property(retain) NSString *operatingSystemBuild; // @synthesize operatingSystemBuild=_operatingSystemBuild;
@property(retain) DVTObservingToken *operatingSystemVersionObserver; // @synthesize operatingSystemVersionObserver=_operatingSystemVersionObserver;
@property(retain) NSString *operatingSystemVersion; // @synthesize operatingSystemVersion=_operatingSystemVersion;
@property(retain) DVTObservingToken *modelCodeObserver; // @synthesize modelCodeObserver=_modelCodeObserver;
@property(retain) NSString *modelCode; // @synthesize modelCode=_modelCode;
@property(retain) DVTProxiediOSDevice *device; // @synthesize device=_device;
@property(retain) DVTDownloadableOperationDownload *downloadOperation; // @synthesize downloadOperation=_downloadOperation;
@property(retain) NSError *downloadError; // @synthesize downloadError=_downloadError;
@property(retain) DVTFilePath *symbolsPath; // @synthesize symbolsPath=_symbolsPath;
- (void).cxx_destruct;
- (id)_downloadOpForSymbolsFileURL:(id)arg1 fromPath:(id)arg2 requireAuth:(BOOL)arg3 error:(id *)arg4;
- (void)_downloadSymbolsToFileURL:(id)arg1 fromServers:(id)arg2;
- (void)_downloadSymbolsToFileURL:(id)arg1;
- (void)_checkForSymbols;
- (void)_setUpPropertyObservers;
- (id)initWithDevice:(id)arg1;

@end

@interface DVTProxiediOSDevice : DVTBasicProxiediOSDevice
{
    DTDKRemoteDeviceToken *_token;
    DVTProxiedDeviceSymbolsCoordinator *_symbolsCoordinator;
}

+ (id)keyPathsForValuesAffectingIsAvailable;
+ (id)keyPathsForValuesAffectingDeviceIsBusy;
+ (id)keyPathsForValuesAffectingNativeArchitecture;
+ (id)keyPathsForValuesAffectingProcessorDescription;
+ (id)keyPathsForValuesAffectingOperatingSystemVersionWithBuildNumber;
+ (id)keyPathsForValuesAffectingAdjustedOperatingSystemVersion;
+ (id)keyPathsForValuesAffectingOperatingSystemBuild;
+ (id)keyPathsForValuesAffectingOperatingSystemVersion;
+ (id)keyPathsForValuesAffectingModelCode;
+ (id)keyPathsForValuesAffectingModelUTI;
+ (id)keyPathsForValuesAffectingModelName;
+ (id)keyPathsForValuesAffectingName;
+ (id)keyPathsForValuesAffectingIdentifier;
@property(retain) DVTProxiedDeviceSymbolsCoordinator *symbolsCoordinator; // @synthesize symbolsCoordinator=_symbolsCoordinator;
@property(readonly) DTDKRemoteDeviceToken *token; // @synthesize token=_token;
- (void).cxx_destruct;
- (BOOL)deviceSupportsBuildable:(id)arg1 buildParameters:(id)arg2 error:(id *)arg3;
- (id)unavailabilityError;
- (BOOL)isAvailable;
- (_Bool)deviceIsBusy;
- (id)primaryInstrumentsServer;
- (id)supportedDeviceFamilies;
- (BOOL)isProxiedDevice;
- (id)nativeArchitecture;
- (id)platform;
- (BOOL)supportsProvisioning;
- (id)platformIdentifier;
- (id)processorDescription;
- (id)operatingSystemVersionWithBuildNumber;
- (id)adjustedOperatingSystemVersion;
- (id)operatingSystemBuild;
- (id)operatingSystemVersion;
- (id)modelCode;
- (id)modelUTI;
- (id)modelName;
- (id)name;
- (id)identifier;
- (BOOL)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)proxiedDevices;
- (void)wasProxiedToDevice:(id)arg1;
- (id)initWithToken:(id)arg1;

@end

@interface DVTSimulatorProxyWrapper : DVTBasicProxiediOSDevice
{
    NSString *_identifier;
    DVTiPhoneSimulator *_companion;
}

+ (id)proxyWrapperForDevice:(id)arg1;
@property(readonly) __weak DVTiPhoneSimulator *companion; // @synthesize companion=_companion;
- (id)identifier;
- (void).cxx_destruct;
- (BOOL)isAvailable;
- (id)supportedDeviceFamilies;
- (BOOL)isProxiedDevice;
- (id)nativeArchitecture;
- (id)platform;
- (id)operatingSystemVersionWithBuildNumber;
- (id)operatingSystemBuild;
- (id)operatingSystemVersion;
- (id)processorDescription;
- (id)modelUTI;
- (id)modelCode;
- (id)modelName;
- (id)proxiedDevices;
- (BOOL)supportsProvisioning;
- (id)platformIdentifier;
- (id)name;

@end

@interface DVTiOSDevice : DVTAbstractiOSDevice <DVTDeviceApplicationInstaller, IDERunDestinationFallbackSelectorDeviceInfo, XCDTMobileIS_XPCDebuggingProcotol>
{
    NSObject<OS_dispatch_queue> *_deviceInstallQueue;
    DVTObservingToken *_developmentStateToken1;
    DVTObservingToken *_developmentStateToken2;
    DVTObservingToken *_developmentStateToken3;
    DVTObservingToken *_proxiedTokensObservingToken;
    DVTNotificationToken *_deviceProgressToken;
    DVTFuture *_wakeupInFlight;
    struct __CFDictionary *_xpcStdoutFDForPid;
    NSMutableSet *_proxiedDevices;
    BOOL _activityIsUserInitiated;
    BOOL _deviceIsBusy;
    BOOL _ignored;
    _Bool _deviceReady;
    _Bool _inHasConnected;
    BOOL _deviceInstallIsCancelled;
    BOOL _deviceIsTransient;
    DTDKRemoteDeviceToken *_token;
    long long _activityProgress;
    NSString *_activityTitle;
    NSError *_developerPrepError;
    IDELaunchParametersSnapshot *_scriptLaunchParameters;
    DTXChannel *_xpcAttachServiceChannel;
    DTXChannel *_xpcProxyAttachServiceChannel;
}

+ (id)keyPathsForValuesAffectingIsPasscodeLocked;
+ (id)keyPathsForValuesAffectingProcessorDescription;
+ (id)keyPathsForValuesAffectingIsUsedForDevelopment;
+ (id)keyPathsForValuesAffectingIgnored;
+ (id)keyPathsForValuesAffectingIsPaired;
+ (id)keyPathsForValuesAffectingIsWirelessEnabled;
+ (id)keyPathsForValuesAffectingAddresses;
+ (id)keyPathsForValuesAffectingHostname;
+ (id)keyPathsForValuesAffectingHasWiredConnection;
+ (id)keyPathsForValuesAffectingHasWirelessConnection;
+ (id)keyPathsForValuesAffectingIsWireless;
+ (void)presentError:(id)arg1;
+ (id)keyPathsForValuesAffectingStatusIsIndeterminate;
+ (id)keyPathsForValuesAffectingActivityProgress;
+ (id)keyPathsForValuesAffectingActivityVisible;
+ (id)keyPathsForValuesAffectingSystemApplications;
+ (id)keyPathsForValuesAffectingApplications;
+ (id)keyPathsForValuesAffectingDeviceIsPaired;
+ (id)keyPathsForValuesAffectingAvailable;
+ (id)keyPathsForValuesAffectingCanRename;
+ (id)keyPathsForValuesAffectingDeviceAttached;
+ (id)itemWithPlistRepresentation:(id)arg1;
+ (id)keyPathsForValuesAffectingNativeArchitecture;
+ (id)keyPathsForValuesAffectingUnavailabilityError;
+ (id)keyPathsForValuesAffectingMountPort;
+ (id)keyPathsForValuesAffectingNfsPort;
+ (id)keyPathsForValuesAffectingRsyncPort;
+ (id)keyPathsForValuesAffectingTelnetPort;
+ (id)keyPathsForValuesAffectingSshPort;
+ (id)keyPathsForValuesAffectingIsRunningSupportedOS;
+ (id)keyPathsForValuesAffectingIsSupportedHardware;
+ (id)keyPathsForValuesAffectingProvisioningProfiles;
+ (id)keyPathsForValuesAffectingName;
+ (id)keyPathsForValuesAffectingCanBeWatchCompanion;
+ (id)iPhoneDeviceWithDeviceToken:(id)arg1;
+ (id)alliOSDevices;
+ (void)initialize;
+ (id)keyPathsForValuesAffectingCanExecute;
+ (id)allDeveloperDiskImagePathsForPlatform:(id)arg1;
+ (id)pathForInternalExecutable:(id)arg1 searchInPlatform:(id)arg2;
@property(retain) DTXChannel *xpcProxyAttachServiceChannel; // @synthesize xpcProxyAttachServiceChannel=_xpcProxyAttachServiceChannel;
@property(retain) DTXChannel *xpcAttachServiceChannel; // @synthesize xpcAttachServiceChannel=_xpcAttachServiceChannel;
@property BOOL deviceIsTransient; // @synthesize deviceIsTransient=_deviceIsTransient;
@property(retain) IDELaunchParametersSnapshot *scriptLaunchParameters; // @synthesize scriptLaunchParameters=_scriptLaunchParameters;
@property BOOL deviceInstallIsCancelled; // @synthesize deviceInstallIsCancelled=_deviceInstallIsCancelled;
@property(retain) NSObject<OS_dispatch_queue> *deviceInstallQueue; // @synthesize deviceInstallQueue=_deviceInstallQueue;
@property(copy) NSError *developerPrepError; // @synthesize developerPrepError=_developerPrepError;
@property _Bool inHasConnected; // @synthesize inHasConnected=_inHasConnected;
@property _Bool deviceReady; // @synthesize deviceReady=_deviceReady;
@property(copy) NSString *activityTitle; // @synthesize activityTitle=_activityTitle;
- (void)setIgnored:(BOOL)arg1;
- (void).cxx_destruct;
- (void)_syncDeviceCrashLogsDirectoryWithCompletionHandler:(CDUnknownBlockType)arg1;
- (id)monitorWirelessConnection;
- (id)primaryInstrumentsServer;
- (id)platform;
- (BOOL)runningSupportedBuildForUITesting;
- (id)makeTransportForTestManagerService:(id *)arg1;
- (id)testHostPathForBuildableProduct:(id)arg1 buildParameters:(id)arg2 outError:(id *)arg3;
- (void)modifyTestingEnvironmentVariables:(id)arg1 host:(id)arg2 testBundlePath:(id)arg3;
- (id)deviceForRunningUnitTestsWithHost:(id)arg1 error:(id *)arg2;
- (_Bool)isPasscodeLocked;
- (id)processorDescription;
- (void)setUsedForDevelopment:(BOOL)arg1;
- (BOOL)isUsedForDevelopment;
- (BOOL)isIgnored;
- (_Bool)isPaired;
- (void)unpair;
- (_Bool)usesPairingRecord;
- (_Bool)canEnableWireless;
- (void)disableWireless;
- (id)enableWireless;
- (_Bool)isWirelessEnabled;
- (id)addresses;
- (id)hostname;
- (_Bool)hasWiredConnection;
- (_Bool)hasWirelessConnection;
- (_Bool)isWireless;
- (void)didBecomeActiveDeviceForRunContext:(id)arg1;
- (BOOL)deviceHasUI;
@property BOOL deviceIsBusy; // @synthesize deviceIsBusy=_deviceIsBusy;
@property(readonly, copy) NSString *description;
- (void)updateExpansionProgress:(double)arg1 withMessage:(id)arg2;
- (void)setDeviceIsBusyOnMainThread:(BOOL)arg1;
- (void)setStatusOnMainThread:(id)arg1 userInitiated:(BOOL)arg2 progress:(long long)arg3;
@property(readonly) BOOL statusIsIndeterminate;
@property BOOL activityIsUserInitiated; // @synthesize activityIsUserInitiated=_activityIsUserInitiated;
@property long long activityProgress; // @synthesize activityProgress=_activityProgress;
@property(readonly, getter=isActivityVisible) BOOL activityVisible;
@property(readonly) NSSet *systemApplications;
@property(readonly) NSSet *applications;
- (BOOL)canChangeDeviceSoftwareVersion;
- (_Bool)deviceIsPaired;
- (BOOL)isAvailable;
- (void)renameDevice:(id)arg1;
- (void)setName:(id)arg1;
- (BOOL)canRename;
@property(readonly) _Bool deviceHasWakeupToken;
@property(readonly) _Bool deviceAttached;
- (void)dealloc;
- (void)setCrashLogDirectory:(id)arg1;
- (id)plistRepresentation;
- (void)downloadOptimizationProfilesFromBundleIdentifiers:(id)arg1 orPaths:(id)arg2 toFilePath:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)downloadOptimizationProfilesFromBundleIdentifier:(id)arg1 orPath:(id)arg2 toFilePath:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (id)optimizationProfilesPathFromBundleIdentifier:(id)arg1;
- (id)scriptingEnvironment;
- (id)deviceSpecificOverridingPropertiesForBuildable:(id)arg1 withBaselineParameters:(id)arg2;
- (id)executionDisplayName;
- (id)supportedSDKsForBuildable:(id)arg1 buildParameters:(id)arg2 error:(id *)arg3;
- (BOOL)canBeDefaultDeviceForBuildable:(id)arg1 buildParameters:(id)arg2;
- (id)displayNameAdditionsWhenUsingArchitecture:(id)arg1 withSDK:(id)arg2;
- (id)supportedArchitectures;
- (id)nativeArchitecture;
- (BOOL)shouldPresentDeviceForBuildable:(id)arg1 buildParameters:(id)arg2 error:(id *)arg3;
- (id)errorMessageForBuildable:(id)arg1 buildParameters:(id)arg2;
- (BOOL)deviceSupportsBuildable:(id)arg1 buildParameters:(id)arg2 error:(id *)arg3;
- (id)supportedDeviceFamilies;
- (id)unavailabilityError;
- (id)_deviceIsUnpairedError;
@property(readonly, copy) NSString *mountOptions;
@property(readonly) long long mountPort;
@property(readonly) long long nfsPort;
@property(readonly) long long rsyncPort;
@property(readonly) long long telnetPort;
@property(readonly) long long sshPort;
- (_Bool)_askForAlternateApplicationIfNeeded:(id *)arg1;
- (BOOL)isRunningSupportedOS;
- (BOOL)isSupportedHardware;
- (BOOL)supportsProvisioning;
@property(readonly, nonatomic) NSString *ide_fallbackSelectorDeviceGroupingFamily;
- (id)deviceClassForDisplay;
- (void)uninstallProvisioningProfile:(id)arg1;
- (void)installProvisioningProfiles:(id)arg1;
- (BOOL)installProvisioningProfileAtURL:(id)arg1 error:(id *)arg2;
- (void)installProvisioningProfile:(id)arg1;
- (id)provisioningProfiles;
- (id)certificateUtilities;
- (BOOL)runsRemoteFromHostLauncher;
- (id)softwareVersion;
- (id)recordedFramesBacktraceRecordingDylibPath;
- (id)recordedFramesLibdispatchIntrospectionDylibPath;
- (BOOL)supportsAttachByPIDOrName;
- (id)operatingSystemVersionWithBuildNumber;
- (id)operatingSystemBuild;
- (id)operatingSystemVersion;
- (id)modelCode;
- (id)modelUTI;
- (id)modelName;
- (id)name;
- (id)displayOrder;
- (BOOL)canIgnore;
- (BOOL)canBeWatchCompanion;
- (unsigned long long)supportsFetchEvents;
- (BOOL)supportsRoutingCoverageFile;
- (BOOL)supportsLocationSimulation;
- (BOOL)supportsApplicationDataUploading;
- (void)cancelDeviceInstall;
- (id)initWithDeviceLocation:(id)arg1 extension:(id)arg2;
- (void)_respondToDeviceProgressNotification:(id)arg1;
@property(retain) DTDKRemoteDeviceToken *token; // @synthesize token=_token;
- (void)stopDebuggingXPCServices:(id)arg1 forPairedDevice:(BOOL)arg2;
- (void)xpcServiceObserved:(id)arg1 withProcessIdentifier:(int)arg2 requestedByProcess:(int)arg3 options:(id)arg4;
- (void)outputReceived:(id)arg1 fromProcess:(int)arg2 atTime:(unsigned long long)arg3;
- (void)debugXPCServices:(id)arg1 onPairedDevice:(BOOL)arg2 completionSemaphore:(id)arg3;
- (void)_setXPCAttachChannel:(id)arg1 ForPairedDevice:(BOOL)arg2;
- (id)_xpcChannelForPairedDevice:(BOOL)arg1;
- (unsigned long long)supportedLaunchOptions;
- (void)didFinishRunning;
- (id)startDebugServerServiceForLaunchSession:(id)arg1;
- (id)deviceArbitrationForcedCheckIn;
- (id)deviceArbitrationCheckIn;
- (BOOL)installApplicationWithLaunchSession:(id)arg1 error:(id *)arg2;
- (void)presentAlertForNoRoutingCoverageFileAtPath:(id)arg1;
- (BOOL)downloadApplicationDataToPath:(id)arg1 forInstalledApplicationWithBundleIdentifier:(id)arg2 error:(id *)arg3;
- (BOOL)uploadApplicationDataWithPath:(id)arg1 forInstalledApplicationWithBundleIdentifier:(id)arg2 error:(id *)arg3;
- (void)_storeAppDataSyncRecords:(id)arg1 forApplication:(id)arg2;
- (id)_appDataSyncRecordsForApplication:(id)arg1;
- (id)_customDataSpecifierForApplication:(id)arg1;
- (BOOL)rsyncInstallAppWithSession:(id)arg1 error:(id *)arg2;
- (BOOL)installForRsyncDeveloperModeWithSession:(id)arg1 error:(id *)arg2;
- (BOOL)installForNFSDeveloperModeWithSession:(id)arg1 error:(id *)arg2;
- (id)deviceInstallPathForLaunchSession:(id)arg1 andBuildProductsPath:(id)arg2;
- (BOOL)installForMobileInstallWithSession:(id)arg1 error:(id *)arg2;
- (BOOL)installForTestBundleWithSession:(id)arg1 error:(id *)arg2;
- (id)updatedTestConfiguration:(id)arg1 inDerivedDataLocation:(id)arg2 forRemoteDirectory:(id)arg3 error:(id *)arg4;
- (id)applicationForSession:(id)arg1;
- (id)deviceBuiltProductsDir;
- (id)deviceMountedProductsDir;
- (id)localBuiltProductsPathWithSession:(id)arg1 error:(id *)arg2;
- (id)buildParametersForLaunchSession:(id)arg1;
- (_Bool)_copyBackAlternateApplication:(id)arg1 atPath:(id *)arg2 error:(id *)arg3;
- (void)setInstallProgress:(long long)arg1 text:(id)arg2;
- (void)setInstallProgress:(long long)arg1 path:(id)arg2;
- (long long)updateInstalledApplicationsWithResult:(id *)arg1;
- (id)taskForDeviceCommand:(id)arg1 withArguments:(id)arg2 error:(id *)arg3;
- (void)installActivityDidEndInWorkspace:(id)arg1 withError:(id)arg2;
- (void)installActivityInWorkspace:(id)arg1 operationInProgress:(id)arg2 details:(id)arg3;
- (void)installActivityWillBeginInWorkspace:(id)arg1 withProductName:(id)arg2;
- (id)invokeUserScript:(id)arg1;
- (BOOL)canExecute;
- (void)hasDisconnected;
- (void)hasConnected;
- (id)_remoteDeviceProperties;
- (id)locateDeveloperRoot;
- (id)developerDiskImageSearchPaths;
- (id)_mountNFSBuildDir;
- (id)_openTCPRelayConnection;
- (BOOL)_hasSpringBoard;
- (BOOL)_bothHaveInternalSupport;
- (id)_transformPathForDevice:(id)arg1;
- (id)_deviceHostname;
- (id)_rsyncEnvironment;
- (id)enableKeyBasedSSH;
- (id)_additionalRsyncParameters;
- (id)_copyPath:(id)arg1 toPath:(id)arg2 sync:(_Bool)arg3 onDevice:(_Bool)arg4;
- (void)_closeConnection;
- (id)analysisOperationWithAnalysisToolService:(id)arg1 location:(id)arg2 workingDirectory:(id)arg3 workspaceFilePath:(id)arg4 projectFilePath:(id)arg5 outError:(id *)arg6;
- (CDUnknownBlockType)_analysisOperationWithAnalysisToolService:(id)arg1 location:(id)arg2 workingDirectory:(id)arg3 workspaceFilePath:(id)arg4 projectFilePath:(id)arg5 outError:(id *)arg6;
- (id)installApplicationSync:(id)arg1 options:(id)arg2;
- (id)installApplicationsSync:(id)arg1 options:(id)arg2;
- (void)uninstallApplications:(id)arg1;
- (id)uninstallApplicationWithBundleIdentifierSync:(id)arg1;
- (void)installApplications:(id)arg1 allowReplacing:(BOOL)arg2;
- (void)_installApplicationsImpl:(id)arg1 allowReplacing:(BOOL)arg2 options:(id)arg3 completionBlock:(CDUnknownBlockType)arg4;
- (void)processAppInstallSet:(id)arg1 appUninstallSet:(id)arg2 installOptions:(id)arg3 completionBlock:(CDUnknownBlockType)arg4;
- (void)processAppInstallSetLegacy:(id)arg1 appUninstallSet:(id)arg2 installOptions:(id)arg3 completionBlock:(CDUnknownBlockType)arg4;
- (id)validateApplicationAtPath:(id)arg1 forInstallationToToken:(id)arg2;
- (BOOL)_checkForARM64SliceAtPath:(id)arg1 executableName:(id)arg2 zipFile:(id)arg3 subpath:(id)arg4;
- (id)installedApplicationWithBundleIdentifier:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly, copy) NSMutableSet *mutableProxiedDevices; // @dynamic mutableProxiedDevices;
@property(readonly) Class superclass;

@end

@interface DVTiOSDeviceLocator : DVTDeviceLocator
{
    DVTNotificationToken *_deviceAttachedToken;
    DVTNotificationToken *_deviceDetachedToken;
    NSMapTable *_deviceObservingTokens;
    NSMutableSet *_savedDevices;
    NSSet *_placeholderDevices;
    NSSet *_platforms;
}

+ (BOOL)_ignoreMobileDevice;
+ (id)deviceLocator;
- (void).cxx_destruct;
- (BOOL)matchDevice:(id)arg1 againstOptions:(id)arg2 genericOnly:(BOOL)arg3 allowAliases:(BOOL)arg4;
- (BOOL)validateDeviceSpecifierOptions:(id)arg1 genericOnly:(BOOL)arg2 allowMultipleMatches:(BOOL)arg3 error:(id *)arg4;
- (id)deviceType;
- (void)presentError:(id)arg1;
- (void)deviceDetached:(id)arg1;
- (void)deviceAttached:(id)arg1;
- (id)iOSDeviceWithIdentifier:(id)arg1;
- (id)knownDeviceAtDeviceLocation:(id)arg1;
- (id)platforms;
- (id)deviceLocationScheme;
- (void)stopLocating;
- (void)startLocating;
- (void)forgetDevice:(id)arg1;
- (void)beginWatchingDevice:(id)arg1;
- (void)updateDefaultsForDevice:(id)arg1;
- (id)init;

@end

@interface DVTiOSDevicePlaceholder : DVTDevice
{
}

- (id)initWithPlatform:(id)arg1;
- (BOOL)isAvailable;
- (id)deviceType;
- (unsigned long long)supportsFetchEvents;
- (id)deviceForRunningUnitTestsError:(id *)arg1;
- (BOOL)supportsRecordedFrames;
- (BOOL)supportsPGOReturningError:(id *)arg1;
- (BOOL)supportsAttachByPIDOrName;
- (BOOL)supportsArchiving;
- (void)requestProcessInformationsOnPairedDevice:(BOOL)arg1 handler:(CDUnknownBlockType)arg2;
- (BOOL)supportsRunningExecutableAtPath:(id)arg1 usingArchitecture:(id)arg2 error:(id *)arg3;
- (BOOL)supportsExecutionForArchitecture:(id)arg1 launchSession:(id)arg2 error:(id *)arg3;
- (BOOL)canInstallBuildablesError:(id *)arg1;
- (id)analysisOperationWithAnalysisToolService:(id)arg1 location:(id)arg2 workingDirectory:(id)arg3 workspaceFilePath:(id)arg4 projectFilePath:(id)arg5 outError:(id *)arg6;
- (id)generalRunErrorWithLaunchSession:(id)arg1;
- (id)generalErrorWithVerb:(id)arg1 launchSession:(id)arg2;
- (id)errorMessageForBuildable:(id)arg1 buildParameters:(id)arg2;
- (id)deviceSpecificOverridingPropertiesForBuildable:(id)arg1 withBaselineParameters:(id)arg2;
- (id)supportedSDKsForBuildable:(id)arg1 buildParameters:(id)arg2 error:(id *)arg3;
- (id)supportedArchitecturesForBuildable:(id)arg1 buildParameters:(id)arg2 error:(id *)arg3;
- (id)nativeArchitecture;
- (id)supportedArchitectures;
- (BOOL)canBeDefaultDeviceForBuildable:(id)arg1 buildParameters:(id)arg2;
- (BOOL)isConcreteDevice;
- (BOOL)isGenericDevice;
- (id)displayOrder;
- (id)displayNameAdditionsWhenUsingArchitecture:(id)arg1 withSDK:(id)arg2;
- (id)name;

@end

@interface DVTiPhone : DVTiOSDevice
{
}

@end

@interface DVTiPhonePlaceholder : DVTiOSDevicePlaceholder
{
}

- (id)proxiedDevices;
- (BOOL)canBeWatchCompanion;

@end

@interface DVTiPhoneProvisioningProfileProvider : DVTProvisioningProfileProvider
{
}

+ (id)keyPathsForValuesAffectingAllProfiles;
+ (id)keyPathsForValuesAffectingAreProfilesLoaded;
- (BOOL)installHostProfiles:(id)arg1 error:(id *)arg2;
- (id)profileWithData:(id)arg1 error:(id *)arg2;
- (id)profileWithURL:(id)arg1 error:(id *)arg2;
- (BOOL)isProfileExpiringWithCodeSigningIdentity:(id)arg1 profileName:(id *)arg2;
- (id)expiringProfilesInExpansionContext:(id)arg1;
- (id)expiringProfiles;
- (id)allProfiles_sync;
- (id)allProfiles;
- (BOOL)areProfilesLoaded;
- (void)forceProfileLoading;
- (id)controller;
- (id)certificateUtilities;

@end

@interface DVTiPhoneSimulator : DVTAbstractiOSDevice <NSFileManagerDelegate, IDERunDestinationFallbackSelectorDeviceInfo, DVTDeviceApplicationProvider, XCDTMobileIS_XPCDebuggingProcotol>
{
    id <DVTCancellable> _deviceNotificationToken;
    id <DVTCancellable> _deviceSetNotificationToken;
    NSString *_displayOrder;
    struct __CFDictionary *_xpcStdoutFDForPid;
    NSString *_recordedFramesBacktraceRecordingDylibPath;
    NSSet *_applications;
    NSDictionary *_applicationsDict;
    DTXConnection *_instrumentsConnection;
    NSObject<OS_dispatch_semaphore> *_instrumentsConnectionSemaphore;
    int _simulatorPID;
    DVTPlatform *_platform;
    NSSet *_proxiedDevices;
    SimDevice *_device;
    DVTSimulatorApplication *_simulatorApplication;
    DTXChannel *_xpcAttachServiceChannel;
    DTXChannel *_xpcProxyAttachServiceChannel;
    DTAssetProviderService *_assetProvider;
}

+ (id)keyPathsForValuesAffectingState;
+ (id)simulatorWithDevice:(id)arg1;
+ (void)initialize;
+ (void)_trackPid:(int)arg1 forDevice:(id)arg2 launchService:(id)arg3;
+ (void)cleanUpSessionMap;
@property(retain) DTAssetProviderService *assetProvider; // @synthesize assetProvider=_assetProvider;
@property(retain) DTXChannel *xpcProxyAttachServiceChannel; // @synthesize xpcProxyAttachServiceChannel=_xpcProxyAttachServiceChannel;
@property(retain) DTXChannel *xpcAttachServiceChannel; // @synthesize xpcAttachServiceChannel=_xpcAttachServiceChannel;
@property int simulatorPID; // @synthesize simulatorPID=_simulatorPID;
@property(readonly) DVTSimulatorApplication *simulatorApplication; // @synthesize simulatorApplication=_simulatorApplication;
@property(retain) SimDevice *device; // @synthesize device=_device;
- (id)platform;
- (void).cxx_destruct;
- (id)launchApplicationWithBundleIdentifier:(id)arg1 withArguments:(id)arg2 environment:(id)arg3 options:(id)arg4;
- (BOOL)canInstallApplication;
- (id)runExecutableAtPath:(id)arg1 withArguments:(id)arg2 environment:(id)arg3 options:(id)arg4 terminationHandler:(CDUnknownBlockType)arg5;
- (BOOL)canRunExecutables;
- (void)stopDebuggingXPCServices:(id)arg1 forPairedDevice:(BOOL)arg2;
- (void)xpcServiceObserved:(id)arg1 withProcessIdentifier:(int)arg2 requestedByProcess:(int)arg3 options:(id)arg4;
- (void)outputReceived:(id)arg1 fromProcess:(int)arg2 atTime:(unsigned long long)arg3;
- (void)_debugXPCServices:(id)arg1 onChannel:(id)arg2 completionSemaphore:(id)arg3;
- (void)debugXPCServices:(id)arg1 onPairedDevice:(BOOL)arg2 completionSemaphore:(id)arg3;
- (id)primaryInstrumentsServer;
- (BOOL)installApplicationWithLaunchSession:(id)arg1 error:(id *)arg2;
- (id)_installedPathForBundleIdentifier:(id)arg1;
- (id)makeTransportForTestManagerService:(id *)arg1;
- (id)_waitForSimLaunchdToLoadENVAndReturnTestConnectionSocketPath:(id *)arg1;
- (BOOL)supportsTestManagerDaemon;
- (id)startAssetServerForApplicationAtPath:(id)arg1;
- (id)testArchitectureForBuildableProduct:(id)arg1 withBuildParameters:(id)arg2;
- (id)_availableArchitecturesForArchitecture:(id)arg1;
- (id)deviceForRunningUnitTestsWithHost:(id)arg1 error:(id *)arg2;
- (BOOL)testingShouldAttachDebuggerWithHost:(id)arg1;
- (id)testHostPathForBuildableProduct:(id)arg1 buildParameters:(id)arg2 outError:(id *)arg3;
- (id)taskForDeviceCommand:(id)arg1 withArguments:(id)arg2 error:(id *)arg3;
- (id)systemBasePath;
- (void)stopLocationSimulation;
- (void)simulateLocationWithLatitude:(id)arg1 longitude:(id)arg2;
@property(readonly, copy) NSString *description;
- (BOOL)attachedToTarget:(id)arg1 launchService:(id)arg2 error:(id *)arg3;
- (BOOL)launchSimulatedExecutable:(id)arg1 launchService:(id)arg2 error:(id *)arg3;
- (BOOL)_launchSimulatorAppForLaunchSession:(id)arg1 error:(id *)arg2;
- (_Bool)_launchSimulatorAppWithExternalDisplayType:(long long)arg1 andError:(id *)arg2;
- (_Bool)_launchSimulatorAppWithError:(id *)arg1;
- (void)transferDirectionsFileToBundlePath:(id)arg1 launchService:(id)arg2;
- (void)uploadApplicationDataToBundlePath:(id)arg1 launchService:(id)arg2;
- (void)presentErrorWithMessageText:(id)arg1 informativeText:(id)arg2;
- (id)simulatorDirectoriesForAppName:(id)arg1;
- (id)effectiveSDKVersion;
- (BOOL)fileManager:(id)arg1 shouldCopyItemAtPath:(id)arg2 toPath:(id)arg3;
- (BOOL)shouldProcessPath:(id)arg1;
@property(readonly) NSSet *systemApplications;
@property(readonly) NSSet *applications;
- (void)_updateApplications;
- (void)_launchSimulatorAndUpdateApplicationsWhenReady;
- (id)deviceSpecificOverridingPropertiesForBuildable:(id)arg1 withBaselineParameters:(id)arg2;
- (id)executionDisplayName;
- (id)supportedSDKsForBuildable:(id)arg1 buildParameters:(id)arg2 error:(id *)arg3;
- (BOOL)shouldPresentDeviceForBuildable:(id)arg1 buildParameters:(id)arg2 error:(id *)arg3;
- (BOOL)canBeDefaultDeviceForBuildable:(id)arg1 buildParameters:(id)arg2;
- (id)softwareVersion;
- (void)setDisplayOrder:(id)arg1;
- (id)displayOrder;
@property(readonly, copy) NSArray *supportedDeviceFamilies;
- (id)deviceType;
- (BOOL)isAvailable;
- (id)supportedArchitectures;
- (id)nativeArchitecture;
- (id)operatingSystemVersionWithBuildNumber;
- (id)operatingSystemBuild;
- (id)operatingSystemVersion;
- (void)renameDevice:(id)arg1;
- (void)setName:(id)arg1;
- (id)name;
- (BOOL)canIgnore;
- (BOOL)canRename;
- (BOOL)isProxiedDevice;
- (id)proxiedDevices;
- (BOOL)canBeWatchCompanion;
- (id)modelCode;
@property(readonly, nonatomic) NSString *ide_fallbackSelectorDeviceGroupingFamily;
- (id)modelUTI;
- (id)modelName;
- (void)downloadOptimizationProfilesFromBundleIdentifier:(id)arg1 orPaths:(id)arg2 toFilePath:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (BOOL)supportsPGOReturningError:(id *)arg1;
- (BOOL)supportsDisplayScaleOption;
- (BOOL)supportsRoutingCoverageFile;
- (void)performUbiquityFetchEvent;
- (BOOL)canPerformUbiquityFetchEvent;
- (void)performFetchEventForPID:(int)arg1;
- (id)recordedFramesBacktraceRecordingDylibPath;
- (id)recordedFramesLibdispatchIntrospectionDylibPath;
- (unsigned long long)supportsFetchEvents;
- (BOOL)supportsLocationSimulation;
- (unsigned long long)supportedLaunchOptions;
- (BOOL)supportsApplicationDataUploading;
- (id)launchApplicationWithBundleIdentifier:(id)arg1 andOptions:(id)arg2;
- (id)launchApplicationWithBundleIdentifier:(id)arg1;
- (id)spawnExecutableAtPath:(id)arg1 withOptions:(id)arg2 andTerminationHandler:(CDUnknownBlockType)arg3;
- (id)spawnExecutableAtPath:(id)arg1 withOptions:(id)arg2;
- (id)applicationIsInstalledWithBundleIdentifier:(id)arg1;
- (id)uninstallApplicationWithBundleIdentifier:(id)arg1 andOptions:(id)arg2;
- (id)uninstallApplicationWithBundleIdentifier:(id)arg1;
- (id)installApplicationAtPath:(id)arg1 withOptions:(id)arg2;
- (id)installApplicationAtPath:(id)arg1;
- (id)restoreContentsAndSettingsFrom:(id)arg1;
- (id)eraseContentsAndSettings;
- (id)shutdown;
- (id)bootWithOptions:(id)arg1;
- (id)boot;
@property(readonly) unsigned long long state;
@property(readonly) SimDeviceType *deviceInfo;
- (id)shutDownDevice;
- (id)startUpDevice;
- (unsigned long long)startupState;
- (BOOL)canStartUpAndShutDown;
- (void)dealloc;
@property(readonly) NSNumber *simulatedDeviceFamily;
- (_Bool)_canStartSession:(id *)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

@interface DVTiPhoneSimulatorLocator : DVTDeviceLocator
{
    _Bool _locating;
    SimDeviceSet *_deviceSet;
    id <DVTCancellable> _notificationToken;
}

+ (id)deviceLocator;
@property(readonly) SimDeviceSet *deviceSet; // @synthesize deviceSet=_deviceSet;
- (void).cxx_destruct;
- (void)unpairDevice:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)pairCompanionDevice:(id)arg1 withGizmoDevice:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)deleteDevice:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)_createDefaultPairsIfNeeded;
- (BOOL)matchDevice:(id)arg1 againstOptions:(id)arg2 genericOnly:(BOOL)arg3 allowAliases:(BOOL)arg4;
- (BOOL)validateDeviceSpecifierOptions:(id)arg1 genericOnly:(BOOL)arg2 allowMultipleMatches:(BOOL)arg3 error:(id *)arg4;
- (id)deviceType;
- (id)knownDeviceAtDeviceLocation:(id)arg1;
- (id)platforms;
- (id)deviceLocationScheme;
- (void)stopLocating;
- (id)deviceForSimDevice:(id)arg1;
- (void)startLocating;

@end

@interface DVTiPhoneTask : DVTTask
{
    NSArray *_originalArguments;
    NSString *_originalLaunchPath;
    DVTiOSDevice *_device;
}

@property(retain) DVTiOSDevice *device; // @synthesize device=_device;
- (void).cxx_destruct;
- (BOOL)launchRunningTerminationHandlerOnQueue:(id)arg1 error:(id *)arg2 terminationHandler:(CDUnknownBlockType)arg3;
- (id)description;

@end

@interface IDEAppStoreIdentityFilter : IDEArchiveIdentityFilter
{
    NSSet *_types;
    CDUnknownBlockType identityComparator;
    CDUnknownBlockType filterBlock;
}

@property(copy) CDUnknownBlockType filterBlock; // @synthesize filterBlock;
@property(copy) CDUnknownBlockType identityComparator; // @synthesize identityComparator;
- (void).cxx_destruct;
- (_Bool)shouldIncludeIdentity:(id)arg1;
- (id)allowedCertificateTypes;
- (id)initWithExtension:(id)arg1;

@end

@interface IDEAppStorePackager : IDEArchivePackager
{
}

- (id)symbolsFolderNameForArchive:(id)arg1;
- (id)createTempPathWithError:(id *)arg1;
- (id)packagingOperationForArchive:(id)arg1 withCodesignIdentity:(id)arg2 installerIdentity:(id)arg3 extraEntitlements:(id)arg4 includeSymbolCache:(BOOL)arg5 error:(id *)arg6;
- (id)signingOperationForArchive:(id)arg1 withCodesignIdentity:(id)arg2 extraEntitlements:(id)arg3 andError:(id *)arg4;
- (id)_packagingOperationForArchive:(id)arg1 withCodesignIdentity:(id)arg2 installerIdentity:(id)arg3 includeSymbolCache:(BOOL)arg4 temporaryDir:(id)arg5 operationGroup:(id)arg6 andError:(id *)arg7;
- (id)_symbolsOperationForArchive:(id)arg1 includeSymbolCache:(BOOL)arg2 temporaryDir:(id)arg3 operationGroup:(id)arg4 error:(id *)arg5;
- (id)_signingOperationForArchive:(id)arg1 withCodesignIdentity:(id)arg2 extraEntitlements:(id)arg3 temporaryDir:(id)arg4 operationGroup:(id)arg5 andError:(id *)arg6;
- (id)_preSigningOperationForArchive:(id)arg1 withCodesignIdentity:(id)arg2 temporaryDir:(id)arg3 operationGroup:(id)arg4 andError:(id *)arg5;
- (id)packageFilenameForArchive:(id)arg1;
- (id)identitiesForBundleIdentifier:(id)arg1 andIdentityFilter:(id)arg2;
- (id)symbolsPath;
- (id)codesignAllocatePath;
- (id)commandLineToolSearchPath;
- (id)tokenForProvisioningProfileNamed:(id)arg1;
- (id)tokenForSigningIdentityNamed:(id)arg1;
- (id)dontSignIdentity;
- (id)sdk;

@end

@interface IDERuniPhoneService : IDERunDeviceService
{
}

+ (id)capability;
+ (id)serviceIdentifierKey;
- (id)operationWorkerWithLaunchSession:(id)arg1 error:(id *)arg2;
- (id)capabilitySequenceForLaunchSession:(id)arg1;

@end

@interface IDEDebugiPhoneService : IDERuniPhoneService
{
}

+ (id)serviceIdentifierKey;

@end

@interface IDERuniPhoneSimulatorService : IDERunDeviceService
{
}

+ (id)capability;
+ (id)serviceIdentifierKey;
- (id)operationWorkerWithLaunchSession:(id)arg1 error:(id *)arg2;
- (id)capabilitySequenceForLaunchSession:(id)arg1;

@end

@interface IDEDebugiPhoneSimulatorService : IDERuniPhoneSimulatorService
{
}

+ (id)serviceIdentifierKey;
- (id)capabilitySequenceForLaunchSession:(id)arg1;

@end

@interface IDEDistributionMethodAdHoc : IDEDistributionMethodExport
{
}

- (id)summaryPaneNextButtonTitleOverride;
- (BOOL)supportsManifestDistribution;
- (id)packagingStepIdentifier;
- (id)exportStepName;
- (unsigned long long)provisioningProfileType;
- (id)provisioningProfilePlatform;
- (BOOL)wantsProvisioningProfiles;
- (id)installerCertificateKind;
- (id)certificateKind;
- (id)orderedDistributionStepClassNames;
- (id)subtitle;
- (id)shortTitle;
- (id)title;
- (id)commandLineName;
@property(readonly) DVTPlatform *supportedPlatform;
- (id)appStoreName;
- (_Bool)supportsDistributionOfArchive:(id)arg1;
- (double)sortOrder;

@end

@interface IDEDistributionMethodDevelopmentSigned : IDEDistributionMethodAdHoc
{
}

- (unsigned long long)provisioningProfileType;
- (id)certificateKind;
- (id)subtitle;
- (id)shortTitle;
- (id)title;
- (id)commandLineName;
- (id)supportedPlatform;
- (double)sortOrder;

@end

@interface IDEDistributionMethodEnterprise : IDEDistributionMethodExport
{
}

- (id)summaryPaneNextButtonTitleOverride;
- (BOOL)supportsManifestDistribution;
- (id)requiredTeamTypes;
- (id)packagingStepIdentifier;
- (id)exportStepName;
- (unsigned long long)provisioningProfileType;
- (id)provisioningProfilePlatform;
- (BOOL)wantsProvisioningProfiles;
- (id)installerCertificateKind;
- (id)certificateKind;
- (id)orderedDistributionStepClassNames;
- (id)subtitle;
- (id)shortTitle;
- (id)title;
- (id)commandLineName;
@property(readonly) DVTPlatform *supportedPlatform;
- (id)appStoreName;
- (_Bool)supportsDistributionOfArchive:(id)arg1;
- (double)sortOrder;

@end

@interface IDEDistributionMethodiOSAppStore : IDEDistributionMethodAppStore
{
}

- (id)packagingStepIdentifier;
- (id)requiredProfileEntitlements;
- (id)provisioningProfilePlatform;
- (BOOL)wantsProvisioningProfiles;
- (id)installerCertificateKind;
- (id)certificateKind;
- (id)shortTitle;
- (id)supportedPlatform;
- (id)appStoreName;
- (_Bool)supportsDistributionOfArchive:(id)arg1;

@end

@interface IDEDistributionMethodiOSAppStoreDistribution : IDEDistributionMethodiOSAppStore
{
}

- (id)subtitle;
- (id)title;
- (int)supportedTask;
- (double)sortOrder;

@end

@interface IDEDistributionMethodiOSAppStoreExport : IDEDistributionMethodiOSAppStore
{
}

- (BOOL)requiresDeveloperAccount;
- (id)exportStepName;
- (id)subtitle;
- (id)title;
- (int)supportedTask;
- (double)sortOrder;
- (id)commandLineName;

@end

@interface IDEDistributionMethodiOSAppStoreValidation : IDEDistributionMethodiOSAppStore
{
}

- (id)subtitle;
- (id)title;
- (int)supportedTask;
- (double)sortOrder;

@end

@interface IDEEmbeddedXCSpecProvider : NSObject
{
}

+ (id)XCSpecProvider_specifications;

@end

@interface IDEEntitlementsMerger : IDEArchivePackagerEntitlementsMerger
{
}

+ (id)genericallyDefinedProfileKeysToSkipWhenCopyingFromProfile;
+ (id)extraEntitlementsToSkipWhenCopying;

@end

@interface IDEGaugeDataProviderService_iOSDevice : IDEGaugeDataProviderService
{
    DTXChannel *_channel;
}

+ (id)remoteServerChannelIdentifier;
+ (id)observableAttributes;
@property(retain) DTXChannel *channel; // @synthesize channel=_channel;
- (void).cxx_destruct;
- (void)didStopSampling;
- (id)stopSamplingForPIDs:(id)arg1;
- (id)sampleAttributes:(id)arg1 forPIDs:(id)arg2;
- (id)startSamplingForPIDs:(id)arg1;
- (void)willStartSamplingAtTime:(double)arg1 withInterval:(double)arg2;

@end

@interface IDEGaugeDataProviderService_iOSDevice_Energy : IDEGaugeDataProviderService_iOSDevice
{
}

+ (id)remoteServerChannelIdentifier;
+ (id)observableAttributes;

@end

@interface IDEGaugeDataProviderService_iOSDevice_NetworkStatistics : IDEGaugeDataProviderService_iOSDevice
{
}

+ (id)remoteServerChannelIdentifier;
+ (id)observableAttributes;

@end

@interface IDEGaugeDataProviderService_iOSDevice_procinfo : IDEGaugeDataProviderService_iOSDevice
{
}

+ (id)remoteServerChannelIdentifier;
+ (id)observableAttributes;

@end

@interface IDEGaugeDataProviderService_iOSSimulator : IDEGaugeDataProviderService
{
}

@end

@interface IDEGaugeDataProviderService_iOSSimulator_Energy : IDEGaugeDataProviderService_iOSSimulator
{
}

+ (id)observableAttributes;
- (id)sampleAttributes:(id)arg1 forPIDs:(id)arg2;

@end

@interface IDEGaugeDataProviderService_iOSSimulator_NetworkStatistics : IDEGaugeDataProviderService_iOSSimulator
{
}

+ (id)observableAttributes;
- (id)sampleAttributes:(id)arg1 forPIDs:(id)arg2;

@end

@interface IDEGaugeDataProviderService_iOSSimulator_procinfo : IDEGaugeDataProviderService_iOSSimulator
{
}

+ (id)observableAttributes;
- (id)sampleAttributes:(id)arg1 forPIDs:(id)arg2;

@end

@interface IDEGaugeDataProviderService_iOSSimulator_resources : IDEGaugeDataProviderService_iOSDevice
{
}

+ (id)remoteServerChannelIdentifier;
+ (id)observableAttributes;

@end

@interface IDEIdentityToken : NSObject <IDEArchivePackagerIdentityToken>
{
    int _status;
    DVTSigningCertificate *_certificate;
    id <DVTProvisioningProfile> _provisioningProfile;
}

+ (id)tokenForSigningIdentityNamed:(id)arg1;
+ (id)tokenForProvisioningProfileNamed:(id)arg1;
+ (id)allTokensForBundleIdentifier:(id)arg1;
+ (id)allTokens;
+ (id)dontSignToken;
+ (id)tokenWithProfile:(id)arg1;
+ (id)tokenWithCertificate:(id)arg1;
+ (id)tokenWithCertificate:(id)arg1 andProfile:(id)arg2;
@property(readonly) int status; // @synthesize status=_status;
@property(readonly) id <DVTProvisioningProfile> provisioningProfile; // @synthesize provisioningProfile=_provisioningProfile;
@property(readonly) DVTSigningCertificate *certificate; // @synthesize certificate=_certificate;
- (void).cxx_destruct;
- (id)codesignParameterSnapshotIncludingProfile:(BOOL)arg1;
- (long long)compare:(id)arg1;
@property(readonly) unsigned long long hash;
- (BOOL)isEqual:(id)arg1;
@property(readonly, copy) NSString *description;
- (id)displayName;
- (id)unadornedDisplayName;
- (id)relatedTokenForKey:(id)arg1;
@property(readonly) NSString *teamID;
@property(readonly) NSString *certificateType;
@property(readonly) NSString *commonName;
- (id)certificateUtilities;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

@interface IDEMacAppStoreArchivePackager : IDEAppStorePackager
{
}

- (id)packageFilenameForArchive:(id)arg1;
- (id)_packagingOperationForArchive:(id)arg1 withCodesignIdentity:(id)arg2 installerIdentity:(id)arg3 includeSymbolCache:(BOOL)arg4 temporaryDir:(id)arg5 operationGroup:(id)arg6 andError:(id *)arg7;
- (id)sdk;
- (_Bool)supportsSymbolUploads;
- (_Bool)supportsInstallerSigning;
- (_Bool)supportsCodeSigning;

@end

@interface IDEInAppPurchaseArchivePackager : IDEMacAppStoreArchivePackager
{
}

- (id)_packagingOperationForArchive:(id)arg1 withCodesignIdentity:(id)arg2 installerIdentity:(id)arg3 includeSymbolCache:(BOOL)arg4 temporaryDir:(id)arg5 operationGroup:(id)arg6 andError:(id *)arg7;
- (_Bool)supportsSymbolUploads;
- (_Bool)supportsInstallerSigning;
- (_Bool)supportsCodeSigning;

@end

@interface IDEInstalliPhoneLauncher : IDERunOperationWorker
{
    DVTiOSDevice *_device;
}

@property(retain) DVTiOSDevice *device; // @synthesize device=_device;
- (void).cxx_destruct;
- (void)terminate;
- (void)start;
- (void)delayLaunchIfNeededFor15147964;
- (void)_setFinishedRunningWithError:(id)arg1;

@end

@interface IDEInstalliPhoneService : IDERunDeviceService
{
}

+ (id)capability;
- (id)operationWorkerWithLaunchSession:(id)arg1 error:(id *)arg2;

@end

@interface IDEInstalliPhoneSimulatorService : IDERunDeviceService
{
}

+ (id)capability;
- (id)operationWorkerWithLaunchSession:(id)arg1 error:(id *)arg2;

@end

@interface IDELaunchiPhoneLauncher : IDERunOperationWorker <DTMISProcessControlServiceAuthorizedAPI>
{
    DTXChannel *_serviceHubProcessControlChannel;
    DTXChannel *_assetServerChannel;
    DVTObservingToken *_passcodeLockedToken;
    BOOL _shouldSkipAppTermination;
    BOOL _launchingToDebug;
    DVTiOSDevice *_device;
}

@property(getter=isLaunchingToDebug) BOOL launchingToDebug; // @synthesize launchingToDebug=_launchingToDebug;
@property(retain) DVTiOSDevice *device; // @synthesize device=_device;
- (void).cxx_destruct;
- (id)_assetServerChannel;
- (id)_assetServerConnection;
- (void)setupAssetServerWithCompletion:(CDUnknownBlockType)arg1;
- (BOOL)setupOptimizationProfileGeneration;
- (void)primitiveInvalidate;
- (void)terminate;
- (void)_deviceWoke;
- (void)pidDiedCallback:(id)arg1;
- (void)_cancelServiceHubProcessControlChannel;
- (id)_serviceHubProcessControlChannel;
- (id)_bestPrimaryInstrumentsServer;
- (void)_setupPlainLaunching;
- (void)_setupDebugging;
- (void)_continueStarting;
- (void)start;
- (void)_holdExecutionWithError:(id)arg1;
- (void)_setFinishedRunningWithError:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

@interface IDELaunchiPhoneService : IDERunDeviceService
{
}

+ (id)capability;
- (id)operationWorkerWithLaunchSession:(id)arg1 error:(id *)arg2;

@end

@interface IDELaunchiPhoneSimulatorLauncher : IDERunOperationWorker <IDERunOperationWorkerChaining, DTMISProcessControlServiceAuthorizedAPI>
{
    BOOL _debugSessionStarted;
    BOOL _responsibleForTermination;
    BOOL _setUpSimulatorSessionForAttaching;
    BOOL _terminateCalled;
    BOOL _notifiedTracker;
    DVTDispatchLock *_lifeCycleLock;
    DVTObservingToken *_debugSessionStateObservingToken;
    BOOL _launchingToDebug;
    DVTiPhoneSimulator *_device;
    IDEPseudoTerminal *_pty;
    DTXChannel *_launchServiceChannel;
}

+ (unsigned long long)assertionBehaviorAfterEndOfEventForSelector:(SEL)arg1;
@property(retain) DTXChannel *launchServiceChannel; // @synthesize launchServiceChannel=_launchServiceChannel;
@property(retain) IDEPseudoTerminal *pty; // @synthesize pty=_pty;
@property(retain) DVTiPhoneSimulator *device; // @synthesize device=_device;
@property(getter=isLaunchingToDebug) BOOL launchingToDebug; // @synthesize launchingToDebug=_launchingToDebug;
- (void).cxx_destruct;
- (BOOL)_willUseExistingProcess:(id)arg1;
- (void)pidDiedCallback:(id)arg1;
- (void)_cancelProcessControlChannel;
- (id)_instrumentsProcessControlChannel;
- (void)launchCompleteWithAppPID:(int)arg1;
- (void)executionDidEnd;
- (void)terminate;
- (void)start;
- (void)_setUpSimulatorSessionForAttaching;
- (void)_finishCurrentWorkAndNotifyTracker:(id)arg1;
- (void)primitiveInvalidate;
- (id)initWithExtensionIdentifier:(id)arg1 launchSession:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

@interface IDELaunchiPhoneSimulatorService : IDERunDeviceService
{
}

+ (id)capability;
+ (void)initialize;
- (id)operationWorkerWithLaunchSession:(id)arg1 error:(id *)arg2;

@end

@interface IDEMobileDeviceArchiver : DVTStreamingZip
{
}

- (_Bool)extractStreamableZipAtPath:(id)arg1 toPath:(id)arg2 error:(id *)arg3;
- (_Bool)createStreamableZipOfDirectory:(id)arg1 atPath:(id)arg2 options:(id)arg3 error:(id *)arg4;

@end

@interface IDERuniPhonePlaceholderService : IDERunDeviceService
{
}

+ (id)capability;
- (id)operationWorkerWithLaunchSession:(id)arg1 error:(id *)arg2;

@end

@interface IDESimulateLocationiPhoneService : IDESimulateLocationService
{
}

- (BOOL)simulateLocationWithLatitude:(id)arg1 longitude:(id)arg2 error:(id *)arg3;
- (BOOL)stopLocationSimulationWithError:(id *)arg1;
- (id)_iPhone;

@end

@interface IDESimulateLocationiPhoneSimulatorService : IDESimulateLocationService
{
}

- (BOOL)simulateLocationWithLatitude:(id)arg1 longitude:(id)arg2 error:(id *)arg3;
- (BOOL)stopLocationSimulationWithError:(id *)arg1;
- (id)_simulator;

@end

@interface IDEiOSSDKPropertiesProvider : NSObject <DVTSDKPropertiesProvider>
{
}

+ (id)additionalDefaultPropertiesForSDK:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

@interface IDEiPhonePackager : IDEAppStorePackager
{
}

- (id)packageFilenameForArchive:(id)arg1;
- (id)_packagingOperationForArchive:(id)arg1 withCodesignIdentity:(id)arg2 installerIdentity:(id)arg3 includeSymbolCache:(BOOL)arg4 temporaryDir:(id)arg5 operationGroup:(id)arg6 andError:(id *)arg7;
- (id)sdk;
- (_Bool)supportsSymbolUploads;
- (_Bool)supportsInstallerSigning;
- (_Bool)supportsCodeSigning;

@end

@interface IDEiPhoneRunOperationWorkerGroup : IDERunOperationWorkerGroup
{
    DVTiOSDevice *device;
}

@property(retain) DVTiOSDevice *device; // @synthesize device;
- (void).cxx_destruct;
- (void)allSubworkersDidFinishWithError:(id)arg1;

@end

@interface XCWorkQueueCommandBuiltinInvocation_validationUtility : XCWorkQueueCommandBuiltinInvocation
{
    _Bool _archive;
    _Bool _verbose;
    _Bool _storeIssuesAreWarnings;
    _Bool _storeValidation;
    NSString *_application;
}

@property(retain) NSString *application; // @synthesize application=_application;
@property _Bool storeValidation; // @synthesize storeValidation=_storeValidation;
@property _Bool storeIssuesAreWarnings; // @synthesize storeIssuesAreWarnings=_storeIssuesAreWarnings;
@property _Bool verbose; // @synthesize verbose=_verbose;
@property _Bool archive; // @synthesize archive=_archive;
- (void).cxx_destruct;
- (BOOL)validateMedusaSupportWithInfoDictionary:(id)arg1 errors:(id *)arg2;
- (int)runTaskWithArguments:(id)arg1 environment:(id)arg2 workingDirectoryPath:(id)arg3 infd:(int)arg4 outerrfd:(int)arg5;

@end

@interface XCiPhoneSimulatorCodeSignContext : XCCodeSignContext
{
}

+ (id)codeSignNode:(id)arg1 withMacroExpansionScope:(id)arg2;
+ (id)prepareForCodeSigningWithMacroExpansionScope:(id)arg1 certificateUtilities:(id)arg2;
+ (BOOL)supportsIOSSigning;
+ (BOOL)supportsMacSigning;
+ (BOOL)supportsDeveloperIDSigning;

@end

@interface Xcode3PortalEntitlementsCoordinatorIOSPlatform : NSObject <IDEPortalEntitlementsCoordinatorPlatform>
{
    id <IDECapabilitiesContextProviding> _capabilitiesContext;
}

@property(retain, nonatomic) id <IDECapabilitiesContextProviding> capabilitiesContext; // @synthesize capabilitiesContext=_capabilitiesContext;
- (void).cxx_destruct;
- (id)willRequestProfileWithFeatures:(id)arg1 usingWildcardAppID:(BOOL)arg2;
- (id)didReadProfileFeatures:(id)arg1;
- (id)initWithCapabilitiesContext:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

@interface _IDEInstalliPhoneSimulatorWorker : IDERunOperationWorker
{
    DVTiPhoneSimulator *_device;
}

@property(retain) DVTiPhoneSimulator *device; // @synthesize device=_device;
- (void).cxx_destruct;
- (void)terminate;
- (void)start;
- (void)_setFinishedRunningWithError:(id)arg1;

@end

