//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#pragma mark Blocks

typedef void (^CDUnknownBlockType)(void); // return type and parameters are unknown

#pragma mark Named Structures

struct CGPoint {
    double _field1;
    double _field2;
};

struct CGRect {
    struct CGPoint _field1;
    struct CGSize _field2;
};

struct CGSize {
    double width;
    double height;
};

struct _NSRange {
    unsigned long long _field1;
    unsigned long long _field2;
};

#pragma mark Typedef'd Structures

typedef struct {
    double _field1;
    double _field2;
    double _field3;
    double _field4;
} CDStruct_d2b197d1;

#pragma mark -

//
// File: /Applications/Xcode-7GM.app/Contents/PlugIns/IDEQuickHelp.ideplugin/Contents/MacOS/IDEQuickHelp
// UUID: C073D819-20F6-3422-BE97-2D368259D45E
//
//                           Arch: x86_64
//                Current version: 8195.0.0
//          Compatibility version: 1.0.0
//                 Source version: 8195.0.0.0.0
//       Minimum Mac OS X version: 10.10.0
//                    SDK version: 10.11.0
//
// Objective-C Garbage Collection: Unsupported
//

@protocol DVTInvalidation <NSObject>
- (void)primitiveInvalidate;

@optional
+ (BOOL)supportsInvalidationPrevention;
+ (unsigned long long)assertionBehaviorForKeyValueObservationsAtEndOfEvent;
+ (unsigned long long)assertionBehaviorAfterEndOfEventForSelector:(SEL)arg1;
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly, nonatomic, getter=isValid) BOOL valid;
- (void)invalidate;
@end

@protocol DVTSourceExpressionSource <NSObject, DVTInvalidation>
@property(readonly, nonatomic) DVTSourceExpression *mouseOverExpression;
@property(readonly, nonatomic) struct CGRect currentSelectionFrame;
@property(readonly) DVTSourceExpression *contextMenuExpression;
@property(readonly, nonatomic) DVTSourceExpression *selectedExpression;
- (struct CGRect)expressionFrameForExpression:(DVTSourceExpression *)arg1;

@optional
@property(readonly) DVTSDK *sdk;
@property(readonly, nonatomic) DVTSourceLanguageService *languageService;
@property(readonly, nonatomic) NSString *selectedText;
@property(readonly) DVTSourceExpression *quickHelpExpression;
@end

@protocol DVTTextCompletionItemInfoProvider
- (void)infoViewControllerForAssociatedUSRs:(NSArray *)arg1 descriptionText:(NSAttributedString *)arg2 width:(double)arg3 context:(NSDictionary *)arg4 completionBlock:(void (^)(DVTViewController<DVTInvalidation> *))arg5;
- (void)infoViewControllerForCompletionItemName:(NSString *)arg1 container:(NSString *)arg2 symbolKind:(DVTSourceCodeSymbolKind *)arg3 displayText:(NSString *)arg4 descriptionText:(NSAttributedString *)arg5 width:(double)arg6 context:(NSDictionary *)arg7 completionBlock:(void (^)(DVTViewController<DVTInvalidation> *))arg8;
@end

@protocol IDECommandHandler <NSObject, NSUserInterfaceValidations>
@end

@protocol IDEQuickHelpDataContext <NSObject>
@property(readonly, nonatomic) DVTSourceCodeLanguage *preferredLanguage;
@property(readonly, nonatomic) NSString *preferredUsr;
@property(readonly, nonatomic) NSXMLElement *documentationMarkup;
@property(readonly, nonatomic) NSXMLElement *declarationSymbolMarkup;
@property(readonly, nonatomic) IDEIndexSymbol *indexSymbol;
- (void)enumerateRelatedDeclarationsUsingBlock:(void (^)(NSXMLElement *, char *))arg1;
- (void)enumerateOverriddenSymbolResolutionsUsingBlock:(void (^)(NSString *, char *))arg1;
@end

@protocol IDEQuickHelpDataContextService <NSObject>
- (void)quickHelpDataContextForLocation:(DVTTextDocumentLocation *)arg1 completionBlock:(void (^)(id <IDEQuickHelpDataContext>))arg2;
@end

@protocol IDEQuickHelpPlaceholderViewDelegate <NSObject>
- (void)placeholderView:(IDEQuickHelpPlaceholderView *)arg1 clickSearchButton:(id)arg2;
@end

@protocol IDESourceExpressionSource <DVTSourceExpressionSource>
- (BOOL)isExpressionModuleImport:(DVTSourceExpression *)arg1;
- (BOOL)isExpressionPoundImport:(DVTSourceExpression *)arg1;
- (BOOL)expressionContainsExecutableCode:(DVTSourceExpression *)arg1;
- (BOOL)isExpressionFunctionOrMethodCall:(DVTSourceExpression *)arg1;
- (BOOL)isExpressionInFunctionOrMethodBody:(DVTSourceExpression *)arg1;
- (BOOL)isExpressionFunctionOrMethodDefinition:(DVTSourceExpression *)arg1;
- (BOOL)isExpressionInPlainCode:(DVTSourceExpression *)arg1;
- (void)symbolsForExpression:(DVTSourceExpression *)arg1 inQueue:(NSObject<OS_dispatch_queue> *)arg2 completionBlock:(void (^)(IDEIndexCollection *, NSDictionary *))arg3;

@optional
- (BOOL)isLocationInFunctionOrMethodBody:(DVTTextDocumentLocation *)arg1;
- (NSString *)importStringInExpression:(DVTSourceExpression *)arg1;
@end

@protocol NSObject
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;
@property(readonly) unsigned long long hash;
- (struct _NSZone *)zone;
- (unsigned long long)retainCount;
- (id)autorelease;
- (oneway void)release;
- (id)retain;
- (BOOL)respondsToSelector:(SEL)arg1;
- (BOOL)conformsToProtocol:(Protocol *)arg1;
- (BOOL)isMemberOfClass:(Class)arg1;
- (BOOL)isKindOfClass:(Class)arg1;
- (BOOL)isProxy;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2 withObject:(id)arg3;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2;
- (id)performSelector:(SEL)arg1;
- (id)self;
- (Class)class;
- (BOOL)isEqual:(id)arg1;

@optional
@property(readonly, copy) NSString *debugDescription;
@end

@protocol NSPopoverDelegate <NSObject>

@optional
- (void)popoverDidClose:(NSNotification *)arg1;
- (void)popoverWillClose:(NSNotification *)arg1;
- (void)popoverDidShow:(NSNotification *)arg1;
- (void)popoverWillShow:(NSNotification *)arg1;
- (NSWindow *)detachableWindowForPopover:(NSPopover *)arg1;
- (void)popoverDidDetach:(NSPopover *)arg1;
- (BOOL)popoverShouldDetach:(NSPopover *)arg1;
- (BOOL)popoverShouldClose:(NSPopover *)arg1;
@end

@protocol NSTextDelegate <NSObject>

@optional
- (void)textDidChange:(NSNotification *)arg1;
- (void)textDidEndEditing:(NSNotification *)arg1;
- (void)textDidBeginEditing:(NSNotification *)arg1;
- (BOOL)textShouldEndEditing:(NSText *)arg1;
- (BOOL)textShouldBeginEditing:(NSText *)arg1;
@end

@protocol NSTextViewDelegate <NSTextDelegate>

@optional
- (void)textView:(NSTextView *)arg1 draggedCell:(id <NSTextAttachmentCell>)arg2 inRect:(struct CGRect)arg3 event:(NSEvent *)arg4;
- (void)textView:(NSTextView *)arg1 doubleClickedOnCell:(id <NSTextAttachmentCell>)arg2 inRect:(struct CGRect)arg3;
- (void)textView:(NSTextView *)arg1 clickedOnCell:(id <NSTextAttachmentCell>)arg2 inRect:(struct CGRect)arg3;
- (BOOL)textView:(NSTextView *)arg1 clickedOnLink:(id)arg2;
- (NSUndoManager *)undoManagerForTextView:(NSTextView *)arg1;
- (NSSharingServicePicker *)textView:(NSTextView *)arg1 willShowSharingServicePicker:(NSSharingServicePicker *)arg2 forItems:(NSArray *)arg3;
- (NSURL *)textView:(NSTextView *)arg1 URLForContentsOfTextAttachment:(NSTextAttachment *)arg2 atIndex:(unsigned long long)arg3;
- (NSArray *)textView:(NSTextView *)arg1 didCheckTextInRange:(struct _NSRange)arg2 types:(unsigned long long)arg3 options:(NSDictionary *)arg4 results:(NSArray *)arg5 orthography:(NSOrthography *)arg6 wordCount:(long long)arg7;
- (NSDictionary *)textView:(NSTextView *)arg1 willCheckTextInRange:(struct _NSRange)arg2 options:(NSDictionary *)arg3 types:(unsigned long long *)arg4;
- (NSMenu *)textView:(NSTextView *)arg1 menu:(NSMenu *)arg2 forEvent:(NSEvent *)arg3 atIndex:(unsigned long long)arg4;
- (long long)textView:(NSTextView *)arg1 shouldSetSpellingState:(long long)arg2 range:(struct _NSRange)arg3;
- (BOOL)textView:(NSTextView *)arg1 doCommandBySelector:(SEL)arg2;
- (BOOL)textView:(NSTextView *)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementString:(NSString *)arg3;
- (NSArray *)textView:(NSTextView *)arg1 completions:(NSArray *)arg2 forPartialWordRange:(struct _NSRange)arg3 indexOfSelectedItem:(long long *)arg4;
- (NSString *)textView:(NSTextView *)arg1 willDisplayToolTip:(NSString *)arg2 forCharacterAtIndex:(unsigned long long)arg3;
- (void)textViewDidChangeTypingAttributes:(NSNotification *)arg1;
- (void)textViewDidChangeSelection:(NSNotification *)arg1;
- (NSDictionary *)textView:(NSTextView *)arg1 shouldChangeTypingAttributes:(NSDictionary *)arg2 toAttributes:(NSDictionary *)arg3;
- (BOOL)textView:(NSTextView *)arg1 shouldChangeTextInRanges:(NSArray *)arg2 replacementStrings:(NSArray *)arg3;
- (NSArray *)textView:(NSTextView *)arg1 willChangeSelectionFromCharacterRanges:(NSArray *)arg2 toCharacterRanges:(NSArray *)arg3;
- (struct _NSRange)textView:(NSTextView *)arg1 willChangeSelectionFromCharacterRange:(struct _NSRange)arg2 toCharacterRange:(struct _NSRange)arg3;
- (BOOL)textView:(NSTextView *)arg1 writeCell:(id <NSTextAttachmentCell>)arg2 atIndex:(unsigned long long)arg3 toPasteboard:(NSPasteboard *)arg4 type:(NSString *)arg5;
- (NSArray *)textView:(NSTextView *)arg1 writablePasteboardTypesForCell:(id <NSTextAttachmentCell>)arg2 atIndex:(unsigned long long)arg3;
- (void)textView:(NSTextView *)arg1 draggedCell:(id <NSTextAttachmentCell>)arg2 inRect:(struct CGRect)arg3 event:(NSEvent *)arg4 atIndex:(unsigned long long)arg5;
- (void)textView:(NSTextView *)arg1 doubleClickedOnCell:(id <NSTextAttachmentCell>)arg2 inRect:(struct CGRect)arg3 atIndex:(unsigned long long)arg4;
- (void)textView:(NSTextView *)arg1 clickedOnCell:(id <NSTextAttachmentCell>)arg2 inRect:(struct CGRect)arg3 atIndex:(unsigned long long)arg4;
- (BOOL)textView:(NSTextView *)arg1 clickedOnLink:(id)arg2 atIndex:(unsigned long long)arg3;
@end

@protocol NSUserInterfaceValidations
- (BOOL)validateUserInterfaceItem:(id <NSValidatedUserInterfaceItem>)arg1;
@end

@protocol WebFrameLoadDelegate <NSObject>

@optional
- (void)webView:(WebView *)arg1 didCreateJavaScriptContext:(JSContext *)arg2 forFrame:(WebFrame *)arg3;
- (void)webView:(WebView *)arg1 windowScriptObjectAvailable:(WebScriptObject *)arg2;
- (void)webView:(WebView *)arg1 didClearWindowObject:(WebScriptObject *)arg2 forFrame:(WebFrame *)arg3;
- (void)webView:(WebView *)arg1 willCloseFrame:(WebFrame *)arg2;
- (void)webView:(WebView *)arg1 didCancelClientRedirectForFrame:(WebFrame *)arg2;
- (void)webView:(WebView *)arg1 willPerformClientRedirectToURL:(NSURL *)arg2 delay:(double)arg3 fireDate:(NSDate *)arg4 forFrame:(WebFrame *)arg5;
- (void)webView:(WebView *)arg1 didChangeLocationWithinPageForFrame:(WebFrame *)arg2;
- (void)webView:(WebView *)arg1 didFailLoadWithError:(NSError *)arg2 forFrame:(WebFrame *)arg3;
- (void)webView:(WebView *)arg1 didFinishLoadForFrame:(WebFrame *)arg2;
- (void)webView:(WebView *)arg1 didReceiveIcon:(NSImage *)arg2 forFrame:(WebFrame *)arg3;
- (void)webView:(WebView *)arg1 didReceiveTitle:(NSString *)arg2 forFrame:(WebFrame *)arg3;
- (void)webView:(WebView *)arg1 didCommitLoadForFrame:(WebFrame *)arg2;
- (void)webView:(WebView *)arg1 didFailProvisionalLoadWithError:(NSError *)arg2 forFrame:(WebFrame *)arg3;
- (void)webView:(WebView *)arg1 didReceiveServerRedirectForProvisionalLoadForFrame:(WebFrame *)arg2;
- (void)webView:(WebView *)arg1 didStartProvisionalLoadForFrame:(WebFrame *)arg2;
@end

@interface IDEQuickHelpActionManager : NSObject
{
    IDEQuickHelpQueryResult *_queryResult;
    id <DVTSourceExpressionSource> _sourceExpressionSource;
}

@property __weak id <DVTSourceExpressionSource> sourceExpressionSource; // @synthesize sourceExpressionSource=_sourceExpressionSource;
@property __weak IDEQuickHelpQueryResult *queryResult; // @synthesize queryResult=_queryResult;
- (void).cxx_destruct;
- (void)_workspaceOpenForURL:(id)arg1;
- (void)openItemInDocumentationOrganizer:(id)arg1;
- (void)_showDeclarationLocationForCurrentSymbol;
- (id)bestIndexSymbolForSearchResultFromQuery:(id)arg1;
- (void)showHeaderFileFromSelectionSource;
- (void)showHeaderFile:(id)arg1;
- (void)showDocumentation:(id)arg1;
- (void)handleLinkClickWithActionInformation:(id)arg1;
- (void)handleUsrLinkClick:(id)arg1 forPlatformName:(id)arg2 sdkVersion:(id)arg3 language:(id)arg4;
- (void)handleFileColonSlashSlashLinkClick:(id)arg1;
- (void)handleFileColonSlashSlashLinkClick:(id)arg1 forPlatformName:(id)arg2 sdkVersion:(id)arg3;
- (id)urlFromLinkClickActionInformation:(id)arg1;
- (id)_relativePathMinusAppleWebDataPrefixForURL:(id)arg1;
- (id)initWithQueryResult:(id)arg1 sourceExpressionSource:(id)arg2;

@end

@interface IDEQuickHelpCommandHandler : NSObject <IDECommandHandler>
{
}

+ (id)handlerForAction:(SEL)arg1 withSelectionSource:(id)arg2;
- (void)_showQuickHelpInternal:(id)arg1;
- (void)showQuickHelp:(id)arg1;
- (void)showDocumentationForSymbol:(id)arg1;
- (BOOL)validateUserInterfaceItem:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

@interface IDEQuickHelpCompletionInfoViewController : DVTViewController <NSTextViewDelegate>
{
    IDEQuickHelpController *_quickHelpController;
    NSTextField *_textField;
    struct CGSize _renderedTextSize;
}

+ (id)defaultViewNibName;
@property struct CGSize renderedTextSize; // @synthesize renderedTextSize=_renderedTextSize;
@property(retain) IDEQuickHelpController *quickHelpController; // @synthesize quickHelpController=_quickHelpController;
@property NSTextField *textField; // @synthesize textField=_textField;
- (void).cxx_destruct;
- (void)primitiveInvalidate;
- (void)viewDidInstall;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

@interface IDEQuickHelpContentCreator : NSObject
{
    unsigned long long _exclusionMask;
}

@property unsigned long long exclusionMask; // @synthesize exclusionMask=_exclusionMask;
- (id)contentForXMLCommentBlock:(id)arg1 withQueryResult:(id)arg2;
- (id)contentForQueryResult:(id)arg1;
- (id)_declarationFromElement:(id)arg1;
- (id)elementForLinkingString:(id)arg1 withURL:(id)arg2 titleAttribute:(id)arg3 elementName:(id)arg4;
- (id)elementForUnlinkedString:(id)arg1 elementName:(id)arg2;
- (id)elementForWrappedHTMLString:(id)arg1 elementName:(id)arg2;

@end

@interface IDEQuickHelpController : NSObject <WebFrameLoadDelegate, DVTInvalidation>
{
    DVTSourceExpression *_selectedSourceExpression;
    NSString *_quickHelpContent;
    NSString *_placeholderString;
    BOOL _showsDocumentationSearch;
    WebView *_backgroundWebView;
    WebView *_targetWebView;
    struct CGSize _renderedContentSize;
    IDEQuickHelpQueryResult *_queryResult;
    DVTPerformanceMetric *_perfMetric;
}

+ (void)loadXSLTStylesheet;
+ (void)initialize;
@property(retain) DVTPerformanceMetric *perfMetric; // @synthesize perfMetric=_perfMetric;
@property(retain) IDEQuickHelpQueryResult *queryResult; // @synthesize queryResult=_queryResult;
@property struct CGSize renderedContentSize; // @synthesize renderedContentSize=_renderedContentSize;
@property(retain) WebView *backgroundWebView; // @synthesize backgroundWebView=_backgroundWebView;
@property(retain) WebView *targetWebView; // @synthesize targetWebView=_targetWebView;
@property BOOL showsDocumentationSearch; // @synthesize showsDocumentationSearch=_showsDocumentationSearch;
@property(retain) NSString *placeholderString; // @synthesize placeholderString=_placeholderString;
@property(retain) NSString *quickHelpContent; // @synthesize quickHelpContent=_quickHelpContent;
@property(retain) DVTSourceExpression *selectedSourceExpression; // @synthesize selectedSourceExpression=_selectedSourceExpression;
- (void).cxx_destruct;
- (void)primitiveInvalidate;
- (void)showDefaultHelpMessage;
- (id)localizedDefaultMessageString;
- (void)displayMessage:(id)arg1 withTitle:(id)arg2;
- (void)handleLinkClickWithActionInformation:(id)arg1;
- (void)renderWebView:(id)arg1 withHTML:(id)arg2 viewWidth:(double)arg3;
- (void)webView:(id)arg1 didFinishLoadForFrame:(id)arg2;
- (void)updateRenderedContentSize;
- (void)updateRenderedContentSizeForFrame:(id)arg1;
- (void)generateContentForDataContext:(id)arg1 fromSource:(id)arg2;
- (void)generateContentForSourceExpression:(id)arg1 fromSource:(id)arg2;
- (void)generateContentForSourceExpression:(id)arg1 container:(id)arg2 symbolKind:(id)arg3 context:(id)arg4;
- (void)generateHTMLForDataContext:(id)arg1 inExpressionSource:(id)arg2 allowFallback:(BOOL)arg3;
- (void)generateHTMLForSymbol:(id)arg1 fromQueryDictionary:(id)arg2 inExpressionSource:(id)arg3 context:(id)arg4;
- (void)generateHTMLFromResult:(id)arg1;
- (void)generateHTMLFromResult:(id)arg1 xmlCommentBlock:(id)arg2 symbol:(id)arg3;
- (id)contentCreator;
- (id)mode;
@property(readonly) NSString *declaredInHeaderFileName;
@property(readonly) NSString *qualifiedName;
@property(readonly) NSString *tokenName;
@property(readonly) id <DVTSourceExpressionSource> sourceExpressionSource;
- (id)sourceExpressionWindow;
- (void)showHeaderFile:(id)arg1;
- (void)showDocumentation:(id)arg1;
- (void)closeQuickHelp;
- (void)showQuickHelp;
- (id)init;
- (id)localizedDefaultDescriptionString;
- (id)localizedMultipleResultsSearchInDocViewerString;
- (id)localizedSearchForSelectionInDocViewerString;
- (id)localizedNoSelectionString;
- (id)localizedCannotDetermineSymbolString;
- (id)localizedMultipleResultsFoundString;
- (id)localizedSymbolNotFoundString;
- (id)localizedTemplateForDocumentationNotFoundForTokenName;
- (id)localizedDocumentationNotFoundString;
- (id)localizedQuickHelpTitleString;
- (id)_safeShortTitleStringFromSelection:(id)arg1;
- (id)localizedTemplateForDocumentationNotFound;

// Remaining properties
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly) Class superclass;
@property(readonly, nonatomic, getter=isValid) BOOL valid;
@property(readonly) DVTViewController *viewControllerWithContent; // @dynamic viewControllerWithContent;

@end

@interface IDEQuickHelpData : NSObject
{
}

+ (id)typeForSymbolKind:(id)arg1 inContainerWithSymbolKind:(id)arg2;
+ (id)sdkFromDocument:(id)arg1 inWorkspace:(id)arg2;
+ (id)sdkFromExpressionSource:(id)arg1 fallbackURL:(id)arg2;
+ (void)indexSymbolForSourceExpression:(id)arg1 fromSource:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
+ (void)quickHelpDataContextForSourceExpression:(id)arg1 fromSource:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
+ (id)_indexQueriesSharedQueue;
- (void)queryCommentXMLFromIndexSymbol:(id)arg1 expressionSource:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (void)queryResultForIndexSymbol:(id)arg1 expressionSource:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (void)generateQueryResultForSourceExpression:(id)arg1 fromSource:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;

@end

@interface IDEQuickHelpDataContextDefault : NSObject <IDEQuickHelpDataContext>
{
    IDEIndexSymbol *_indexSymbol;
}

+ (id)fixedUpSymbolForDocLookup:(id)arg1;
@property(readonly, nonatomic) IDEIndexSymbol *indexSymbol; // @synthesize indexSymbol=_indexSymbol;
- (void).cxx_destruct;
- (void)enumerateRelatedDeclarationsUsingBlock:(CDUnknownBlockType)arg1;
- (void)enumerateOverriddenSymbolResolutionsUsingBlock:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) DVTSourceCodeLanguage *preferredLanguage;
@property(readonly, nonatomic) NSString *preferredUsr;
@property(readonly, nonatomic) NSXMLElement *documentationMarkup;
@property(readonly, nonatomic) NSXMLElement *declarationSymbolMarkup;
- (id)initWithIDEIndexSymbol:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

@interface IDEQuickHelpIndexCompletionItemInfoProvider : NSObject <DVTTextCompletionItemInfoProvider>
{
}

- (void)_observeQuickHelpControllerForContent:(id)arg1 altContent:(id)arg2 width:(double)arg3 completionBlock:(CDUnknownBlockType)arg4;
- (void)infoViewControllerForAssociatedUSRs:(id)arg1 descriptionText:(id)arg2 width:(double)arg3 context:(id)arg4 completionBlock:(CDUnknownBlockType)arg5;
- (void)infoViewControllerForCompletionItemName:(id)arg1 container:(id)arg2 symbolKind:(id)arg3 displayText:(id)arg4 descriptionText:(id)arg5 width:(double)arg6 context:(id)arg7 completionBlock:(CDUnknownBlockType)arg8;

@end

@interface IDEQuickHelpInspectorController : IDEQuickHelpController
{
    IDEQuickHelpInspectorViewController *_inspectorViewController;
    DVTObservingToken *_mainViewControllerObservingToken;
    DVTObservingToken *_selectionSourceExpressionObservingToken;
}

@property(retain) IDEQuickHelpInspectorViewController *inspectorViewController; // @synthesize inspectorViewController=_inspectorViewController;
- (void).cxx_destruct;
- (void)primitiveInvalidate;
- (void)inspectorWillUninstall;
- (void)inspectorDidInstall;
- (void)endTrackingOfCurrentExpressionSelectionSource;
- (void)beginTrackingExpressionSelectionSource:(id)arg1;
- (void)beginTrackingMainViewController;
- (void)selectedExpressionDidChange;
- (void)cancelContentGeneration;
- (void)_generateContentForSelectedExpression;
- (id)contentCreator;
- (id)mode;
- (id)sourceExpressionWindow;
- (void)closeQuickHelp;
- (void)showQuickHelp;
- (id)initWithViewController:(id)arg1;

@end

@interface IDEQuickHelpInspectorViewController : IDEInspectorViewController <IDEQuickHelpPlaceholderViewDelegate>
{
    IDEQuickHelpInspectorController *_inspectorController;
    DVTObservingToken *_renderedContentSizeObservingToken;
    DVTNotificationToken *_frameChangeToken;
    NSTrackingArea *_mouseTracking;
    IDEQuickHelpPlaceholderView *_placeholderView;
    WebPreferences *_webPreferences;
    WebView *_webView;
}

@property WebView *webView; // @synthesize webView=_webView;
@property(retain) IDEQuickHelpPlaceholderView *placeholderView; // @synthesize placeholderView=_placeholderView;
- (void).cxx_destruct;
- (void)placeholderView:(id)arg1 clickSearchButton:(id)arg2;
- (void)mouseExited:(id)arg1;
- (void)unregisterForMouseEvents;
- (void)registerForMouseEvents;
- (id)webView:(id)arg1 contextMenuItemsForElement:(id)arg2 defaultMenuItems:(id)arg3;
- (unsigned long long)webView:(id)arg1 dragDestinationActionMaskForDraggingInfo:(id)arg2;
- (void)webView:(id)arg1 decidePolicyForNavigationAction:(id)arg2 request:(id)arg3 frame:(id)arg4 decisionListener:(id)arg5;
- (void)handleLinkClickWithActionInformation:(id)arg1;
- (BOOL)inspectorIsActive;
- (void)primitiveInvalidate;
- (void)viewWillUninstall;
- (void)viewDidInstall;
- (void)awakeFromNib;
- (void)_contentDidChange:(id)arg1;
- (void)_setPlaceholder:(id)arg1;
- (void)_webViewFrameDidChange:(id)arg1;
- (void)adjustInspectorHeightForContentSize:(struct CGSize)arg1;
- (void)_configurePlaceholderView;
- (void)_configureWebViewFonts;
- (void)_configureWebView;
- (void)loadView;
- (id)nibBundle;
- (id)nibName;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

@interface IDEQuickHelpOneShotController : IDEQuickHelpController <NSPopoverDelegate>
{
    DVTObservingToken *_renderedContentSizeObservingToken;
    NSPopover *_popover;
    IDEQuickHelpOneShotWindowContentViewController *_contentViewController;
}

@property(retain) IDEQuickHelpOneShotWindowContentViewController *contentViewController; // @synthesize contentViewController=_contentViewController;
- (void).cxx_destruct;
- (void)primitiveInvalidate;
- (void)popoverDidClose:(id)arg1;
- (void)closeQuickHelp;
- (void)showQuickHelp;
- (void)_contentDidChange:(id)arg1;
- (void)_configurePlaceholderView;
- (void)showPanelAtPoint:(struct CGPoint)arg1 withContentSize:(struct CGSize)arg2;
- (void)_adjustPlaceholderHeight;
- (id)mode;
- (id)contentCreator;
- (id)sourceExpressionWindow;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

@interface IDEQuickHelpOneShotWindowContentViewController : DVTViewController <IDEQuickHelpPlaceholderViewDelegate>
{
    IDEQuickHelpController *_quickHelpController;
    IDEQuickHelpPlaceholderView *_placeholderView;
    WebView *_webView;
}

+ (id)defaultViewNibName;
@property WebView *webView; // @synthesize webView=_webView;
@property(retain) IDEQuickHelpController *quickHelpController; // @synthesize quickHelpController=_quickHelpController;
@property(retain) IDEQuickHelpPlaceholderView *placeholderView; // @synthesize placeholderView=_placeholderView;
- (void).cxx_destruct;
- (void)placeholderView:(id)arg1 clickSearchButton:(id)arg2;
- (void)primitiveInvalidate;
- (unsigned long long)webView:(id)arg1 dragDestinationActionMaskForDraggingInfo:(id)arg2;
- (void)webView:(id)arg1 decidePolicyForNavigationAction:(id)arg2 request:(id)arg3 frame:(id)arg4 decisionListener:(id)arg5;
- (id)webView:(id)arg1 contextMenuItemsForElement:(id)arg2 defaultMenuItems:(id)arg3;
- (void)handleLinkClickWithActionInformation:(id)arg1;
- (void)loadWebViewWithHTML:(id)arg1;
- (CDStruct_d2b197d1)contentInset;
- (void)viewWillUninstall;
- (void)viewDidInstall;
- (void)_configureWebView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

@interface IDEQuickHelpPlaceholderView : IDEUtilityPlaceholderView
{
    NSButton *_searchButton;
    id <IDEQuickHelpPlaceholderViewDelegate> _delegate;
}

@property __weak id <IDEQuickHelpPlaceholderViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain) NSButton *searchButton; // @synthesize searchButton=_searchButton;
- (void).cxx_destruct;
- (void)clickSearchButton:(id)arg1;
- (void)setShowsDocumentationSearch:(BOOL)arg1;
- (void)layoutBottomUp;
- (id)initWithFrame:(struct CGRect)arg1;

@end

@interface IDEQuickHelpQueries : NSObject
{
    NSArray *_docSetRecords;
}

+ (void)scheduleLoadingTokenCacheForEnabledDocSetsIfNeeded;
- (void).cxx_destruct;
- (void)queryDocSetsWithUSR:(id)arg1 language:(id)arg2 platform:(id)arg3 sdkVersion:(id)arg4 completionBlock:(CDUnknownBlockType)arg5;
- (void)queryDocSetsWithInfo:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)determineBestDocSetRecordsForQuery:(id)arg1;
- (id)tokensForSymbol:(id)arg1 useFallbackNameSearch:(BOOL)arg2;
- (id)predicateForName:(id)arg1 scope:(id)arg2 type:(id)arg3;
- (id)resultBySearchingClassHierarchyWithInfo:(id)arg1 ancestorMatchKey:(id)arg2 useFallbackNameSearch:(BOOL)arg3;
- (id)queryResultFromToken:(id)arg1 resultingFromQuery:(id)arg2 ancestorHierarchy:(id)arg3;

@end

@interface IDEQuickHelpQueryResult : NSObject
{
    id <DSAToken> _resultToken;
    NSXMLDocument *_XMLDescription;
    NSString *_symbolName;
    NSString *_parentName;
    NSArray *_ancestorNames;
    NSDictionary *_symbolDictionary;
    NSString *_qualifiedName;
    NSString *_platformFamilyName;
    NSString *_sdkVersion;
    id <IDEQuickHelpDataContext> _quickHelpDataContext;
}

+ (id)queryResultWithSymbolDictionary:(id)arg1;
+ (id)queryResultForToken:(id)arg1 ancestorHierarchy:(id)arg2;
@property(retain) id <IDEQuickHelpDataContext> quickHelpDataContext; // @synthesize quickHelpDataContext=_quickHelpDataContext;
@property(retain) NSString *sdkVersion; // @synthesize sdkVersion=_sdkVersion;
@property(retain) NSString *platformFamilyName; // @synthesize platformFamilyName=_platformFamilyName;
@property(copy) NSString *qualifiedName; // @synthesize qualifiedName=_qualifiedName;
@property(copy) NSDictionary *symbolDictionary; // @synthesize symbolDictionary=_symbolDictionary;
@property(copy) NSArray *ancestorNames; // @synthesize ancestorNames=_ancestorNames;
@property(copy) NSString *parentName; // @synthesize parentName=_parentName;
@property(copy, nonatomic) NSString *symbolName; // @synthesize symbolName=_symbolName;
@property(retain) NSXMLDocument *XMLDescription; // @synthesize XMLDescription=_XMLDescription;
@property(retain) id <DSAToken> resultToken; // @synthesize resultToken=_resultToken;
- (void).cxx_destruct;
@property(readonly) IDEIndexSymbol *indexSymbol;
@property(readonly, copy) NSXMLElement *relatedDeclarations;
@property(readonly, copy) NSXMLElement *relatedSampleCode;
@property(readonly, copy) NSXMLElement *relatedDocuments;
- (id)elementWithName:(id)arg1 listingNodes:(id)arg2;
@property(readonly, copy) NSXMLElement *relatedTokens;
@property(readonly, copy) NSXMLElement *returnValue;
@property(readonly, copy) NSXMLElement *parameters;
@property(readonly, copy) NSString *deprecationStatement;
@property(readonly, copy) NSString *generalAvailabilityAndVersionStatement;
@property(readonly, copy) NSString *message;
@property(readonly, copy) NSURL *declaredInURL;
@property(readonly, copy) NSXMLElement *declaration;
- (id)_declaration;
@property(readonly, copy) NSXMLElement *specialConsiderations;
@property(readonly, copy) NSXMLElement *discussion;
@property(readonly, copy) NSXMLElement *abstract;
- (id)contentElementWithName:(id)arg1 HTMLString:(id)arg2;
- (id)contentElementForXPath:(id)arg1;

@end

@interface IDEQuickHelpTextCompletionController : IDEQuickHelpController
{
}

- (void)showDefaultHelpMessage;
- (void)generateHTMLFromResult:(id)arg1;
- (id)sourceExpressionWindow;
- (void)closeQuickHelp;

@end

@interface IDEQuickHelpTextCompletionDataContext : NSObject <IDEQuickHelpDataContext>
{
    NSArray *_associatedUsrs;
    DVTSourceCodeLanguage *_language;
}

- (void).cxx_destruct;
- (void)enumerateRelatedDeclarationsUsingBlock:(CDUnknownBlockType)arg1;
- (void)enumerateOverriddenSymbolResolutionsUsingBlock:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) DVTSourceCodeLanguage *preferredLanguage;
@property(readonly, nonatomic) NSString *preferredUsr;
@property(readonly, nonatomic) NSXMLElement *documentationMarkup;
@property(readonly, nonatomic) NSXMLElement *declarationSymbolMarkup;
@property(readonly, nonatomic) IDEIndexSymbol *indexSymbol;
- (id)initWithAssociatedUSRs:(id)arg1 language:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

@interface NSFont (IDEQuickHelpNSFontAdditions)
- (id)dvt_nameVisibleToWebFontCache;
@end

@interface NSXMLElement (IDEQuickHelpAdditions)
- (id)dvt_tidiedElement;
- (void)dvt_setPreservesWhitespace:(BOOL)arg1;
@end

@interface _IDEQuickHelpCompletionInfoTextField : NSTextField
{
}

- (void)mouseDown:(id)arg1;

@end

@interface _IDEQuickHelpPluginPrivateClassForFindingBundle : NSObject
{
}

@end

