//
//  IDESourceCodeEditor.h
//  XVim
//
//  Created by Tomas Lundell on 1/04/12.
//  Copyright (c) 2012 __MyCompanyName__. All rights reserved.
//

#import <Foundation/Foundation.h>
#import "DVTSourceTextView.h"

@class IDEWorkspaceTabController;

@interface IDESourceCodeEditor : NSViewController
{
    NSScrollView *_scrollView;
    DVTSourceTextView *_textView;
    //IDESourceCodeEditorContainerView *_containerView;
    //DVTTextSidebarView *_sidebarView;
    NSArray *_currentSelectedItems;
    NSHashTable *_selectedExpressionObservers;
    NSHashTable *_mouseOverExpressionObservers;
    NSDictionary *_syntaxColoringContext;
    //DVTSourceExpression *_selectedExpression;
    //DVTSourceExpression *_mouseOverExpression;
    //IDESourceCodeNavigationRequest *_currentNavigationRequest;
    //IDESourceCodeHelpNavigationRequest *_helpNavigationRequest;
    struct dispatch_queue_s *_symbolLookupQueue;
    NSMutableArray *_stateChangeObservingTokens;
//    id <DVTObservingToken> _topLevelItemsObserverToken;
//    id <DVTObservingToken> _firstResponderObserverToken;
//    id <DVTObservingToken> _editorLiveIssuesEnabledObserverToken;
//    id <DVTObservingToken> _navigatorLiveIssuesEnabledObserverToken;
//    id _workspaceLiveSourceIssuesEnabledObserver;
//    id <DVTObservingToken> _needsDiagnosisObserverToken;
//    id <DVTObservingToken> _diagnosticItemsObserverToken;
//    NSOperationQueue *_diagnoseRelatedFilesQueue;
//    id <DVTObservingToken> _sessionInProgressObserverToken;
//    id _blueprintDidChangeNotificationObservingToken;
//    id _buildOperationOutputFilesObserver;
//    IDESourceCodeEditorAnnotationProvider *_annotationProvider;
//    IDEAnalyzerResultsExplorer *_analyzerResultsExplorer;
//    DVTScopeBarController *_analyzerResultsScopeBar;
//    IDENoteAnnotationExplorer *_noteAnnotationExplorer;
//    IDESingleFileProcessingToolbarController *_singleFileProcessingToolbarController;
    NSView *_emptyView;
    NSProgressIndicator *_contentGenerationProgressIndicator;
    NSTimer *_contentGenerationProgressTimer;
    NSOperationQueue *_tokenizeQueue;
//    DVTDispatchLock *_tokenizeAccessLock;
    unsigned long long _tokenizeGeneration;
    NSTrackingArea *_mouseTracking;
    NSDictionary *_previouslyRestoredStateDictionary;
    long long _previousLineNumber;
    unsigned long long _lastFocusedAnnotationIndex;
    struct _NSRange _lastEditedCharRange;
//    DVTTextDocumentLocation *_coninueToHereDocumentLocation;
//    IDEViewController<IDESourceEditorViewControllerHost> *_hostViewController;
    struct {
        unsigned int wantsDidScroll:1;
        unsigned int wantsDidFinishAnimatingScroll:1;
        unsigned int supportsContextMenuCustomization:1;
        unsigned int supportsAnnotationContextCreation:1;
        unsigned int wantsDidLoadAnnotationProviders:1;
        unsigned int reserved:3;
    } _hvcFlags;
    BOOL _trackingMouse;
    BOOL _initialSetupDone;
    BOOL _nodeTypesPrefetchingStarted;
}

+ (id)keyPathsForValuesAffectingIsWorkspaceBuilding;
+ (void)revertStateWithDictionary:(id)arg1 withSourceTextView:(id)arg2 withEditorDocument:(id)arg3;
+ (void)commitStateToDictionary:(id)arg1 withSourceTextView:(id)arg2;
+ (long long)version;
+ (void)configureStateSavingObjectPersistenceByName:(id)arg1;
//@property(readonly) IDESingleFileProcessingToolbarController *singleFileProcessingToolbarController; // @synthesize singleFileProcessingToolbarController=_singleFileProcessingToolbarController;
//@property DVTScopeBarController *analyzerResultsScopeBar; // @synthesize analyzerResultsScopeBar=_analyzerResultsScopeBar;
//@property(readonly) IDEAnalyzerResultsExplorer *analyzerResultsExplorer; // @synthesize analyzerResultsExplorer=_analyzerResultsExplorer;
//@property DVTSourceExpression *mouseOverExpression; // @synthesize mouseOverExpression=_mouseOverExpression;
//@property DVTSourceExpression *selectedExpression; // @synthesize selectedExpression=_selectedExpression;
@property(assign) /*IDESourceCodeEditorContainerView*/ NSView *containerView; // @synthesize containerView=_containerView;
@property(assign) DVTSourceTextView *textView; // @synthesize textView=_textView;
//@property NSScrollView *scrollView; // @synthesize scrollView=_scrollView;
- (id)_documentLocationForLineNumber:(long long)arg1;
- (void)_createFileBreakpointAtLocation:(long long)arg1;
- (id)_breakpointManager;
- (long long)_currentOneBasedLineNubmer;
- (id)currentEditorContext;
- (id)documentLocationForOpenQuicklyQuery:(id)arg1;
- (void)openQuicklyScoped:(id)arg1;
- (void)debugLogJumpToDefinitionState:(id)arg1;
- (id)_jumpToDefinitionOfExpression:(id)arg1 fromScreenPoint:(struct CGPoint)arg2 clickCount:(long long)arg3 modifierFlags:(unsigned long long)arg4;
- (void)_cancelHelpNavigationRequest;
- (void)_cancelCurrentNavigationRequest;
- (void)contextMenu_revealInSymbolNavigator:(id)arg1;
- (void)jumpToSelection:(id)arg1;
- (void)jumpToDefinitionWithShiftPlusAlternate:(id)arg1;
- (void)jumpToDefinitionWithAlternate:(id)arg1;
- (void)jumpToDefinition:(id)arg1;
- (void)revealInSymbolNavigator:(id)arg1;
- (unsigned long long)_insertionIndexUnderMouse;
- (id)_documentLocationUnderMouse;
- (id)_calculateContinueToHereDocumentLocation;
- (BOOL)validateMenuItem:(id)arg1;
- (void)menuNeedsUpdate:(id)arg1;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)mouseMoved:(id)arg1;
- (void)deregisterForMouseEvents;
- (void)registerForMouseEvents;
- (id)importStringInExpression:(id)arg1;
- (BOOL)expressionContainsExecutableCode:(id)arg1;
- (BOOL)isExpressionFunctionOrMethodCall:(id)arg1;
- (BOOL)isExpressionInFunctionOrMethodBody:(id)arg1;
- (BOOL)isExpressionFunctionOrMethodDefinition:(id)arg1;
- (BOOL)isExpressionWithinComment:(id)arg1;
- (void)symbolsForExpression:(id)arg1 inQueue:(struct dispatch_queue_s *)arg2 completionBlock:(id)arg3;
@property(readonly) struct CGRect currentSelectionFrame;
- (void)_invalidateExpressions;
- (void)_invalidateSelectionExpression;
- (void)_invalidateMouseOverExpression;
//@property(readonly) DVTSourceExpression *quickHelpExpression;
//@property(readonly) DVTSourceExpression *contextMenuExpression;
- (void)_updatedMouseOverExpression;
- (void)_updateSelectedExpression;
- (BOOL)_expression:(id)arg1 representsTheSameLocationAsExpression:(id)arg2;
- (id)_expressionAtCharacterIndex:(unsigned long long)arg1;
- (void)unregisterMouseOverExpressionObserver:(id)arg1;
- (void)registerMouseOverExpressionObserver:(id)arg1;
- (void)unregisterSelectedExpressionObserver:(id)arg1;
- (void)registerSelectedExpressionObserver:(id)arg1;
- (void)specialPaste:(id)arg1;
- (id)_specialPasteContext;
- (void)_changeSourceCodeLanguageAction:(id)arg1;
- (void)_useSourceCodeLanguageFromFileDataTypeAction:(id)arg1;
- (void)_askToPromoteToUnicodeSheetDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (void)_askToPromoteToUnicode;
- (void)_applyPerFileTextSettings;
- (void)textView:(id)arg1 doubleClickedOnCell:(id)arg2 inRect:(struct CGRect)arg3 atIndex:(unsigned long long)arg4;
- (void)textView:(id)arg1 clickedOnCell:(id)arg2 inRect:(struct CGRect)arg3 atIndex:(unsigned long long)arg4;
- (void)contextMenu_toggleIssueShown:(id)arg1;
- (void)toggleIssueShown:(id)arg1;
- (void)_enumerateDiagnosticAnnotationsInSelection:(id)arg1;
- (id)_jumpToAnnotationWithSelectedRange:(struct _NSRange)arg1 fixIt:(BOOL)arg2 backwards:(BOOL)arg3;
- (void)fixAllInScope:(id)arg1;
- (id)fixableDiagnosticAnnotationsInScope;
- (id)_diagnosticAnnotationsInScopeFixableOnly:(BOOL)arg1;
- (id)_diagnosticAnnotationsInRange:(struct _NSRange)arg1 fixableOnly:(BOOL)arg2;
- (void)_searchDocumentationForSelectedText:(id)arg1;
- (void)showQuickHelp:(id)arg1;
- (void)continueToHere:(id)arg1;
- (void)toggleInvisibleCharactersShown:(id)arg1;
- (void)toggleBreakpointAtCurrentLine:(id)arg1;
- (void)_stopShowingContentGenerationProgressInidcator;
- (void)_showContentGenerationProgressIndicatorWithDelay:(double)arg1;
- (void)_contentGenerationProgressTimerFired:(id)arg1;
- (void)_hideEmptyView;
- (void)_showEmptyViewWithMessage:(id)arg1;
- (void)_centerViewInSuperView:(id)arg1;
- (void)preprocessFile:(id)arg1;
- (void)showAssemblyCodeForFile:(id)arg1;
- (void)_processCurrentFileUsingBuildCommand:(int)arg1;
- (id)_singleFileProcessingFilePath;
- (void)startSingleProcessingModeForURL:(id)arg1;
@property(readonly) BOOL isWorkspaceBuilding;
- (void)stopNoteExplorer;
- (void)startNoteExplorerForItem:(id)arg1;
- (void)showErrorsOnly:(id)arg1;
- (void)showAllIssues:(id)arg1;
- (void)toggleMessageBubbles:(id)arg1;
- (void)hideAnalyzerExplorerAnimate:(BOOL)arg1;
- (void)showAnalyzerExplorerForMessage:(id)arg1 animate:(BOOL)arg2;
- (void)_startPrefetchingNodeTypesInUpDirection:(BOOL)arg1 initialLineRange:(struct _NSRange)arg2 noProgressIterations:(unsigned long long)arg3;
- (void)revertStateWithDictionary:(id)arg1;
- (void)commitStateToDictionary:(id)arg1;
- (void)configureStateSavingObservers;
- (id)_transientStateDictionaryForDocument:(id)arg1;
- (id)_stateDictionariesForDocuments;
- (id)cursorForAltTemporaryLink;
- (void)_textViewDidLoseFirstResponder;
- (BOOL)completingTextViewHandleCancel:(id)arg1;
- (void)textViewDidScroll:(id)arg1;
- (void)textViewDidFinishAnimatingScroll:(id)arg1;
- (id)textView:(id)arg1 menu:(id)arg2 forEvent:(id)arg3 atIndex:(unsigned long long)arg4;
- (void)tokenizableItemsForItemAtRealRange:(struct _NSRange)arg1 completionBlock:(id)arg2;
- (void)textViewBoundsDidChange:(id)arg1;
- (void)textView:(id)arg1 handleMouseDidExitSidebar:(id)arg2;
- (void)textView:(id)arg1 handleMouseDidMoveOverSidebar:(id)arg2 atLineNumber:(unsigned long long)arg3;
- (void)textView:(id)arg1 handleMouseDownInSidebar:(id)arg2 atLineNumber:(unsigned long long)arg3;
- (id)completingTextView:(id)arg1 documentLocationForWordStartLocation:(unsigned long long)arg2;
- (void)completingTextView:(id)arg1 willPassContextToStrategies:(id)arg2 atWordStartLocation:(unsigned long long)arg3;
- (void)textView:(id)arg1 didClickOnTemporaryLinkAtCharacterIndex:(unsigned long long)arg2 event:(id)arg3 isAltEvent:(BOOL)arg4;
- (void)_doubleClickOnTemporaryHelpLinkTimerExpired;
- (void)_doubleClickOnTemporaryLinkTimerExpired;
- (BOOL)textView:(id)arg1 shouldShowTemporaryLinkForCharacterAtIndex:(unsigned long long)arg2 proposedRange:(struct _NSRange)arg3 effectiveRanges:(id *)arg4;
- (void)textView:(id)arg1 didRemoveAnnotations:(id)arg2;
- (void)textViewDidLoadAnnotationProviders:(id)arg1;
- (id)annotationContextForTextView:(id)arg1;
- (id)syntaxColoringContextForTextView:(id)arg1;
- (BOOL)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)setupTextViewContextMenuWithMenu:(id)arg1;
- (void)setupGutterContextMenuWithMenu:(id)arg1;
- (void)textViewDidChangeSelection:(id)arg1;
- (void)textDidChange:(id)arg1;
- (void)removeVisualization:(id)arg1 fadeOut:(BOOL)arg2 completionBlock:(id)arg3;
- (void)addVisualization:(id)arg1 fadeIn:(BOOL)arg2 completionBlock:(id)arg3;
@property(readonly) NSArray *visualizations;
- (id)pathCell:(id)arg1 menuItemForNavigableItem:(id)arg2 defaultMenuItem:(id)arg3;
- (BOOL)pathCell:(id)arg1 shouldSeparateDisplayOfChildItemsForItem:(id)arg2;
- (id)startingLocationForFindBar:(id)arg1 findingBackwards:(BOOL)arg2;
- (void)dvtFindBar:(id)arg1 didUpdateCurrentResult:(id)arg2;
- (void)dvtFindBar:(id)arg1 didUpdateResults:(id)arg2;
- (void)_sourceCodeDocumentDidSave:(id)arg1;
- (void)_sourceCodeDocumentWillSave:(id)arg1;
- (void)didSetupEditor;
- (void)didSetupEditor_;
- (void)takeFocus;
- (BOOL)canBecomeMainViewController;
- (id)undoManagerForTextView:(id)arg1;
- (void)viewWillUninstall;
- (void)viewDidInstall;
- (void)contentViewDidCompleteLayout;
- (void)_doInitialSetup;
- (void)_liveIssuesPreferencesUpdatedInvalidateDiagnosticController:(BOOL)arg1;
- (void)_blueprintDidChangeForSourceCodeEditor:(id)arg1;
- (void)_endObservingDiagnosticItemsAndSessionInProgress;
- (void)_startObservingDiagnosticItemsAndSessionInProgress;
- (void)invalidate;
- (void)selectDocumentLocations:(id)arg1;
- (void)navigateToAnnotationWithRepresentedObject:(id)arg1 wantsIndicatorAnimation:(BOOL)arg2 exploreAnnotationRepresentedObject:(id)arg3;
- (id)currentSelectedDocumentLocations;
- (id)_currentSelectedLandmarkItem;
- (void)setCurrentSelectedItems:(id)arg1;
- (id)currentSelectedItems;
- (BOOL)_isCurrentSelectedItemsValid;
//@property IDEViewController<IDESourceEditorViewControllerHost> *hostViewController;
//@property(readonly) IDESourceCodeEditorAnnotationProvider *annotationProvider; // @synthesize annotationProvider=_annotationProvider;
- (id)mainScrollView;
//@property(readonly) IDESourceCodeDocument *sourceCodeDocument;
- (void)loadView;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2 document:(id)arg3;
- (id)initWithNibName_:(NSString*)nibName bundle:(NSBundle*)nibBundle document:(NSDocument*)nibDocument;

- (IDEWorkspaceTabController*)workspaceTabController;
- (NSRange)textView_:(NSTextView *)textView willChangeSelectionFromCharacterRange:(NSRange)oldSelectedCharRange toCharacterRange:(NSRange)newSelectedCharRange;

@end
