
typedef NS_ENUM(NSUInteger, MOTION_TYPE) {
    DEFAULT_MOTION_TYPE,
    CHARACTERWISE_INCLUSIVE,
    CHARACTERWISE_EXCLUSIVE,
    LINEWISE,
    BLOCKWISE,
};

NSString* XVimMotionTypeName(MOTION_TYPE motion_type);
